### ISSUE TITLE
Jobhost shutdown can cause in-flight executions to fail

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1112]
### Description
When the webjobs host recycles, we stop the TaskHubWorker so that no new events get processed. However, the way we stop the TaskHubWorker does not stop in-flight executions. Because of that, when the JobHost disposes of it's resources, we can get stacktraces like the following:

```
Function 'OrchestratorFunction (Orchestrator)' failed with an error. Reason: System.AggregateException: One or more errors occurred. (The activity function '*******' failed: "Failed to deserialize exception from TaskActivity: Unhandled exception while executing task: System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 68
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 54
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57
   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135
       at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Script.WebHost.ScriptLoggerFactory.CreateLogger(String categoryName) in C:\azure-webjobs-sdk-script\src\WebJobs.Script.WebHost\Diagnostics\ScriptLoggerFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.Log(LogLevel level, FunctionDescriptor descriptor, Guid functionId, String message, Exception exception) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 68
   at Microsoft.Azure.WebJobs.Host.Loggers.FunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\FunctionInstanceLogger.cs:line 54
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance instance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 87
   at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync(TriggeredFunctionData input, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 56
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskActivityShim.RunAsync(TaskContext context, String rawInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskActivityShim.cs:line 57
   at DurableTask.Core.TaskActivityDispatcher.<>c__DisplayClass12_1.<<OnProcessWorkItemAsync>b__1>d.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskActivityDispatcher.cs:line 135".
```

### Expected behavior
When WebJobs hosts recycle for any reason, in-flight executions are not at risk of failing because of it.

### Relevant source code snippets
```csharp

        internal async Task<bool> StopTaskHubWorkerIfIdleAsync()
        {
            using (await this.taskHubLock.AcquireAsync())
            {
                if (this.isTaskHubWorkerStarted &&
                    this.knownOrchestrators.Values.Count(info => !info.IsDeregistered) == 0 &&
                    this.knownActivities.Values.Count(info => !info.IsDeregistered) == 0)
                {
                    this.TraceHelper.ExtensionInformationalEvent(
                        this.Options.HubName,
                        instanceId: string.Empty,
                        functionName: string.Empty,
                        message: "Stopping task hub worker",
                        writeToUserLogs: true);

                    await this.taskHubWorker.StopAsync(isForced: true);
                    this.isTaskHubWorkerStarted = false;
                    return true;
                }
            }

            return false;
        }
```

Setting`isForced` to true means this is not a graceful shutdown, so we don't wait for inflight orchestrations before returning.

### Known workarounds
Using dedicated plan should greatly reduce the possibility of these errors, due to less frequent jobhost recycles, but it does not completely reduce the risk.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.8.3 or 2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0 (likely 1.0 and 3.0 as well)
- **Programming language used**: C# (likely JavaScript as well)

**Comment by cgillum** [comment]
Let's figure out how to make graceful shutdown work in a robust and reliable way as a default option for v2.1.1. I think we should also port this fix to the 1.x series (as a non-configurable default).

**Comment by cgillum** [comment]
This [most severe side-effect](https://github.com/Azure/azure-functions-durable-extension/issues/472) of this has been addressed in the v2.1.1 release, so I think we can safely punt this fix out.

**Comment by GavinOsborn** [comment]
If you think of the canonical slot based green/blue deployment scenario for most Azure compute these days this is critical.

If we can't gracefully drain traffic from one slot as we warm up the next without in-flight terminations then we introduce a greater chance of unwanted side effects as our activity functions potentially run multiple times.

If we own the activity function and any dependencies that they talk to then there are steps we can take to mitigate this but external dependencies (a 3rd party SaaS system for example) make this hard.

**Comment by ConnorMcMahon** [comment]
@cgillum,

What is the latest status update on this? If I remember correctly, the Function runtime team said their JobHost shutdown is fire and forget, so even if we try to gracefully shutdown we may not get the chance.

**Comment by ConnorMcMahon** [comment]
This work hasn't been started yet, so will likely be in next patch release after 2.2.0.

**Comment by ConnorMcMahon** [comment]
This will be partially resolved in 2.2.1 assuming you are using our graceful shutdown host.json setting.

**Comment by cgillum** [comment]
Doesn’t the “abort session” work that we did resolve this independent of the graceful shutdown?

**Comment by ConnorMcMahon** [comment]
Ah yes it should. For some reason, I was mixing this issue up with the notion that Functions runtime can shutdown while activity functions are still executing, resulting in us having to execute those again. (Essentially issue #344)

The use of graceful shutdown should hopefully prevent some of those cases, but I don't think we can ever fully eliminate the retry in that scenario, just hopefully more gracefully handle the visibility timeout.

**Comment by ConnorMcMahon** [comment]
Fixed with the upgrade to DurableTask.AzureStorage 1.7.5 in #1294.

**Comment by drdamour** [comment]
are there any docs around what a graceful shutdown is, and if we're supposed to write code in a certain way to leverage it?

**Comment by davidmrdavid** [comment]
@drdamour - regarding how to leverage it, I believe you can use CancellationTokens as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library?tabs=v4%2Ccmd#method-signature-parameters).

I believe a graceful shutdown is simply a shutdown where opt-in cancellation tokens are signaled so that user-code may perform some cleanup prior to the host terminating.

**Comment by drdamour** [comment]
@davidmrdavid  cool!  you aware of anything specific or unique to durable functions/entities coding

**Comment by davidmrdavid** [comment]
Not specifically, but I do see you created a ticket related to drain mode and entities which I assume is related to this. We can try to discuss the specifics of this _there_, assuming I'm correctly guessing you're asking about that :)
