### ISSUE TITLE
Error converting HttpRequest using Orchestrator from F#. Cannot access a closed Stream.

### ISSUE THREAD

**Issue by iskandersierra** [Azure/azure-functions-durable-extension#1138]
### Description
There seems to be a problem with any or both of the functions `ConvertHttpRequestMessage` and `ConvertHttpResponseMessage` on `DurableClient.cs` when using function `IDurableOrchestrationClient.CreateCheckStatusResponse` from F#.

### Expected behavior
When calling `IDurableOrchestrationClient.CreateCheckStatusResponse`, I expect the same behavior whether I call it using `HttpRequest` and `HttpRequestMessage`.

### Actual behavior
When using `HttpRequestMessage` the function works as expected, but when using `HttpRequest`, which is more convenient due to `IActionResult` for the responses, I get an error with the message `"Cannot access a closed Stream"`.

### Relevant source code snippets
This is the whole source code:
```fsharp
module Functions

open FSharp.Control.Tasks.V2
open Microsoft.AspNetCore.Http
open Microsoft.Azure.WebJobs
open Microsoft.Azure.WebJobs.Extensions.Http
open Microsoft.Azure.WebJobs.Extensions.DurableTask
open Microsoft.AspNetCore.Mvc
open Microsoft.Extensions.Logging
open Newtonsoft.Json
open System.IO
open System.Net
open System.Net.Http

[<Literal>]
let Orchestrate = "Orchestrate"

let readTextBody (request: HttpRequest) = task {
  use reader = new StreamReader(request.Body)
  return! reader.ReadToEndAsync()
}

let readTextMessageBody (request: HttpRequestMessage) = task {
  use! stream = request.Content.ReadAsStreamAsync()
  use reader = new StreamReader(stream)
  return! reader.ReadToEndAsync()
}

[<FunctionName(Orchestrate)>]
let orchestrate ([<OrchestrationTrigger>] context: IDurableOrchestrationContext) =
  task {
    let input = context.GetInput<string>()

    return sprintf "Hello, %s" input
  }

[<FunctionName("StartWithMessage")>]
let startWithMessage 
  ([<HttpTrigger(AuthorizationLevel.Function, "post", Route = null)>] req: HttpRequestMessage)
  (logger: ILogger)
  ([<DurableClient>] client: IDurableOrchestrationClient) =
  task {
    try
      let! request = req |> readTextMessageBody

      let! instanceId = client.StartNewAsync(Orchestrate, null, request)

      return client.CreateCheckStatusResponse(req, instanceId)
    with
    | exn ->
      logger.LogError(exn, exn.ToString())
      return req.CreateErrorResponse(HttpStatusCode.InternalServerError, exn)
  }

[<FunctionName("StartWithRequest")>]
let startWithRequest 
  ([<HttpTrigger(AuthorizationLevel.Function, "post", Route = null)>] req: HttpRequest)
  (logger: ILogger)
  ([<DurableClient>] client: IDurableOrchestrationClient) =
  task {
    try
      let! request = req |> readTextBody

      let! instanceId = client.StartNewAsync(Orchestrate, null, request)

      return client.CreateCheckStatusResponse(req, instanceId)
    with
    | exn ->
      logger.LogError(exn, exn.ToString())
      return StatusCodeResult(500) :> IActionResult
  }
```
You can find it in this [repro](https://github.com/iskandersierra/AzFuncClosedStreamBug)

#### When calling StartWithMessage:
```
POST http://localhost:7071/api/StartWithMessage

hello
```
the logs show successful result:
```
[1/2/2020 8:26:35 PM] Executing HTTP request: {
[1/2/2020 8:26:35 PM]   "requestId": "5c214640-76c6-46e3-b216-95aa8d4831f4",
[1/2/2020 8:26:35 PM]   "method": "POST",
[1/2/2020 8:26:35 PM]   "uri": "/api/StartWithMessage"
[1/2/2020 8:26:35 PM] }
[1/2/2020 8:26:35 PM] Executing 'StartWithMessage' (Reason='This function was programmatically called via the host APIs.', Id=0fb48cfe-f507-445b-8140-b9c7d4d258ef)
[1/2/2020 8:26:35 PM] 29c62d9eec81438688f4c3c1b5ea3088: Function 'Orchestrate (Orchestrator)' scheduled. Reason: NewInstance. IsReplay: False. State: Scheduled. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.0. SequenceNumber: 2.
[1/2/2020 8:26:35 PM] Executed 'StartWithMessage' (Succeeded, Id=0fb48cfe-f507-445b-8140-b9c7d4d258ef)
[1/2/2020 8:26:35 PM] Executed HTTP request: {
[1/2/2020 8:26:35 PM]   "requestId": "5c214640-76c6-46e3-b216-95aa8d4831f4",
[1/2/2020 8:26:35 PM]   "method": "POST",
[1/2/2020 8:26:35 PM]   "uri": "/api/StartWithMessage",
[1/2/2020 8:26:35 PM]   "identities": [
[1/2/2020 8:26:35 PM]     {
[1/2/2020 8:26:35 PM]       "type": "WebJobsAuthLevel",
[1/2/2020 8:26:35 PM]       "level": "Admin"
[1/2/2020 8:26:35 PM]     }
[1/2/2020 8:26:35 PM]   ],
[1/2/2020 8:26:35 PM]   "status": 202,
[1/2/2020 8:26:35 PM]   "duration": 200
[1/2/2020 8:26:35 PM] }
[1/2/2020 8:26:35 PM] Executing 'Orchestrate' (Reason='', Id=d280500b-c476-4251-84d5-855c19bbb015)
[1/2/2020 8:26:35 PM] 29c62d9eec81438688f4c3c1b5ea3088: Function 'Orchestrate (Orchestrator)' started. IsReplay: False. Input: (28 bytes). State: Started. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.0. SequenceNumber: 3.
[1/2/2020 8:26:35 PM] 29c62d9eec81438688f4c3c1b5ea3088: Function 'Orchestrate (Orchestrator)' completed. ContinuedAsNew: False. IsReplay: False. Output: (56 bytes). State: Completed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.0. SequenceNumber: 4.
[1/2/2020 8:26:35 PM] Executed 'Orchestrate' (Succeeded, Id=d280500b-c476-4251-84d5-855c19bbb015)
```

#### When calling StartWithRequest:
```
POST http://localhost:7071/api/StartWithRequest

hello
```
the logs show **failed** result:
```
[1/2/2020 8:26:39 PM] Executing HTTP request: {
[1/2/2020 8:26:39 PM]   "requestId": "53afa2a5-4df8-4977-a0ea-88e759a2d32e",
[1/2/2020 8:26:39 PM]   "method": "POST",
[1/2/2020 8:26:39 PM]   "uri": "/api/StartWithRequest"
[1/2/2020 8:26:39 PM] }
[1/2/2020 8:26:39 PM] Executing 'StartWithRequest' (Reason='This function was programmatically called via the host APIs.', Id=1b5ec15b-8ba8-45c5-854b-d26e751804be)
[1/2/2020 8:26:39 PM] 431d3e339c104876aba2fffc7b196278: Function 'Orchestrate (Orchestrator)' scheduled. Reason: NewInstance. IsReplay: False. State: Scheduled. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.0. SequenceNumber: 5.
[1/2/2020 8:26:39 PM] Executing 'Orchestrate' (Reason='', Id=cb3fcd0d-9466-41a6-80a5-c88ccf3c4139)
[1/2/2020 8:26:39 PM] 431d3e339c104876aba2fffc7b196278: Function 'Orchestrate (Orchestrator)' started. IsReplay: False. Input: (28 bytes). State: Started. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.0. SequenceNumber: 6.
[1/2/2020 8:26:39 PM] 431d3e339c104876aba2fffc7b196278: Function 'Orchestrate (Orchestrator)' completed. ContinuedAsNew: False. IsReplay: False. Output: (56 bytes). State: Completed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.1.0. SequenceNumber: 7.
[1/2/2020 8:26:39 PM] Executed 'Orchestrate' (Succeeded, Id=cb3fcd0d-9466-41a6-80a5-c88ccf3c4139)
[1/2/2020 8:26:39 PM] System.ObjectDisposedException: Cannot access a closed Stream.
[1/2/2020 8:26:39 PM]    at System.IO.MemoryStream.get_Position()
[1/2/2020 8:26:39 PM]    at Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream.get_Position()
[1/2/2020 8:26:39 PM]    at System.Net.Http.StreamContent.InitializeContent(Stream content, Int32 bufferSize)
[1/2/2020 8:26:39 PM]    at System.Net.Http.StreamContent..ctor(Stream content)
[1/2/2020 8:26:39 PM]    at Microsoft.AspNetCore.Mvc.WebApiCompatShim.HttpRequestMessageFeature.CreateHttpRequestMessage(HttpContext httpContext)
[1/2/2020 8:26:39 PM]    at Microsoft.AspNetCore.Mvc.WebApiCompatShim.HttpRequestMessageFeature.get_HttpRequestMessage()
[1/2/2020 8:26:39 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.ConvertHttpRequestMessage(HttpRequest request) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 546
[1/2/2020 8:26:39 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.CreateCheckStatusResponse(HttpRequest request, String instanceId, Boolean returnInternalServerErrorOnFailure) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 76
[1/2/2020 8:26:39 PM]    at Functions.startWithRequest@66-3.Invoke(String _arg2) in C:\Users\iskan\source\repos\AzFuncClosedStreamBug\AzFuncClosedStreamBugFSharp\Functions.fs:line 66
[1/2/2020 8:26:39 PM]    at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
[1/2/2020 8:26:39 PM] System.Private.CoreLib: Cannot access a closed Stream.
[1/2/2020 8:26:39 PM] Executed 'StartWithRequest' (Succeeded, Id=1b5ec15b-8ba8-45c5-854b-d26e751804be)
[1/2/2020 8:26:39 PM] Executed HTTP request: {
[1/2/2020 8:26:39 PM]   "requestId": "53afa2a5-4df8-4977-a0ea-88e759a2d32e",
[1/2/2020 8:26:39 PM]   "method": "POST",
[1/2/2020 8:26:39 PM]   "uri": "/api/StartWithRequest",
[1/2/2020 8:26:39 PM]   "identities": [
[1/2/2020 8:26:39 PM]     {
[1/2/2020 8:26:39 PM]       "type": "WebJobsAuthLevel",
[1/2/2020 8:26:39 PM]       "level": "Admin"
[1/2/2020 8:26:39 PM]     }
[1/2/2020 8:26:39 PM]   ],
[1/2/2020 8:26:39 PM]   "status": 500,
[1/2/2020 8:26:39 PM]   "duration": 98
[1/2/2020 8:26:39 PM] }
```

### Known workarounds
I didn't dig into why this is happening more than what is shown in the description. For now using `HttpRequestMessage` instead of `HttpRequest` do the trick, but it prevents me from using `IActionResult`.

### App Details

- **TargetFramework**: `netcoreapp3.0`
- **AzureFunctionsVersion**: `v3`
- **Microsoft.Azure.WebJobs.Extensions.DurableTask**: `2.1.0`
- **Microsoft.NET.Sdk.Functions**: `3.0.2`
- **Programming language used**: `FSharp`

**Comment by vladnega** [comment]
I am experiencing this issue as well in C#, azure functions v2, .netcore2.1. I believe it's happening because you are reading the stream at this line:
```
let! request = req |> readTextBody
```
If you remove this line, the `CreateCheckStatusResponse` would succeed.

Would be nice to get this issue fixed so that we can use `HttpRequest`.

**Comment by vladnega** [comment]
An workaround would be to rewrite your `readTextBody` function so that you reset your body `Stream`:
```fsharp
let readTextBody (request: HttpRequest) = task {
  use reader = new StreamReader(request.Body)
  let body = reader.ReadToEndAsync()
  request.Body <- new MemoryStream(Encoding.ASCII.GetBytes(body))
  return! body
}
```

**Comment by iskandersierra** [comment]
Hi @vladnega. Have you found the issue in the source code? I would like to fix the SDK instead of using a workaround. 
@cgillum, do you think is this a thing to fix in the SDK?

**Comment by vladnega** [comment]
@iskandersierra, I didn't have time to look in the source code, sorry.

**Comment by justinyoo** [comment]
> A workaround would be to rewrite your `readTextBody` function so that you reset your body `Stream`:
> 
> ```fsharp
> let readTextBody (request: HttpRequest) = task {
>   use reader = new StreamReader(request.Body)
>   let! body = reader.ReadToEndAsync()
>   request.Body <- new MemoryStream(Encoding.ASCII.GetBytes(body))
>   return body
> }
> ```

Just FYI, I've got the same issue in C# and @vladnega 's approach fixed mine, too.

I'm with my DurableTask extension version of 2.4.0.
