### ISSUE TITLE
NullReferenceException when Task returns void

### ISSUE THREAD

**Issue by mark-szabo** [Azure/azure-functions-durable-extension#1245]
A NullReferenceException is thrown when a Durable Function Task returns void like this and is called by a typed CallActivityAsync:

```csharp
[FunctionName("MyFunctions_RunTaskAsync")]
public async Task RunTaskAsync([ActivityTrigger] string input)
{
    ...
}
```

```csharp
await context.CallActivityAsync<bool>("MyFunctions_RunTaskAsync", input);
```

```
Function 'MyFunctions (Orchestrator)' failed with an error.Reason: System.NullReferenceException: Object reference not set to an instance of an object.
at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskToWorker[TResult](String name, String version, String taskList, Object[] parameters) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 80
at DurableTask.Core.TaskOrchestrationContext.ScheduleTask[TResult](String name, String version, Object[] parameters) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 70
at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 607
at MyNamespace.MyFunctions.RunOrchestrator(IDurableOrchestrationContext context)
```

**Comment by cgillum** [comment]
What happens if you use the non-generic overload of [CallActivityAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.durablecontextextensions.callactivityasync?view=azure-dotnet)?

```csharp
await context.CallActivityAsync("MyFunctions_RunTaskAsync", input);
```

**Comment by mark-szabo** [comment]
@cgillum Yup, that's the correct way to do, I know, but an internal NullReferenceException is not something the SDK should throw. Maybe an InvalidOperationException with some nice error message that you should call the non-generic method or something.

**Comment by ConnorMcMahon** [comment]
We had an internal customer hit this the other week, prioritizing this bug fix.

**Comment by wldevries** [comment]
A similar crash happens when the activity has an actual return type of `Task<bool>`
