### ISSUE TITLE
Sytem.NotSupported excpetion when trying to mock IDurableOrchestrationContext.CallSubOrchestratorAsync method.

### ISSUE THREAD

**Issue by brandon-de** [Azure/azure-functions-durable-extension#1308]
### Description
> Sytem.NotSupported exception when trying to use the moq frame work and mock calling a sub-orchestration with the method IDurableOrchestrationContext.CallSubOrchestratorAsync

> I tried to mock CallActivityAsync instead when calling the sub-orchestration because mocking CallActivityAsync works elsewhere in my code but in this instance the mock just returns a null

### Expected behavior
> No errors occur when setting up a mock for method 'CallSubOrchestratorAsync'

### Actual behavior
>Exception occurs 

``` System.NotSupportedException
  HResult=0x80131515
  Message=Unsupported expression: x => x.CallSubOrchestratorAsync<MyTestSubOrchDataResponse>("my-test-sub-orchestration", It.IsAny<MyTestSubOrchDataRequest>())
Extension methods (here: DurableContextExtensions.CallSubOrchestratorAsync) may not be used in setup / verification expressions.
  Source=Moq
  StackTrace:
   at Moq.Guard.IsOverridable(MethodInfo method, Expression expression)
   at Moq.InvocationShape..ctor(LambdaExpression expression, MethodInfo method, IReadOnlyList`1 arguments, Boolean exactGenericTypeArguments)
   at Moq.ExpressionExtensions.<Split>g__Split|4_1(Expression e, Expression& r, InvocationShape& p)
   at Moq.ExpressionExtensions.Split(LambdaExpression expression)
   at Moq.Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`3 setupLast)
   at Moq.Mock.Setup(Mock mock, LambdaExpression expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)C:\Git\Market
```

### Relevant source code snippets
```
                        _mockContext.Setup(
                             x => x.CallSubOrchestratorAsync<MyTestSubOrchDataResponse>(
                                "my-test-sub-orchestration",
                                 It.IsAny<MyTestSubOrchDataRequest>()
                             )
                         )
                        .ReturnsAsync(someRandomData);
```

### Known workarounds
>N/A

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: Microsoft.Azure.WebJobs.Extensions.DurableTask 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

**Comment by gashach** [comment]
you must mock CallSubOrchestratorAsync<T>(string, string, object). it is the implementation. in this case, object would be null i think.

**Comment by brandon-de** [comment]
> you must mock CallSubOrchestratorAsync(string, string, object). it is the implementation. in this case, object would be null i think.

@gashach thank you for the reply

I tried the following

`                         _mockContext.Setup(
                             x => x.CallSubOrchestratorAsync(
                                 It.IsAny<string>(),
                                 It.IsAny<string>(),
                                 It.IsAny<object>()
                             )
                         )
                        .Returns(Task.FromResult(someRandomData));`

and I still receive the following error

`System.NotSupportedException
  HResult=0x80131515
  Message=Unsupported expression: x => x.CallSubOrchestratorAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<object>())
Extension methods (here: DurableContextExtensions.CallSubOrchestratorAsync) may not be used in setup / verification expressions.
  Source=Moq
  StackTrace:
   at Moq.Guard.IsOverridable(MethodInfo method, Expression expression)
   at Moq.InvocationShape..ctor(LambdaExpression expression, MethodInfo method, IReadOnlyList`1 arguments, Boolean exactGenericTypeArguments)
   at Moq.ExpressionExtensions.<Split>g__Split|4_1(Expression e, Expression& r, InvocationShape& p)
   at Moq.ExpressionExtensions.Split(LambdaExpression expression)
   at Moq.Mock.SetupRecursive[TSetup](Mock mock, LambdaExpression expression, Func`3 setupLast)
   at Moq.Mock.Setup(Mock mock, LambdaExpression expression, Condition condition)
   at Moq.Mock`1.Setup[TResult](Expression`1 expression)
   at Woo.Kitting.Durable.Functions.Tests.UnitTests.RefreshKittingOrchestratorTest.Init() in 
`

**Comment by brandon-de** [comment]
@gashach sorry, I take it back I was still referencing the extension method when I was mocking CallSubOrchestratorAsync. Here is my new code:

`_mockContext.Setup(
                             x => x.CallSubOrchestratorAsync<SomeResponse>(
                                 "SomeFunctionName",
                                 It.IsAny<string>(),
                                 It.IsAny<object>()
                             )
                         )
                        .Returns(Task.FromResult(someResponseData));`

Thank you for your help!
