### ISSUE TITLE
Using Cosmos as Table storage and Azure Storage for queues

### ISSUE THREAD

**Issue by withinboredom** [Azure/azure-functions-durable-extension#1318]
**Is your feature request related to a problem? Please describe.**
I'd like a multi-region configuration, and thought I'd be clever using the `trackingStoreConnectionStringName` setting and pointing it at cosmosdb running in "storage table mode."

The appropriate tables were created, however, there seems to be an error.

**Describe the solution you'd like**
My solution was to use cosmos for globally reading state and each region having its own task hub, etc. I don't know what problems this would cause, but in my particular case, it's very unlikely entities and orchestrations would be processed in multiple regions at the same time (I do realize I'd be running into concurrency errors, more on that below). If any region were to go offline, work should continue for that region once it comes back online, but end users might only lose a few seconds of work.

Some suggestions to make this work:

1. Fix the error when using cosmosdb in table storage mode, it [looks like a package might just need to be updated](https://github.com/Azure/durabletask/issues/276):

```
[4/14/2020 5:57:10 PM]  ---> Microsoft.WindowsAzure.Storage.StorageException: Unexpected response code, Expected:OK or NotFound, Received:BadRequest
[4/14/2020 5:57:10 PM]    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
[4/14/2020 5:57:10 PM]    at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.FetchInstanceStatusInternalAsync(String instanceId, String executionId, Boolean fetchInput) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 514
[4/14/2020 5:57:10 PM]    at DurableTask.AzureStorage.AzureStorageOrchestrationService.CreateTaskOrchestrationAsync(TaskMessage creationMessage, OrchestrationStatus[] dedupeStatuses) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1288
[4/14/2020 5:57:10 PM]    at DurableTask.Core.TaskHubClient.InternalCreateOrchestrationInstanceWithRaisedEventAsync(String orchestrationName, String orchestrationVersion, String orchestrationInstanceId, Object orchestrationInput, IDictionary`2 orchestrationTags, OrchestrationStatus[] dedupeStatuses, String eventName, Object eventData) in C:\source\durabletask\src\DurableTask.Core\TaskHubClient.cs:line 503
[4/14/2020 5:57:10 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 144
...
[4/14/2020 6:03:58 PM] Request Information
[4/14/2020 6:03:58 PM] RequestID:f5e53132-9d26-4d90-b88d-d2355db35cee
[4/14/2020 6:03:58 PM] RequestDate:Tue, 14 Apr 2020 20:03:58 GMT
[4/14/2020 6:03:58 PM] StatusMessage:Bad Request
[4/14/2020 6:03:58 PM] ErrorCode:
[4/14/2020 6:03:58 PM] ErrorMessage:One of the input values is invalid.
[4/14/2020 6:03:58 PM] ActivityId: f5e53132-9d26-4d90-b88d-d2355db35cee, documentdb-dotnet-sdk/2.10.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
RequestID:f5e53132-9d26-4d90-b88d-d2355db35cee
```

2. There are a few different ways to handle concurrency (mostly in user-code-land), but locking could be handled using the TTL function of cosmosdb (though I'm not sure how that works) and an attribute on critical functions.

**Describe alternatives you've considered**
I've considered updating the library myself, but I'm not sure if that code would also be run in production. Also, I really wouldn't like maintaining a fork.

I've also considered writing an Azure function app that can act as a translation layer between what API durable functions expects and cosmos expects, but that might add considerable latency.

**Additional context**

**Comment by withinboredom** [comment]
@ConnorMcMahon,

I tried to figure out what changes were required. Some of them are plainly not ideal, however, it's far less code churn than I'd thought it would be.

# Durable Task Changes

I had to make some significant changes to the project files to be able to compile locally, please ignore those.

Reference changes: https://github.com/Azure/durabletask/compare/master...withinboredom:test/cosmos

Notes:
1. Had to abandon .NET Standard support (not ideal).
2. Cosmos does not allow a rowkey of `string.Empty` (a pretty significant change).
3. I made some poor variable name choices but I'm out of time for this investigation.
4. I didn't experience any issues running a large project locally with both Cosmos and the emulator as the tracking store.

# Azure Functions Durable Extension

The changes were so minuscule that it was terribly simple but note that I had to abandon .NET Standard support.

# Thoughts

Seeing that most of the changes are in the DurableTask framework, perhaps I should move the issue there?

**Comment by espray** [comment]
Wouldn't a preferred approach be creating a CosmosDB storage provider. Like what @cgillum is working on here, but using SQL Server https://github.com/cgillum/durabletask-sqlserver

**Comment by withinboredom** [comment]
@espray, All I did was update the storage library. CosmosDB is backwards compatible (with the exception of empty row keys, apparently) with Azure Storage. The current storage library is ages old, I'm not sure why.

**Comment by deepbass** [comment]
I'd love this ability 🙂 and the storage library being old + Cosmos not supporting empty row keys has burnt me in the past too

**Comment by ConnorMcMahon** [comment]
In the interest of tracking this in only one location, I am closing this issue. You can look for the status of us upgrading the Azure Storage SDK at https://github.com/Azure/durabletask/issues/516.
