### ISSUE TITLE
Synchronous durable entity operations invoked with lock throw LockingRulesViolationException

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#1371]
### Description
Synchronous durable entity operations invoked with lock throw a LockingRulesViolationException.

When invoking synchronous methods such as 

```csharp
public void Debit(DebitAccountMessage message)
{
    Balance -= Math.Abs(message.Amount);
}

public void Credit(CreditAccountMessage message)
{
    Balance += Math.Abs(message.Amount);
}
```

Within a lock such as

```csharp
[FunctionName(nameof(ExecuteTransfer))]
public async Task ExecuteTransfer([OrchestrationTrigger] IDurableOrchestrationContext context)
{
    var message = context.GetInput<TransferMessage>();

    var fromAccountEntity = new EntityId(nameof(AccountEntity), message.FromAccountId);
    var toAccountEntity = new EntityId(nameof(AccountEntity), message.ToAccountId);

    using (await context.LockAsync(fromAccountEntity, toAccountEntity))
    {
        var fromAccountProxy = context.CreateEntityProxy<IAccountEntity>(fromAccountEntity);
        var toAccountProxy = context.CreateEntityProxy<IAccountEntity>(toAccountEntity);

        fromAccountProxy.Debit(new DebitAccountMessage(message.Amount));
        toAccountProxy.Credit(new CreditAccountMessage(message.Amount));
    }
}
```

The following exception is returned:

~~~
[5/18/2020 1:29:39 PM] d3b997e7accf4f91b1fe4b43a0b2d5a5: Function 'ExecuteTransfer (Orchestrator)' failed with an error. Reason: System.AggregateException: One or more errors occurred. (While holding locks, cannot signal entities whose lock is held.)
[5/18/2020 1:29:39 PM]  ---> Microsoft.Azure.WebJobs.Extensions.DurableTask.LockingRulesViolationException: While holding locks, cannot signal entities whose lock is held.
[5/18/2020 1:29:39 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 562
[5/18/2020 1:29:39 PM]    --- End of inner exception stack trace ---
[5/18/2020 1:29:39 PM]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[5/18/2020 1:29:39 PM]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[5/18/2020 1:29:40 PM]    at System.Threading.Tasks.Task.Wait()
[5/18/2020 1:29:40 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationContext.SignalEntity(EntityId entity, String operationName, Object operationInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 404
[5/18/2020 1:29:40 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.OrchestrationContextProxy.Signal(EntityId entityId, String operationName, Object operationInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\OrchestrationContextProxy.cs:line 44
[5/18/2020 1:29:40 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.EntityProxy.Signal(String operationName, Object operationInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\EntityProxy.cs:line 58
[5/18/2020 1:29:40 PM]    at IAccountEntity_4f271e793a004a49b1ef0491bce6e45e.Debit(DebitAccountMessage )
[5/18/2020 1:29:40 PM]    at Sample.Functions.Transfers.TransfersHandler.ExecuteTransfer(IDurableOrchestrationContext context) in C:\code\_cz\azure-durable-entities-encryption\src\Sample.Functions\Transfers\TransfersHandler.cs:line 23
[5/18/2020 1:29:40 PM]    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 21
[5/18/2020 1:29:40 PM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[5/18/2020 1:29:40 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 96. IsReplay: False. State: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.2.1. SequenceNumber: 21.
[5/18/2020 1:29:40 PM] Executed 'ExecuteTransfer' (Failed, Id=bd6be399-a2bf-47c7-b1a2-336853778c3a)
[5/18/2020 1:29:40 PM] System.Private.CoreLib: Exception while executing function: ExecuteTransfer. System.Private.CoreLib: Orchestrator function 'ExecuteTransfer' failed: One or more errors occurred. (While holding locks, cannot signal entities whose lock is held.).
~~~

If the methods are changed to async as 

```csharp
public Task Debit(DebitAccountMessage message)
{
    Balance -= Math.Abs(message.Amount);
    return Task.CompletedTask;
}

public Task Credit(CreditAccountMessage message)
{
    Balance += Math.Abs(message.Amount);
    return Task.CompletedTask;
}
```

And awaiting within the lock

```csharp
using (await context.LockAsync(fromAccountEntity, toAccountEntity))
{
    var fromAccountProxy = context.CreateEntityProxy<IAccountEntity>(fromAccountEntity);
    var toAccountProxy = context.CreateEntityProxy<IAccountEntity>(toAccountEntity);

    await fromAccountProxy.Debit(new DebitAccountMessage(message.Amount));
    await toAccountProxy.Credit(new CreditAccountMessage(message.Amount));
}
```

Then no exception is thrown

### Expected behavior
To be able to perform synchronous durable entity operations invoked with lock without throwing a LockingRulesViolationException. 

Currently synchronous methods appear to be supported on durable entities (no build or runtime errors) if they exist on both the interface and concrete implementation. Therefore, I expected for them to work when invoking within the context of a lock within an orchestration.

If this error is expected, then it should be added to the [critical section rules documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp#critical-section-rules) and the [analyzer rules](https://github.com/Azure/azure-functions-durable-extension/tree/dev/test/WebJobs.Extensions.DurableTask.Analyzers.Test) should be updated to prevent executing synchronous method within a critical section.

### Workaround
Workaround is to make the methods async by returning Task. The body can return Task.CompletedTask to accomodate the return type despite there being no async operations.

Code sample that uses workaround can be found in [this repo](https://github.com/charleszipp/azure-durable-entities-encryption/blob/master/src/Sample.Functions/Transfers/TransfersHandler.cs).

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.1
- **Azure Functions runtime version (1.0 or 2.0)**: v3
- **Programming language used**: C#

<details>
<summary>Internal Tracking</summary>
CSEF 359547
</details>

**Comment by sebastianburckhardt** [comment]
I see, interesting! This is actually working as intended, though I understand why this may be a surprise, so we may need to improve the explanations.

The misunderstanding is that you call a "synchronous method" is really a "signal" in durable-entity-terminology, so it really is not quite what it looks like coming from regular C# coding style.

Signals are one-way fire-and-forget, which means they are inappropriate for use in a critical section: you don't want to exit the critical section until after the operations are completed, so you have to wait for a response (just the way you demonstrate with the async version of it).

I agree that it would be good to have the analyzer catch this.

The  critical section rules documentation does already state this:
- Critical sections can signal only entities they haven't locked.

Just this morning I was trying to remember why I put that rule there, now I remember. It's precisely to catch potential errors like this one.

**Comment by YunchuWang** [comment]
Closing for the same reason as #3536: the proposed analyzer fix targets only .NET in-process APIs, while our current focus is .NET isolated. Any future analyzer work for this rule should target TaskOrchestrationContext.Entities.LockEntitiesAsync and SignalEntityAsync in the isolated model.
