### ISSUE TITLE
Aborted orchestration executions due to host shutdowns occasionally log that the orchestration failed

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1477]
### Description
For some orchestrations aborted due to host shutdowns (see #1242), we incorrectly log that the orchestration failed. While the function execution failed, the orchestration does not fail, as the execution is aborted and will be retried when the host starts back up.

This makes it difficult to determine whether the orchestration actually failed when using App Insights as a source of truth.

### Expected behavior
1. The Function.<FunctionName> logger will mark a failed function execution.
2. The Host.Triggers.DurableTask logger will mark an aborted execution for this orchestration instance.

### Actual behavior
1. The Function.<FunctionName> logger will mark a failed function execution.
2. Occasionally, the Host.Triggers.DurableTask will log an Orchestration Failure.
3. The Host.Triggers.DurableTask logger will mark an aborted execution for this orchestration instance.

### Stack trace for error log looks something like this:
```
<instance-id>: Function '<Orchestrator-FunctionName> (Orchestrator)' failed with an error. Reason: DryIoc.ContainerException: Container is disposed and should not be used: Container is disposed.
You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace())
   at DryIoc.Throw.It(Int32 error, Object arg0, Object arg1, Object arg2, Object arg3) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 8990
   at DryIoc.Container.ThrowIfContainerDisposed() in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 411
   at DryIoc.Container.WithCurrentScope(IScope scope, Boolean preferInterpretaion) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 436
   at DryIoc.ResolverContext.OpenScope(IResolverContext r, Object name, Boolean trackInParent, Boolean preferInterpretation) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 2699
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.WebHostServiceProvider.CreateScope() in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\WebHostServiceProvider.cs:line 51
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver.CreateChildScope(IServiceScopeFactory rootScopeFactory) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedResolver.cs:line 42
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.CreateScope() in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\JobHostServiceProvider.cs:line 104
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInstanceWrapper.get_InstanceServices() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInstanceWrapper.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionInstanceFactory`1.InvokeWrapper.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionInstanceFactory.cs:line 80
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 846
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 123
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. HubName: <hubname>. AppName: <appname>. SlotName: Production. ExtensionVersion: 2.2.2. SequenceNumber: 7648.
```

### Known workarounds
1. Directly query the orchestration instance to see if it is actually marked as failed if you get one of these errors.
2. Look to see if you have a corresponding warning log saying that the execution was aborted due to the Container disposed exception. If so, the orchestration instance likely is still running fine.
3. Ignore all errors logged that have this exception type.

**Comment by cgillum** [comment]
I don't recall seeing this issue in recent days, so I'm not sure if it's still an active problem that needs to be tracked. Closing this out for now.
