### ISSUE TITLE
Blob storage returns 403 when lease kicks in and blob is private

### ISSUE THREAD

**Issue by erwelch** [Azure/azure-functions-durable-extension#1479]
When the Azure Function scales out we are starting to see 403s on the blob storage for the durable function. We have the Azure Function VNET integrated and the Durable Storage Account is using a private endpoint for Queue, Table, and Blob. Before scaling out it works fine, and if making the durable storage account public then it also works fine. 

The method throwing the error is: `DurableTask.AzureStorage.Partitioning.AppLeaseManager+<CreateContainerIfNotExistsAsync>d__17.MoveNext`

Relevant call stack:
```
[WrapServiceBusTrigger] Exception caught in Function: Microsoft.WindowsAzure.Storage.StorageException: This request is not authorized to perform this operation.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.CreateIfNotExistsAsync(BlobContainerPublicAccessType accessType, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
   at DurableTask.AzureStorage.Partitioning.AppLeaseManager.CreateContainerIfNotExistsAsync() in C:\source\durabletask\src\DurableTask.AzureStorage\Partitioning\AppLeaseManager.cs:line 78
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.GetTaskHubCreatorTask() in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 344
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.EnsureTaskHubAsync() in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 325
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.SendTaskOrchestrationMessageAsync(TaskMessage message) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1388
   at DurableTask.Core.TaskHubClient.RaiseEventAsync(OrchestrationInstance orchestrationInstance, String eventName, Object eventData) in C:\source\durabletask\src\DurableTask.Core\TaskHubClient.cs:line 656
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.SignalEntityAsyncInternal(DurableClient durableClient, String hubName, EntityId entityId, Nullable`1 scheduledTimeUtc, String operationName, Object operationInput) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 305
```

**Comment by ConnorMcMahon** [comment]
@amdeel, since the code path failing is in the app lease manager, though I don't necessarily know if this is an issue with that code path as much as a connectivity problem to Azure Storage.

@erwelch, could you attempt to directly communicate with the storage account endpoint before making the call to `IDurableClient.SignalEntityAsync()`, i.e. with an HTTPClient making a request to `<accountname>.core.windows.net`. In general, I highly suspect this is a problem with scale out breaking your VNET connectivity to storage rather than any issues with Durable Functions code itself.

If that is the case, I would highly recommend opening a support ticket, as it will be very difficult for us to help you via GitHub.

**Comment by blueelvis** [comment]
@erwelch Did you find anything into this? We seem to be running into this exact scenario.
