### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException causing failed operation?

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#1495]
I'm seeing a strange operation exception I would like to try and get some clarification on.

I was looking at the exception logs and see the following error message:

```
TaskOrchestrationDispatcher-917a4adf7b0347b9a1b2fe1130ee6333-0: Unhandled exception with work item '@purchaseaggregator@site-id@14@sale-line-id@531124258719528@block-dtm@20200924T102610000': Microsoft.WindowsAzure.Storage.StorageException: Element 3 in the batch returned an unexpected response code.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String clientRequestId, String account, AzureStorageOrchestrationServiceSettings settings, Func`1 operation)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UploadHistoryBatch(String instanceId, String executionId, TableBatchOperation historyEventBatch, StringBuilder historyEventNamesBuffer, Int32 numberOfTotalEvents, Int32 episodeNumber, Int32 estimatedBatchSizeInBytes, String eTagValue, Boolean isFinalBatch) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1244
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1053
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 965
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 451
   at DurableTask.Core.TaskOrchestrationDispatcher.OnProcessWorkItemSessionAsync(TaskOrchestrationWorkItem workItem) in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationDispatcher.cs:line 123
   at DurableTask.Core.WorkItemDispatcher`1.ProcessWorkItemAsync(WorkItemDispatcherContext context, Object workItemObj) in C:\source\durabletask\src\DurableTask.Core\WorkItemDispatcher.cs:line 373
Request Information
RequestID:1c08551f-3002-003e-437e-92dc78000000
RequestDate:Thu, 24 Sep 2020 14:26:13 GMT
StatusMessage:3:The specified entity already exists.
ErrorCode:
ErrorMessage:3:The specified entity already exists.
RequestId:1c08551f-3002-003e-437e-92dc78000000
Time:2020-09-24T14:26:14.2421525Z


Backing off for 10 seconds until 5 successful operations
```

Then under the failed operations I see a null reference exception which points back to a line of code that simply writes a log statement.

I'm wondering if this is the same issue I see pop up when the runtime cannot provide a logger instance and throws a container exception. Or potentially a scale out issue with lease stealing.

@ConnorMcMahon are you able to look at the logs and see if there is something else going on? Our alerting strategy revolves around failed operations and would like to rule out other possibilities?

app name: auction-etr-int-purchases-east-prod
task hub name: PurchaseTaskHub
entity id: @purchaseaggregator@site-id@14@sale-line-id@531124258719528@block-dtm@20200924T102610000
region: us east
event time: 2020-09-24T14:26:13.7510831Z

Let me know if you need anything else!

**Comment by ConnorMcMahon** [comment]
Looking into it now.

**Comment by mpaul31** [comment]
@ConnorMcMahon thanks for looking into this! i actually switched to the new partition management not too long ago so i'll go cross reference that date i saw this issue to when i released the change.
