### ISSUE TITLE
Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.OrchestratorAnalyzer' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation Parameter name: syntaxTree'.

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-functions-durable-extension#1558]
Just upgraded to VS 16.8, and I receive the following analyzer warning.
I don't think it was there before upgrading to 16.8 - but I'm not 100% sure.

Using `Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers @ 0.3.2`

```
Warning	AD0001	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.OrchestratorAnalyzer' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation
Parameter name: syntaxTree'.
Exception occurred with following context:
Compilation: DW.Workspaces.WebJobs

System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.SyntaxNodeUtils.TryGetSemanticModelForSyntaxTree(SemanticModel model, SyntaxNode node, SemanticModel& newModel)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.SyntaxNodeUtils.TryGetITypeSymbol(SemanticModel semanticModel, SyntaxNode node, ITypeSymbol& typeSymbol)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.IOTypesAnalyzer.RegisterDiagnostic(SyntaxNode method, CompilationAnalysisContext context, SemanticModel semanticModel)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.MethodAnalyzer.RegisterAnalyzers(List`1 methodInformationList, CompilationAnalysisContext context, SemanticModel semanticModel)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.OrchestratorAnalyzer.RegisterAnalyzers(CompilationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationActionsCore>b__48_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: DF0101, DF0102, DF0103, DF0104, DF0105, DF0106, DF0107	DW.Workspaces.WebJobs		1	Active
```

**Comment by amdeel** [comment]
Hey @NickSevens, thanks for submitting this. I'm going to try to fix this for our next analyzer release. Are you still seeing this warning in your code? And is it possible that I could have your project/a repro of this so I can make sure that I fix it?

**Comment by NickSevens** [comment]
Hi @amdeel I don't have the issue anymore, and can't reproduce it either. My VS has been updated in the meantime to 16.8.2 - don't know if that has anything to do with it :/

**Comment by amdeel** [comment]
Hey @NickSevens. Thanks for getting back to me. Since we can't repro this I'm hoping this could be a visual studio issue or a warning leftover from a previous analyzer version. I'm going to close this issue for now. Please reopen this if you see this warning again.
