### ISSUE TITLE
Durable function timeout exception bug

### ISSUE THREAD

**Issue by ComeChao** [Azure/azure-functions-durable-extension#1599]
I have an Azure Durable Function whose host.json file sets all functions to **never timeout**: 
**{ "version": "2.0", "functionTimeout": "-1" } }**

When the durable function is run though the activity function called by the orchestrator function gets a timeout after the default 30 minutes:

**Timeout value of 00:30:00 was exceeded by function: LongRunningActivity**

Microsoft.Azure.WebJobs.Host.FunctionTimeoutException: at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+d__29.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35Microsoft.Azure.WebJobs.Host, Version=3.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.csMicrosoft.Azure.WebJobs.Host, Version=3.0.23.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35: 624) at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)

The documentation states that the timeout defined in host.json should apply to all functions in the function app yet the activity function fails the rule. 

Is there a fix or a workaround other than setting the timeout to something like "12:00:00" (12 hours)?

**Comment by cgillum** [comment]
The timeout is enforced by the functions host. Durable Functions has no influence over this.

Does this setting work correctly for other function types? Also, if you set it to a value other than 30 minutes (for example, something shorter like 10 seconds), is that timeout value being honored?

**Comment by ComeChao** [comment]
We have a regular function that has a host.json file:
{
  "version": "2.0",
  **"functionTimeout": "01:00:00"**
}
and the **function times out at 01:00:01 as expected.**

**Comment by cgillum** [comment]
* Does `"-1"` work for the regular function?
* Does any timeout other than `"-1"` or `"00:30:00"` work for your activity function?

**Comment by ComeChao** [comment]
I don't think so. I had tried the "01:00:00" before, if I am not mistaken, but it failed. since I got the default 30s timeouts. I thought I had fixed the issue using "-1".

**Comment by ConnorMcMahon** [comment]
It looks like the code for unlimited timeouts is described below:

```csharp
else if (!_environment.IsWindowsConsumption() && TimeSpan.Compare(options.FunctionTimeout.Value, TimeSpan.FromDays(-1)) == 0)
{
    // If a value of -1 is specified on a dedicated host, it should result in an infinite timeout
    options.FunctionTimeout = null;
}
```

Unfortunately, I can't find the code that resolves the JSON in the host.json into `options.FunctionTimeout`, which is of type `TimeSpan?`, but I would try using `-1` instead of `"-1"`. If that fails, I would try `"-01:00:00"`.

**Comment by ComeChao** [comment]
I checked the json schema and it expects a string. (https://github.com/Azure/Azure-Functions/blob/main/schemas/host.json)
    "functionTimeout": {
      "description": "Value indicating the timeout duration for all functions.",
      "oneOf": [
        {
          "type": "string",
          "pattern": "^(**-1**|(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d)$"
        },
        { "enum": [ null ] }
      ]
    },

**Comment by ConnorMcMahon** [comment]
Hmm. That schema could be wrong. I would try my suggestions, and we should update our docs and schema accordingly if either of those work.

If neither of those work, let's transfer this to the Functions host repo where someone from that team can help resolve this issue, since this is a broader Azure Functions issue.

**Comment by ComeChao** [comment]
ok, I would do this and get back with an answer. Meanwhile would it be possible for you reach out to your colleagues in the Functions team and maybe get a solution?
Thank you so much!

**Comment by ComeChao** [comment]
I tried:

{
  "version": "2.0",
  "functionTimeout": -1
}
and 
{
  "version": "2.0",
  "functionTimeout": "-01:00:00"
}

and got the Timeout Exception in both cases. 

2020-12-09T20:27:05.997 [Error] Timeout value of 00:30:00 exceeded by function 'LongRunningActivity' (Id: ''). Initiating cancellation.

The stack trace is this:

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryHandleTimeoutAsync(Task invokeTask, CancellationToken shutdownToken, Boolean throwOnTimeout, CancellationToken timeoutToken, TimeSpan timeoutInterval, IFunctionInstance instance, Action onTimeout) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 624
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 535
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.**ExecuteWithWatchersAsync**(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 492
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 438
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 245
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 295
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstanceEx, CancellationToken cancellationToken, ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 97. IsReplay: False. State: Failed. HubName: x. AppName: x. SlotName: Production. ExtensionVersion: 2.2.2. SequenceNumber: 13.

I found the source code here: https://raw.githubusercontent.com/Azure/azure-webjobs-sdk/master/src/Microsoft.Azure.WebJobs.Host/Executors/FunctionExecutor.cs

The issue seems to be around **ExecuteWithWatchersAsync** which calls **StartFunctionTimeout**. StartFunctionTimeout sets a timer that handles the timeout with OnFunctionTimeout. Somehow a TimeoutAttribute is passed as a parameter and its TimeSpan is set to 30s. It looks like this is an Azure Functions bug but this obviously requires more research.

**Comment by ComeChao** [comment]
I am transferring this to Azure Functions: https://github.com/Azure/azure-webjobs-sdk/issues
Thanks.

**Comment by ComeChao** [comment]
FYI: In case you are annoyed by this same issue again:

Also run the Durable Function with **""functionTimeout": "02:00:00"** and also got the timeout exception. 'GenerateExtract_Worker' is an activity function called by an orchestrator function:

2020-12-11T16:58:51 Welcome, you are now connected to log-streaming service. **The default timeout is 2 hours.** Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2020-12-11T16:59:51 No new trace in the past 1 min(s).
2020-12-11T17:00:51 No new trace in the past 2 min(s).
2020-12-11T17:01:51 No new trace in the past 3 min(s).
2020-12-11T17:02:51 No new trace in the past 4 min(s).
2020-12-11T17:03:51 No new trace in the past 5 min(s).
2020-12-11T17:04:51 No new trace in the past 6 min(s).
2020-12-11T17:05:51 No new trace in the past 7 min(s).
2020-12-11T17:06:51 No new trace in the past 8 min(s).
2020-12-11T17:07:51 No new trace in the past 9 min(s).
2020-12-11T17:08:51 No new trace in the past 10 min(s).
2020-12-11T17:09:51 No new trace in the past 11 min(s).
2020-12-11T17:10:42.993 **[Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker'** (Id: 'db914cf6-3078-4bd4-a3af-bdc5b7112843'). Initiating cancellation.
2020-12-11T17:10:43.044 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=db914cf6-3078-4bd4-a3af-bdc5b7112843, Duration=1800136ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker
2020-12-11T17:10:43.126 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: 'b1bd37d7-612b-4496-b970-02ae20cd3722'). Initiating cancellation.
2020-12-11T17:10:43.131 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '194dc5dc-f89e-46fd-ba95-a286c1e6d748'). Initiating cancellation.
2020-12-11T17:10:43.131 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '194dc5dc-f89e-46fd-ba95-a286c1e6d748'). Initiating cancellation.
2020-12-11T17:10:43.133 [Error] Timeout value of 00:30:00 exceeded by function 'GenerateExtract_Worker' (Id: '6c7c561a-95c7-45c3-bcdd-d877a5a792cd'). Initiating cancellation.
2020-12-11T17:10:43.326 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=194dc5dc-f89e-46fd-ba95-a286c1e6d748, Duration=1800320ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker
2020-12-11T17:10:43.343 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=6c7c561a-95c7-45c3-bcdd-d877a5a792cd, Duration=1800354ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker
2020-12-11T17:10:43.376 [Error] Executed 'GenerateExtract_Worker' (Failed, Id=b1bd37d7-612b-4496-b970-02ae20cd3722, Duration=1800334ms)Timeout value of 00:30:00 was exceeded by function: GenerateExtract_Worker

**This means there is no known workaround at this moment.**

**Comment by ConnorMcMahon** [comment]
@ComeChao,

Do you have a custom Startup.cs file to set up dependency injection? We have seen some customers put code in their startup that overrides the configuration set by host.json.

**Comment by ComeChao** [comment]
Yes, we do have dependency injection set up in our FunctionStartup.cs file. 
Do you have any guidance on how to have dependency injection set up without overriding host.json contents?

**Comment by ConnorMcMahon** [comment]
This was a common problem for customers, so Azure Functions recently added [better support for this scenario](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources).

**Comment by ComeChao** [comment]
@ConnorMcMahon

I will try to fix this issue on my side then. Thank you!

**Comment by ConnorMcMahon** [comment]
@ComeChao, were you able to resolve your issue?

**Comment by avillaca** [comment]
I was able to fix this issue by adding the Timeout attribute - [Timeout("-1")] - to each one of the durable function workers.

Adding a file to override host,json, as suggested above, did not work. Maybe I missed something? The json file contents is this:
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    **"AzureFunctionsJobHost__functionTimeout": "-1"**
  }
}

**Comment by guru-stack** [comment]
@avillaca when you say you added Timeout attribute to durable function workers, where exactly you added this?

**Comment by ComeChao** [comment]
I added a Timeout attribute in top of each function with an ActivityTrigger and that is called with context.CallActivityAsync. 
Hope this helps.

        [FunctionName("Function1_Hello")]
        //[Timeout("-1")]
        [Timeout("00:59:00")]
        public static string SayHello([ActivityTrigger] string name, ILogger log)

**Comment by guru-stack** [comment]
Thank you. Actually i updated host.json to -1 and it seems working (Actually the function completed in exactly 30 min 15 sec. Just to double check, am running one more time with double the payload side to be sure it will cross 30 min. Below is my host.json.
{
  "version": "2.0",
  "functionTimeout": -1
}
