### ISSUE TITLE
Host startup fails under certain conditions if both Durable Task and Storage extensions are referenced.

### ISSUE THREAD

**Issue by DL444** [Azure/azure-functions-durable-extension#1688]
### Description
Host startup will fail when **all** of the conditions below are met:
- Function app is deployed to a Linux Consumption plan (Premium and App Service plans untested).
- App project references both `Microsoft.Azure.WebJobs.Extensions.DurableTask` and `Microsoft.Azure.WebJobs.Extensions.Storage` packages.
- Output cleaning is disabled by setting `_FunctionsSkipCleanOutput` to `true` in csproj file.

### Expected behavior
The function app should startup and run normally.

### Actual behavior
Function startup will fail. Error message:
> Microsoft.Extensions.Hosting.Abstractions: Value cannot be null. (Parameter 'hostingEnvironment').

### Relevant source code snippets
csproj file:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RootNamespace>linux_test</RootNamespace>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>    
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
See [here](https://github.com/DL444/azure-func-linux-diag) for a minimum reproduce project I created.

### Known workarounds
1. Switch to a Windows plan.
2. Enable output cleaning. Due to the aggressive cleaning behavior, this might not be viable in some scenarios.

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.1
- **Azure Functions runtime version (1.0 or 2.0)**: v3
- **Programming language used**: C#
- **Storage extension version**: 4.0.4

### Screenshots
N/A

### If deployed to Azure
- **Timeframe issue observed**: Since at least 2021-01-27.
- **Function App name**: `ucqu-linux-test`
- **Function name(s)**: N/A as durable functions are not required to present to trigger the issue.
- **Azure region**: East Asia
- **Orchestration instance ID(s)**: N/A as host cannot start.
- **Azure storage account name**: `ucqulinuxtest`

**Comment by DL444** [comment]
Since this seems to be a dependency problem, I'm not sure if this is the right place for this issue. Sorry if it's not.

**Comment by cgillum** [comment]
FYI @brettsam or @fabiocav does this error message ring a bell? I'm not really sure what `<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>` is for but I feel like I've seen other similar cases recently related to assembly version conflicts.

**Comment by brettsam** [comment]
This is an issue on Linux right now -- we're working on rolling out the hotfix. The other workaround is to pin back to version 3.0.15815 (I'll write back with exact steps for this... gotta find them).

PR that fixed it is here: https://github.com/Azure/azure-functions-host/pull/7113

**Comment by brettsam** [comment]
In order to pin, see docs here -- https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version?tabs=portal%2Cazurecli-linux#manual-version-updates-on-linux 

`LinuxFXVersion` should be set to: `DOCKER|mcr.microsoft.com/azure-functions/dotnet:3.0.15185-appservice`

Note that there is currently a bug in the `az` CLI (https://github.com/Azure/azure-cli/issues/16126) which means that after you update the `LinuxFXVersion`, you need to follow-up with another command to update the `WEBSITES_ENABLE_APP_SERVICE_STORAGE` app setting to `true`

**Comment by DL444** [comment]
@brettsam 

For some reason after I set the version, the runtime becomes unreachable. Any HTTP requests to functions will return "The service is unavailable."

I may have made a mistake, so here is the commands I used:
```bash
az functionapp config set --name ucqu-linux-test --resource-group ucqu-linux-test --linux-fx-version "DOCKER|mcr.microsoft.com/azure-functions/dotnet:3.0.15185-appservice"
az functionapp config appsettings set --name ucqu-linux-test --resource-group ucqu-linux-test --settings "WEBSITES_ENABLE_APP_SERVICE_STORAGE=true"
```

I also tried tags `3.0.15185`, `3.0.15185-appservice-quickstart`, `3.0.15185-dotnet3-appservice`, and `3.0.15185-slim`. The results are the same.

**Comment by brettsam** [comment]
I'm sorry-- I led you down the wrong path. I just saw you are on Linux Consumption, not Dedicated. In that case:
```
az functionapp config set --name ucqu-linux-test --resource-group ucqu-linux-test --linux-fx-version "DOCKER|DOCKER|mcr.microsoft.com/azure-functions/mesh:3.0.15185"
```
@pragnagopa / @divyagandhisethi -- does that `az cli` bug with `WEBSITES_ENABLE_APP_SERVICE_STORAGE` apply to consumption also?

**Comment by pragnagopa** [comment]
@divyagandhisethi - Please confirm if https://github.com/Azure/azure-cli/issues/16126 would effect linux consumption

**Comment by DL444** [comment]
@brettsam 
After setting linuxFxVersion to `DOCKER|DOCKER|mcr.microsoft.com/azure-functions/mesh:3.0.15185` or `DOCKER|mcr.microsoft.com/azure-functions/mesh:3.0.15185` I still got the same service unavailable error.

This is weird since I can't really find a better tag from the tag list. But reverting back to `DOTNET|3.1` restores host availability (still with the "hostingEnvironment null" problem though).

@pragnagopa 
I can confirm that Azure/azure-cli#16126 does affect apps hosted in Linux Consumption plans.

**Comment by divyagandhisethi** [comment]
@brettsam The CLI bug does not affect Linux Consumption.

**Comment by TsuyoshiUshio** [comment]
FYI, I can reproduce the issue in my environment. I'll share the full stack trace. 

```
2021-02-18T06:48:07.896185203Z: [INFO] System.ArgumentNullException: Value cannot be null. (Parameter 'hostingEnvironment')
2021-02-18T06:48:07.897268128Z: [INFO] at Microsoft.Extensions.Hosting.HostingEnvironmentExtensions.IsDevelopment(IHostingEnvironment hostingEnvironment)
2021-02-18T06:48:07.897292229Z: [INFO] at Microsoft.Extensions.Hosting.StorageWebJobsBuilderExtensions.<>c.<AddAzureStorage>b__0_5(QueuesOptions options, IHostingEnvironment env) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\StorageWebJobsBuilderExtensions.cs:line 75
2021-02-18T06:48:07.897298329Z: [INFO] at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
2021-02-18T06:48:07.897302029Z: [INFO] at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2021-02-18T06:48:07.897305629Z: [INFO] at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2021-02-18T06:48:07.897318829Z: [INFO] at System.Lazy`1.CreateValue()
2021-02-18T06:48:07.899700886Z: [INFO] at Microsoft.Azure.WebJobs.Host.Queues.Triggers.QueueTriggerAttributeBindingProvider..ctor(INameResolver nameResolver, StorageAccountProvider accountProvider, IOptions`1 queueOptions, IWebJobsExceptionHandler exceptionHandler, SharedQueueWatcher messageEnqueuedWatcherSetter, ILoggerFactory loggerFactory, IQueueProcessorFactory queueProcessorFactory) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Triggers\QueueTriggerAttributeBindingProvider.cs:line 42
2021-02-18T06:48:07.899716586Z: [INFO] at lambda_method(Closure , IResolverContext )
2021-02-18T06:48:07.899720986Z: [INFO] at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6605
2021-02-18T06:48:07.899725086Z: [INFO] at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7849
2021-02-18T06:48:07.899738486Z: [INFO] at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7834
2021-02-18T06:48:07.899742387Z: [INFO] at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6604
2021-02-18T06:48:07.899745787Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6564
2021-02-18T06:48:07.899749087Z: [INFO] at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7083
2021-02-18T06:48:07.899752387Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6554
2021-02-18T06:48:07.899755787Z: [INFO] at DryIoc.WrappersSupport.GetArrayExpression(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 2903
2021-02-18T06:48:07.899759087Z: [INFO] at DryIoc.ExpressionFactory.CreateExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7699
2021-02-18T06:48:07.902145343Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6554
2021-02-18T06:48:07.902160844Z: [INFO] at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7083
2021-02-18T06:48:07.902165344Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6554
2021-02-18T06:48:07.902168744Z: [INFO] at DryIoc.Factory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6634
2021-02-18T06:48:07.902172144Z: [INFO] at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 211
2021-02-18T06:48:07.902175444Z: [INFO] at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 196
2021-02-18T06:48:07.902178944Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 99
2021-02-18T06:48:07.902182444Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetRequiredService(Type serviceType) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 82
2021-02-18T06:48:07.902185844Z: [INFO] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2021-02-18T06:48:07.903063865Z: [INFO] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2021-02-18T06:48:07.903077665Z: [INFO] at Microsoft.Azure.WebJobs.WebJobsServiceCollectionExtensions.<>c.<AddWebJobs>b__1_0(IServiceProvider p) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsServiceCollectionExtensions.cs:line 57
2021-02-18T06:48:07.903082765Z: [INFO] at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/DryIocAdapter.cs:line 156
2021-02-18T06:48:07.903086665Z: [INFO] at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 4550
2021-02-18T06:48:07.903090266Z: [INFO] at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6605
2021-02-18T06:48:07.903093966Z: [INFO] at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7849
2021-02-18T06:48:07.903097366Z: [INFO] at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7834
2021-02-18T06:48:07.903100766Z: [INFO] at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6604
2021-02-18T06:48:07.903104166Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6564
2021-02-18T06:48:07.903107366Z: [INFO] at DryIoc.Factory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6634
2021-02-18T06:48:07.903110666Z: [INFO] at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7746
2021-02-18T06:48:07.903114766Z: [INFO] at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 291
2021-02-18T06:48:07.903118266Z: [INFO] at lambda_method(Closure , IResolverContext )
2021-02-18T06:48:07.903121466Z: [INFO] at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6605
2021-02-18T06:48:07.904074789Z: [INFO] at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7849
2021-02-18T06:48:07.904088589Z: [INFO] at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7834
2021-02-18T06:48:07.904097389Z: [INFO] at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6604
2021-02-18T06:48:07.904101089Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6564
2021-02-18T06:48:07.904104389Z: [INFO] at DryIoc.Factory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6634
2021-02-18T06:48:07.904107790Z: [INFO] at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 211
2021-02-18T06:48:07.904111290Z: [INFO] at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 196
2021-02-18T06:48:07.904114590Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 99
2021-02-18T06:48:07.904941309Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetRequiredService(Type serviceType) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 82
2021-02-18T06:48:07.904953009Z: [INFO] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2021-02-18T06:48:07.904957010Z: [INFO] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
2021-02-18T06:48:07.904960410Z: [INFO] at Microsoft.Azure.WebJobs.WebJobsServiceCollectionExtensions.<>c.<AddWebJobs>b__1_4(IServiceProvider p) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Hosting\WebJobsServiceCollectionExtensions.cs:line 92
2021-02-18T06:48:07.904964710Z: [INFO] at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/DryIocAdapter.cs:line 156
2021-02-18T06:48:07.904968610Z: [INFO] at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 4550
2021-02-18T06:48:07.904972210Z: [INFO] at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6605
2021-02-18T06:48:07.904975710Z: [INFO] at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7849
2021-02-18T06:48:07.904979110Z: [INFO] at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7834
2021-02-18T06:48:07.904987810Z: [INFO] at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6604
2021-02-18T06:48:07.904992010Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6564
2021-02-18T06:48:07.904995510Z: [INFO] at DryIoc.Factory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6634
2021-02-18T06:48:07.904998811Z: [INFO] at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7746
2021-02-18T06:48:07.905009711Z: [INFO] at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, Object serviceKey, IfUnresolved ifUnresolved, Type requiredServiceType, Request preResolveParent, Object[] args) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 291
2021-02-18T06:48:07.905013811Z: [INFO] at lambda_method(Closure , IResolverContext )
2021-02-18T06:48:07.905017011Z: [INFO] at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6605
2021-02-18T06:48:07.905020611Z: [INFO] at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7849
2021-02-18T06:48:07.905024111Z: [INFO] at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7834
2021-02-18T06:48:07.905027411Z: [INFO] at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6604
2021-02-18T06:48:07.905030811Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6564
2021-02-18T06:48:07.905034011Z: [INFO] at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7083
2021-02-18T06:48:07.905037411Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6554
2021-02-18T06:48:07.905041212Z: [INFO] at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 7083
2021-02-18T06:48:07.905044512Z: [INFO] at DryIoc.Factory.GetExpressionOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6554
2021-02-18T06:48:07.905047812Z: [INFO] at DryIoc.Factory.GetDelegateOrDefault(Request request) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 6634
2021-02-18T06:48:07.905054612Z: [INFO] at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 211
2021-02-18T06:48:07.905058212Z: [INFO] at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/DryIoc/Container.cs:line 196
2021-02-18T06:48:07.905061512Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType, IfUnresolved ifUnresolved) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 99
2021-02-18T06:48:07.905065012Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.JobHostServiceProvider.GetService(Type serviceType) in /src/azure-functions-host/src/WebJobs.Script.WebHost/DependencyInjection/JobHostServiceProvider.cs:line 77
2021-02-18T06:48:07.905068412Z: [INFO] at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
2021-02-18T06:48:07.905071612Z: [INFO] at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in /src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobsScriptHostService.cs:line 247
```

**Comment by TsuyoshiUshio** [comment]
I removed durable, however still have it. looks `Microsoft.Azure.WebJobs.Extensions.Storage` ? 

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RootNamespace>linux_test</RootNamespace>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.16.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>    
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by DL444** [comment]
@TsuyoshiUshio 
In my case referencing `Microsoft.Azure.WebJobs.Extensions.Storage` alone will not trigger the bug. I used different version though.

```xml
<ItemGroup>
  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
  <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
</ItemGroup>
```

**Comment by ConnorMcMahon** [comment]
Do we have a status update with this @TsuyoshiUshio or @brettsam?

**Comment by ConnorMcMahon** [comment]
This issue has not received traffic in several months, so we are assuming this is fixed.

**Comment by DL444** [comment]
I can confirm this no longer affects me by now.
