### ISSUE TITLE
Durable entity class - AmbiguousMatchException

### ISSUE THREAD

**Issue by joeyeng** [Azure/azure-functions-durable-extension#1696]
### Description
> When I do a method overload in my Durable entity class I get a "System.Reflection.AmbiguousMatchException: Ambiguous match found" exception. In my particular case the method overload was a private method (not part of the interface). When I renamed the method the issue was fixed.

### Expected behavior
> Either allow method overloads or cause a compiler error.

### Actual behavior
> Runtime exception

Stack trace:

@bulkcalculationstate@f2b52896-d253-4871-92f0-bec867712d77: Function 'bulkcalculationstate (Entity)' failed 'AddFees' operation 08d8f9af-e35a-4eea-baed-4abbc8398ca2 after 0.9082ms with exception System.Reflection.AmbiguousMatchException: Ambiguous match found.
   at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TypedInvocationExtensions.FindMethodForContext[T](IDurableEntityContext context) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\TypedInvocationExtensions.cs:line 102
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TypedInvocationExtensions.DispatchAsync[T](IDurableEntityContext context, Object[] constructorParameters) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\TypedInvocationExtensions.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskEntityShim.ProcessOperationRequestAsync(RequestMessage request) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskEntityShim.cs:line 319. Input: (1060 bytes). IsReplay: False.

### App Details

- Microsoft.NET.Sdk.Functions v3.0.5
- **Durable Functions extension v2.3.0**
- **Azure Functions runtime version v3**
- **C#**

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Orchestration instance ID(s)**: 58bb38ff961e41898a835506ca44785f
- Entity name: @bulkcalculationstate@f2b52896-d253-4871-92f0-bec867712d77

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by ConnorMcMahon** [comment]
Related to #1584.

@sebastianburckhardt, I'm curious if we can make improvements to just throwing ambiguous match exception. For instance, can we identify by looking at the event sent whether to invoke the interface overload that has 0 or 1 parameters?

**Comment by YunchuWang** [comment]
Closing as not planned for the .NET in-process model. The original dispatcher includes non-public methods in its reflection lookup, so a private helper overload can cause AmbiguousMatchException even when it is not part of the entity interface.

The reported private-helper overload pattern does not reproduce in current .NET isolated. I ran a local Functions host with .NET 8, Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.19.0, and Azurite. Both TaskEntity<int> and plain-class entities successfully dispatched a public AddFees(int) operation with a private AddFees() helper.

Two public overloads still throw AmbiguousMatchException, with or without operation input. That is expected: isolated dispatch considers only public instance methods and resolves operations by name before binding arguments. Use distinct public operation names; private helper overloads are fine.

Isolated dispatch implementation: https://github.com/microsoft/durabletask-dotnet/blob/1b25b5e0f0cc6ef75293142c016d070b33350c1a/src/Abstractions/Entities/TaskEntityOperationExtensions.cs#L17-L44
