### ISSUE TITLE
IDurableOrchestrationContext.GetInput method is using Newtonsoft rather than System.Text.Json

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-durable-extension#1698]
### Description
I'm moving from `Newtonsoft` to `System.Text.Json` to handle serialization/deserialization, however, I found that internally durable functions are using `Newtonsoft` to do so, I realized about that because it is not taking into account a custom converter I had to create to deal with `JsonDocument`, so the deserialization is throwing an error because obviously, the JSON converter I'm using is an implementation of `System.Text.Json` converter.

### Expected behavior
I'd expect that internally Durable functions are dealing with serialization/deserialization stuff using System.Text.Json since that's the Microsoft recommendation due to performance and security enhancements.

### Actual behavior
I'm getting a deserialization exception when trying to get the orchestrator input through the `GetInput` method:
```
Function 'OrderSaga (Orchestrator)' failed with an error. Reason: Newtonsoft.Json.JsonSerializationException: Unable to find a constructor to use for type System.Text.Json.JsonDocument. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'SourceIdentities.Order.RootElement', line 1, position 44.
[2021-02-25T20:09:28.111Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
[2021-02-25T20:09:28.113Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-02-25T20:09:28.114Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-02-25T20:09:28.115Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
[2021-02-25T20:09:28.116Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
[2021-02-25T20:09:28.117Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-02-25T20:09:28.118Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-02-25T20:09:28.131Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
[2021-02-25T20:09:28.146Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
[2021-02-25T20:09:28.148Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-02-25T20:09:28.159Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
[2021-02-25T20:09:28.166Z]    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
[2021-02-25T20:09:28.168Z]    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
[2021-02-25T20:09:28.169Z]    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
[2021-02-25T20:09:28.181Z]    at DurableTask.Core.Serializing.JsonDataConverter.Deserialize(String data, Type objectType) in C:\source\durabletask\src\DurableTask.Core\Serializing\JsonDataConverter.cs:line 104
[2021-02-25T20:09:28.188Z]    at DurableTask.Core.Serializing.DataConverter.Deserialize[T](String data) in C:\source\durabletask\src\DurableTask.Core\Serializing\DataConverter.cs:line 54
[2021-02-25T20:09:28.199Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationContext.GetInput[T]() in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 154
[2021-02-25T20:09:28.192Z] Host lock lease acquired by instance ID '0000000000000000000000003A509386'.
[2021-02-25T20:09:28.208Z]    at Curbit.Integrations.Orchestrator.OrderOrchestrator.StartOrderOrchestrator(IDurableOrchestrationContext context, ILogger log) in C:\Users\vany0\OneDrive\Documentos\GitHub\DrivingThru\Curbit-Infrastructure\src\dotnet\integrations\Curbit.Integrations.Orchestrators\Orchestrators\OrderOrchestrator.cs:line 33
[2021-02-25T20:09:28.230Z]    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 21
[2021-02-25T20:09:28.245Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[2021-02-25T20:09:28.255Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.4.1. SequenceNumber: 4. TaskEventId: -1
exception!
[2021-02-25T20:09:28.336Z] Executed 'OrderSaga' (Failed, Id=cb994eeb-88bf-4184-b393-569b8362ce9d, Duration=2603ms)
[2021-02-25T20:09:28.337Z] System.Private.CoreLib: Exception while executing function: OrderSaga. System.Private.CoreLib: Orchestrator function 'OrderSaga' failed: Unable to find a constructor to use for type System.Text.Json.JsonDocument. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'SourceIdentities.Order.RootElement', line 1, position 44.
```

### Relevant source code snippets
```csharp
public class Foo
{
     [JsonPropertyName("bar")]
     [JsonConverter(typeof(JsonConverterJsonDocument))]
     public JsonDocument Bar{ get; set; }
}
```

### Known workarounds
Use Newtonsoft instead of System.Text.Json to deal with serialization/deserialization :(

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0.15371.0
- **Programming language used**: C#
- **Microsoft.Azure.Functions.Extensions**: 1.1.0

I appreciate your help, thanks in advance!

**Comment by vany0114** [comment]
BTW let me know if I can help with that guys, I'd love it

**Comment by ConnorMcMahon** [comment]
The work to be done here would have to be done in a couple of places. @amdeel may have some more context, as she performed the work to help with [adding custom serialization](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp#customizing-serialization-with-dependency-injection) (note, our customer serialization points mainly just allow you to tweak the Newtonsoft.Json settings, not bypass Newtonsoft altogether). 

I think the projects that would need this would be at least DurableTask.Core (found in the [durable task repo](https://github.com/Azure/durabletask)), and the Functions extension project found in this repo.

I think if we were to add support for this, we would want to add a new interface to allow any serialization to a `string` (or possibly even to `byte[]`). Then we could plug into this generic extension point with our own built-in implementation with `System.Text.Json`, and if customers want to use some other serialization method, they could implement their version of the interface using dependency injection to customize serialization.

@vany0114, we are always happy to take external contributions, especially for features that would benefit lots of customers like this one. The only caveat is that I highly recommend solidifying a design with us first, so that we are on the same page about the end-user experience and code maintenance burden before you put in the effort of developing this feature.

**Comment by vany0114** [comment]
@ConnorMcMahon makes total sense, so let me know your thoughts on the design to get some context so that I can understand better the expectations then I can start to work on this, I'd be more than happy to put my two cents here! 😄 cc: @amdeel

**Comment by YunchuWang** [comment]
Closing in favor of the .NET isolated worker model, where Durable Functions uses System.Text.Json by default and honors the worker's configured serializer. The original in-process IDurableOrchestrationContext.GetInput API still uses Newtonsoft.Json; this closure does not indicate a serializer change to that API. For System.Text.Json support, migrate to isolated and use TaskOrchestrationContext.GetInput<T>(). See https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence#customizing-serialization-and-deserialization
