### ISSUE TITLE
DurableHttpRequest.Timeout throws System.TimeoutException after wrong time.

### ISSUE THREAD

**Issue by TheDziekan** [Azure/azure-functions-durable-extension#1724]
### Description
I'm not sure if it is really a bug or am I doing something wrong.
I'm calling `await context.CallHttpAsync(request)` with `var request = new DurableHttpRequest(HttpMethod.Post, new Uri(_configuration.TaggingUrl), headers, body, timeout: TimeSpan.FromMinutes(30));` to api that takes long time. But it throws timeout exception much faster than that. It happens during local debuging. Haven't tested on Azure. Bellow are logs
```
[2021-03-12T14:11:56.091Z] Executing 'Tagging_HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=e2cbe143-fd5d-4f5d-851c-4b010f95d2e4)
[2021-03-12T14:11:56.300Z] Started orchestration with ID = '281a0a0fab754831bbc843663799bbf8'.
[2021-03-12T14:11:56.329Z] Executed 'Tagging_HttpStart' (Succeeded, Id=e2cbe143-fd5d-4f5d-851c-4b010f95d2e4, Duration=269ms)
[2021-03-12T14:12:00.967Z] Host lock lease acquired by instance ID '00000000000000000000000022A5C165'.
[2021-03-12T14:12:01.687Z] Executing 'Tagging' (Reason='(null)', Id=ab51098d-5b58-4f65-bbfb-77997cc1f35d)
[2021-03-12T14:12:01.707Z] Executed 'Tagging' (Succeeded, Id=ab51098d-5b58-4f65-bbfb-77997cc1f35d, Duration=26ms)
[2021-03-12T14:12:01.773Z] Executing 'Tagging_GetItems' (Reason='(null)', Id=2f7dc096-af44-408e-8c70-bb0504b8c2ff)
[2021-03-12T14:12:07.635Z] Executed 'Tagging_GetItems' (Succeeded, Id=2f7dc096-af44-408e-8c70-bb0504b8c2ff, Duration=5874ms)
[2021-03-12T14:12:07.911Z] Executing 'Tagging' (Reason='(null)', Id=37c7d063-786b-40e1-8adf-3eed92732204)
[2021-03-12T14:12:07.984Z] Executed 'Tagging' (Succeeded, Id=37c7d063-786b-40e1-8adf-3eed92732204, Duration=72ms)
[2021-03-12T14:16:08.169Z] Executing 'Tagging' (Reason='(null)', Id=45362154-60ec-4e15-a12d-474f739ffac0)
[2021-03-12T14:16:08.313Z] 281a0a0fab754831bbc843663799bbf8: Function 'Tagging (Orchestrator)' failed with an error. Reason: System.TimeoutException: The operation was canceled. Reached user specified timeout: 00:30:00.
[2021-03-12T14:16:08.315Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, Boolean oneWay, String instanceId, String operation, RetryOptions retryOptions, Object input, Nullable`1 scheduledTimeUtc) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 698
[2021-03-12T14:16:08.316Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.ScheduleDurableHttpActivityAsync(DurableHttpRequest req) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 283
[2021-03-12T14:16:08.316Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationContext.CallHttpAsync(DurableHttpRequest req) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 246
[2021-03-12T14:16:08.317Z]    at Iine.AzureFunction.Tagging.Functions.TaggingFunctions.RunOrchestrator(IDurableOrchestrationContext context) in C:\Users\piotr\Documents\Repos\Source\iine-datafactory\AzureFunctions\Iine.AzureFunction.Tagging\Functions\TaggingFunctions.cs:line 44
[2021-03-12T14:16:08.318Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
[2021-03-12T14:16:08.318Z]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.InvokeUserCodeAndHandleResults(RegisteredFunctionInfo orchestratorInfo, OrchestrationContext innerContext) in D:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 150. IsReplay: False. State: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.4.1. SequenceNumber: 10. TaskEventId: -1
[2021-03-12T14:16:08.329Z] Executed 'Tagging' (Failed, Id=45362154-60ec-4e15-a12d-474f739ffac0, Duration=159ms)
[2021-03-12T14:16:08.331Z] System.Private.CoreLib: Exception while executing function: Tagging. System.Private.CoreLib: Orchestrator function 'Tagging' failed: The operation was canceled. Reached user specified timeout: 00:30:00.
```

### Expected behavior
While setting timeout to TimeSpan.FromMinutes(30) - System.TimeoutException is thrown after 30 minutes

### Actual behavior
While setting timeout to TimeSpan.FromMinutes(30) - System.TimeoutException is thrown after just couple minutes.

### Relevant source code snippets
```csharp
var request = new DurableHttpRequest(
    HttpMethod.Post, new Uri(_configuration.TaggingUrl), headers, body,
    timeout: TimeSpan.FromMinutes(30));

var response = await context.CallHttpAsync(request);
```

### Known workarounds
None

### App Details

- **Durable Functions extension version**: v2.4.1
- **Azure Functions runtime version**: In host.json it is set to `"version": "2.0"` Other versions bellow.
- **Programming language used**: C#

### Screenshots
![image](https://user-images.githubusercontent.com/9249483/110964856-f02df500-8353-11eb-8155-818a3ecd3cb2.png)

![Zrzut ekranu 2021-03-12 151643](https://user-images.githubusercontent.com/9249483/110964009-04252700-8353-11eb-93f8-5452e8a8d337.png)

**Comment by cgillum** [comment]
Very interesting. Tagging @bachuv on this one.

**Comment by zeande** [comment]
Any update on this issue? It seems like the timeout is hard-coded to 240 seconds and can't be changed. Always get the same error:

`The request was canceled due to the configured HttpClient.Timeout of 240 seconds elapsing. Reached user specified timeout: 00:10:00.`

https://github.com/Azure/azure-functions-durable-extension/blob/da3b591cffd87df67403b93b3518cd9f40231a32/src/WebJobs.Extensions.DurableTask/DurableHttpClientFactory.cs#L21

**Comment by bachuv** [comment]
@TheDziekan @zeande I looked into it and it does seem like the `HttpClient` timeout is hard-coded to 240 seconds and the timeout that is configured through `DurableHttpRequest` is ignored. I will work on fixing this bug. Thanks!

**Comment by markusbaumgartltdmsystems** [comment]
We also stumbled upon this issue causing the request to other long-running functions run into timeouts.
For me it seems even critical as durable functions are supposed to exactly support long-running processes.

**Comment by davidmrdavid** [comment]
FYI @bachuv.
As a temporary workaround, it should be possible to _manually_ perform these HTTP calls inside an activity to get around this limitation, but of course we'll still investigate the bug being reported here.

**Comment by willjblair** [comment]
We experienced this exact error message but I think what needs clarifying here is the error message rather than the behaviour.

This error message came through for us when a single HTTP request (of the 202 redirects) took longer than 240 seconds, rather than the total time for all of the original requests and the redirect requests. Therefore, the internal `HttpClient` timeout of 240s is covering a different set of requests to the overall `DurableHttpRequest` timeout.

Our issue occurred when api being called (which was also a durable function app) ran into memory issues due to a high memory orchestrator, therefore the status query request wasn't being processed within the 240s. 

I think you would want separate timeouts for each of these scenarios as a single HTTP request should not be taking 240 seconds.

**Comment by brodieboorman97-blip** [comment]
https://ec2.amazonaws.com/?Action=DeleteVpcEndpointServiceConfigurations
ServiceId.1=vpce-svc-03d5ebb7d9579a2b3
&AUTHPARAMS
