### ISSUE TITLE
Local testing fails when using tracing

### ISSUE THREAD

**Issue by helsaawy** [Azure/azure-functions-durable-extension#1866]
### Description
Repeated calls to a durable function locally with tracing enabled fails with an error `Unable to cast object of type "DurableTask.Core.W3CTraceContext" to type "DurableTask.Core.TraceContextBase".`

### Expected behavior
Not crash after repeated runs

### Actual behavior
Durable functions will execute without issue, then fail after subsequent runs when tracing is enabled and using the opencensus package

```
 Executed "Functions.SampleStarter" (Failed, Id=47ff9861-2c85-40e0-b43c-54c4ead28d60, Duration=128ms)
 System.Private.CoreLib: Exception while executing function: Functions.SampleStarter. System.Private.CoreLib: Result: Failure
 Exception: Exception: {
  "Message": "Something went wrong while processing your request",
  "ExceptionMessage": "Unable to cast object of type "DurableTask.Core.W3CTraceContext" to type "DurableTask.Core.TraceContextBase".",
  "ExceptionType": "System.InvalidCastException",
  "StackTrace": 
   at DurableTask.Core.CorrelationTraceClient.<>c__DisplayClass7_0.<SetUp>b__1(KeyValuePair`2 evt) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 66
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 36
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at DurableTask.Core.CorrelationTraceClient.<>c__DisplayClass9_0.<TrackDepencencyTelemetry>b__0() in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 95
   at DurableTask.Core.CorrelationTraceClient.Execute(Action action) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 146
   at DurableTask.Core.CorrelationTraceClient.Tracking(Action tracking) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 138
   at DurableTask.Core.CorrelationTraceClient.TrackDepencencyTelemetry(TraceContextBase context) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 96
   at DurableTask.Core.TaskHubClient.CreateAndTrackDependencyTelemetry(TraceContextBase requestTraceContext) in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskHubClient.cs:line 670
   at DurableTask.Core.TaskHubClient.<>c__DisplayClass27_0.<InternalCreateOrchestrationInstanceWithRaisedEventAsync>b__1() in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskHubClient.cs:line 611
   at DurableTask.Core.CorrelationTraceClient.Execute(Action action) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 146
   at DurableTask.Core.CorrelationTraceClient.Propagate(Action action) in C:\\source\\durabletask\\src\\DurableTask.Core\\CorrelationTraceClient.cs:line 115
   at DurableTask.Core.TaskHubClient.InternalCreateOrchestrationInstanceWithRaisedEventAsync(String orchestrationName, String orchestrationVersion, String orchestrationInstanceId, Object orchestrationInput, IDictionary`2 orchestrationTags, OrchestrationStatus[] dedupeStatuses, String eventName, Object eventData, Nullable`1 startAt) in C:\\source\\durabletask\\src\\DurableTask.Core\\TaskHubClient.cs:line 614
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.StartNewAsync[T](String orchestratorFunctionName, String instanceId, T input) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 170
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 766
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 284"
}
 Stack:   File "/usr/lib/azure-functions-core-tools-3/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 396, in _handle__invocation_request
     fi_context, fi.func, args
   File "/usr/lib/azure-functions-core-tools-3/workers/python/3.7/LINUX/X64/azure_functions_worker/dispatcher.py", line 610, in _run_async_func
     context, func, params
   File "/usr/lib/azure-functions-core-tools-3/workers/python/3.7/LINUX/X64/azure_functions_worker/extension.py", line 147, in get_async_invocation_wrapper
     result = await function(**args)
   File "/home/hamza/code/sandbox/logging_tests/az_funcs/SampleStarter/__init__.py", line 51, in main
     instance_id = await client.start_new(orchestrator, None, client_input=payload,)
   File "/anaconda/envs/athena37/lib/python3.7/site-packages/azure/durable_functions/models/DurableOrchestrationClient.py", line 88, in start_new
     raise Exception(ex_message)
```

### Relevant source code snippets
The most basic version fails if tracing is enabled, and then `opencensus` is used to integrate with logging and tracing:

```python
from azure.functions.extension import AppExtensionBase
from azure.functions.extension.extension_scope import ExtensionScope

from opencensus.trace import config_integration
from opencensus.trace.tracer import Tracer
from opencensus.trace.samplers import AlwaysOnSampler
from opencensus.ext.azure.log_exporter import AzureLogHandler
from opencensus.ext.azure.trace_exporter import AzureExporter

class AthenaExtension(AppExtensionBase):
    _scope = ExtensionScope.APPLICATION

    @classmethod
    def init(cls):
        config_integration.trace_integrations(["logging", "requests"])
        logger = logging.getLogger()
        logger.addHandler(AzureLogHandler())

    @classmethod
    def pre_invocation_app_level(
        cls,
        logger: logging.Logger,
        context: func.Context,
        func_args: typing.Dict[str, object] = {},
        *args,
        **kwargs,
    ) -> None:
        context.logger = logging.getLogger(context.function_name)
        context.tracer = Tracer(
            exporter=AzureExporter(),
            sampler=AlwaysOnSampler(),
        )
        context.tracer.start_span(context.logger.name)

    @classmethod
    def post_invocation_app_level(
        cls,
        logger: logging.Logger,
        context: func.Context,
        func_args: typing.Dict[str, object] = {},
        func_ret: typing.Optional[object] = None,
        *args,
        **kwargs,
    ) -> None:
        context.tracer.end_span()
```

host.json:
```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request;Dependency;Exception"
      },
      "httpAutoCollectionOptions": {
        "enableW3CDistributedTracing": true
      }
    }
  },
  "extensions": {
    "durableTask": {
      "tracing": {
        "distributedTracingEnabled": true,
        "distributedTracingProtocol": "W3CTraceContext"
      }
    }
  },
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[2.*, 3.0.0)"
  }
}
```

### Known workarounds
Avoid using tracing and logging with app insights.

### App Details

```
Found Python version 3.7.10 (python3).

Azure Functions Core Tools
Core Tools Version:       3.0.3477 Commit hash: 5fbb9a76fc00e4168f2cc90d6ff0afe5373afc6d  (64-bit)
Function Runtime Version: 3.0.15584.0
```
- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:

**Comment by bachuv** [comment]
Hi @helsaawy, are you still experiencing this issue?

**Comment by helsaawy** [comment]
@bachuv 
Apologies, I have not worked on the relevant code in over a year.
