### ISSUE TITLE
Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.DeterministicMethodAnalyzer' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation

### ISSUE THREAD

**Issue by thegrahamking** [Azure/azure-functions-durable-extension#1883]
### Description
After a build of my .NETCore 3.1 Function App using `Microsoft.Azure.WebJobs.Extensions.DurableTask` v2.4.3 with the (tranient dependency) `Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers` v0.4.0 I see an error in the build output `Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.DeterministicMethodAnalyzer' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation`

### Expected behavior
No exceptions cause by running the analyzer, only those that are triggered by the analyzer

### Actual behavior
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	AD0001	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.DeterministicMethodAnalyzer' threw an exception of type 'System.ArgumentException' with message 'SyntaxTree is not part of the compilation
Parameter name: syntaxTree'.
Exception occurred with following context:
Compilation: <project name>

System.ArgumentException: SyntaxTree is not part of the compilation
Parameter name: syntaxTree
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.GetSemanticModel(SyntaxTree syntaxTree, Boolean ignoreAccessibility)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.SyntaxNodeUtils.TryGetSemanticModelForSyntaxTree(SemanticModel model, SyntaxNode node, SemanticModel& newModel)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.SyntaxNodeUtils.TryGetITypeSymbol(SemanticModel semanticModel, SyntaxNode node, ITypeSymbol& typeSymbol)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.IOTypesAnalyzer.RegisterDiagnostic(CompilationAnalysisContext context, SemanticModel semanticModel, SyntaxNode method)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.DeterministicMethodAnalyzer.RegisterAnalyzers(CompilationAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteCompilationActionsCore>b__48_1(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: DF0101, DF0102, DF0103, DF0104, DF0105, DF0106, DF0107, DF0111	<project name>		1	Active

```

### Known workarounds
None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.3
- **Azure Functions runtime version (1.0 or 2.0)**: 3
- **Programming language used**: .NET
- The following in project file:
  - `<EnableNETAnalyzers>true</EnableNETAnalyzers>`
  - `<AnalysisMode>AllEnabledByDefault</AnalysisMode>`
  - `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>`
  - `<WarningsNotAsErrors>612,618</WarningsNotAsErrors>`
   - `<NoWarn>1701;1702;1591;VSTHRD200</NoWarn>`

**Comment by amdeel** [comment]
Hey, @thegrahamking. Is this still a consistent error you get using the analyzer on your project? Could I get a copy of your project as a repro?

**Comment by thegrahamking** [comment]
Hi @amdeel, It is consistent with this project yes.  I can't give you a copy I'm afraid but I'll try to repo in a project I can share

**Comment by thegrahamking** [comment]
Unfortuntely I'm unable to pair back our project enough to retain the build error but allow it to compile.

Is there anything else I can do to investigate?

**Comment by amdeel** [comment]
Hey @thegrahamking sorry it's taken so long to get to this bug. I wanted to check in and see if this is still consistently an issue for you, even after VS restarts. If so, I can give you a test nuget package to reference that might (hopefully) be able to provide some more information to help figure out what's going on here and diagnose this issue.

**Comment by thegrahamking** [comment]
Hi @amdeel. No worries. Yes still an issue.  Happy to give a test nuget package a try.

**Comment by amdeel** [comment]
Hey @thegrahamking I published a preview nuget package to our public app service myget feed with an analyzer version that will both eliminate these warnings and hopefully give us useful information to help investigate and repro this.

You can access this nuget package by adding our app service myget feed (feed url: https://www.myget.org/F/azure-appservice/api/v3/index.json).

Add the analyzer package explicitly: <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.4.1-preview" />

Keep in mind, you'll need to restart all instances of VisualStudio after you do this.

This nuget package should turn these warnings into information level diagnostics that contain the original exception details as well as the syntax node that was being analyzed when the exception was thrown. You should see an information diagnostic/squiggle on the specific node (some identifier) being analyzed as well as the detailed message in your VisualStudio error list. This change should prevent you from having to disable analyzers and will also, hopefully, give us enough information to investigate this further. Please let me know if this works correctly, as I didn't have your test case to use to properly test this out.

I know you said previously that you couldn't share your code but, hopefully, this diagnostic can narrow down where in your project this node being analyzed is located and what deterministic methods/methods related to orchestrator code its associated with, which might significantly narrow down the code you need to share and help give us a proper repro or better pinpoint what might be causing the error. If you can share snippets of your code related to the diagnostic, or if you are able to share your code/code snippets privately, let me know and you can send me an email instead of publicly sharing over GitHub.

**Comment by thegrahamking** [comment]
`RoleId` is a value object
``` csharp
public readonly struct RoleId : IComparable<RoleId>, IEquatable<RoleId>
    {
        public static readonly RoleId Owner = new RoleId("Owner");

        public static readonly RoleId ReadWrite = new RoleId("ReadWrite:All");

        public static readonly IReadOnlyCollection<RoleId> All = new[] {Owner, ReadWrite};

        public static RoleId Parse(string value) =>
            !TryParse(value, out var roleId)
                ? throw new FormatException($"'{value}' is not a valid {nameof(RoleId)}")
                : roleId;

        public static bool TryParse(string value, out RoleId roleId)
        {
            var result = All.SingleOrDefault(a => a.Value.Equals(value, StringComparison.OrdinalIgnoreCase));
            if (result == default)
            {
                roleId = default;
                return false;
            }

            roleId = result;
            return true;
        }

        public string Value { get; }

        internal RoleId(string value)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Is null, empty or whitespace", nameof(value));
            }

            Value = value;
        }

        public bool Equals(RoleId other) => Value == other.Value;

        public override bool Equals(object obj) => obj is RoleId other && Equals(other);

        public override int GetHashCode() => Value.GetHashCode();

        public int CompareTo(RoleId other) => string.Compare(Value, other.Value, StringComparison.Ordinal);

        public override string ToString() => Value;

        public static bool operator ==(RoleId a, RoleId b) => a.CompareTo(b) == 0;
        public static bool operator !=(RoleId a, RoleId b) => !(a == b);

        public TenantRoleId ForTenant(TenantId tenantId) => new TenantRoleId(tenantId, this);
    }
```
It has a serializer
``` csharp
public class RoleIdConverter : JsonConverter<RoleId>
    {
        public override void WriteJson(JsonWriter writer, RoleId value, JsonSerializer serializer) =>
            writer.WriteValue(value.Value);

        public override RoleId ReadJson(JsonReader reader, Type objectType, RoleId existingValue,
            bool hasExistingValue,
            JsonSerializer serializer) => new RoleId((string)reader.Value);
    }
```
There are a couple of other value objects which will be relevant below so including them here as well:
``` csharp
public readonly struct TenantRoleId : IComparable<TenantRoleId>, IEquatable<TenantRoleId>
    {
        public TenantId TenantId { get; }
        public RoleId RoleId { get; }

        public string Value { get; }

        internal TenantRoleId(TenantId tenantId, RoleId roleId)
        {
            TenantId = tenantId;
            RoleId = roleId;
            Value = $"{tenantId.Value}:{roleId.Value}";
        }

        public bool Equals(TenantRoleId other) => Value.Equals(other.Value);
        public int CompareTo(TenantRoleId other) => string.Compare(Value, other.Value, StringComparison.Ordinal);

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            return obj is TenantRoleId other && Equals(other);
        }

        public override int GetHashCode() => Value.GetHashCode();
        public override string ToString() => Value;

        public static bool operator ==(TenantRoleId a, TenantRoleId b) => a.CompareTo(b) == 0;
        public static bool operator !=(TenantRoleId a, TenantRoleId b) => !(a == b);
    }

    public readonly struct TenantId : IComparable<TenantId>, IEquatable<TenantId>
    {
        // Validation rule is the same as event type for consistency to clients, no other reason
        private static readonly Regex Validator = EventTypeId.Validator;

        public string Value { get; }

        public TenantId(string value)
            : this(value, true)
        {
        }

        private TenantId(string value, bool validate)
        {
            if (validate && !TryValidate(value, out var message))
            {
                throw new ArgumentException(message);
            }

            Value = value;
        }

        public bool Equals(TenantId other) => Value.Equals(other.Value, StringComparison.OrdinalIgnoreCase);
        public int CompareTo(TenantId other) => string.Compare(Value, other.Value, StringComparison.OrdinalIgnoreCase);

        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            return obj is TenantId other && Equals(other);
        }

        public override int GetHashCode() => Value.ToLowerInvariant().GetHashCode();
        public override string ToString() => Value;

        public static bool operator ==(TenantId a, TenantId b) => a.CompareTo(b) == 0;
        public static bool operator !=(TenantId a, TenantId b) => !(a == b);

        public static bool TryCreate(string value, out TenantId? created, out string failureReason)
        {
            if (TryValidate(value, out failureReason))
            {
                created = new TenantId(value, false);
                return true;
            }

            created = null;
            return false;
        }

        private static bool TryValidate(string value, out string failureReason)
        {
            if (!string.IsNullOrWhiteSpace(value) && Validator.IsMatch(value))
            {
                failureReason = null;
                return true;
            }

            failureReason = $"'{value}' is not a valid tenant id." + Environment.NewLine +
                            "A tenant id must conform to the following rules:" + Environment.NewLine +
                            "\t- Must start and end with a letter or number, and can contain only letters, numbers, and the dash (-) character" + Environment.NewLine +
                            "\t- Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted" + Environment.NewLine +
                            "\t- Must be from 3 through 40 characters long";
            return false;
        }

```

The project setup is as follows
```
.
├── AzureFunctionApp/
│   ├── MyOrchestrator1
│   └── MyOrchestrator2
├── DomainSerializationClassLibrary/
│   ├── RoleIdConverter
│   └── ...
└── DomainClassLibrary/
    ├── RoleId
    ├── TenantId
    └── TenantRoleId
```

`AzureFunctionApp` has a project dependency on `DomainSerializationClassLibrary` which has a dependency on `DomainClassLibrary`

The error above is reported against the `AzureFunctionApp` project.

`MyOrchestrator1` in `AzureFunctionApp` calls an activity function which takes a `TenantRoleId` as an input which is created using `RoleId.Owner.ForTenant` (that's the `MyOrchestrator1` to `RoleId` relationship) in parellel with another activity function, both using extension methods:
``` csharp
await Task.WhenAll(
                context.CallMyRoleBasedActivityAsync(new MyRoleBasedActivityRequest
                {
                    TenantRoleId = RoleId.Owner.ForTenant(input.TenantId),
                    // ...
                }),
                context.CallMyOtherActivityAsync(new CallMyOtherActivityRequest
                {
                    // ...
                }));
```
The extension methods all have this format:
``` csharp
public static Task CallMyRoleBasedActivityAsync(this IDurableOrchestrationContext context,
            MyRoleBasedActivityRequest request) =>
            context.CallActivityWithRetryAsync(
                "CallMyRoleBasedActivityFunctionName",
                RetryOptions.Default,
                request);
```

I hope that helps

**Comment by amdeel** [comment]
@thegrahamking Ok, sorry about that, I made a mistake in my last preview package. Latest package: 0.4.1-preview4.

**Comment by thegrahamking** [comment]
\o/ no errors with 0.4.1-preview4.

Out of curioristy, what about our setup was causing the original error?

**Comment by amdeel** [comment]
Hey @thegrahamking I wanted to update you that we were able to release 2.6.0 with this updated analyzer package today. Sorry, it took longer than expected to get the release out.
