### ISSUE TITLE
Deploying with func kubernetes deploy lead to "Unable to load metadata" exception

### ISSUE THREAD

**Issue by koscelansky** [Azure/azure-functions-durable-extension#2110]
### Description

Example Durable Functions orchestration in C# do not work when deployed to kubernetes via Azure Functions Core Tools. I create a minimal repro example here [https://github.com/koscelansky/issue-k8s-durable-func-csharp]. There are also steps how to reproduce it. 

I tried local kuberneters (minikube) and also azure hosted (AKS). 

What I think is happening. Running `func kubernetes deploy` will create two deployments, (one for http and one for other tasks)[https://github.com/Azure/azure-functions-core-tools/blob/dev/src/Azure.Functions.Cli/Kubernetes/KubernetesHelpers.cs#L132] (it is done via env variables). Likely this is because non-http can be scaled with KEDA (using MS SQL Server backend, we also try that, but the result is the same). But it seems like http one also pick ups durable tasks, however that will not work, since those durable workflows are not inside http deployment. I think this is happening, because I see in logs like (for http deployment).

```
dbug: DurableTask.Core[24]
      TaskOrchestrationDispatcher-7b9d12ee266842e6936a87539e86cb10-0: Fetched next work item '2369fa71719547c2bbda85826f244cb9' after 75639ms. Current active work-item count: 0. Maximum active work-item count: 80
dbug: DurableTask.Core[23]
      TaskOrchestrationDispatcher-7b9d12ee266842e6936a87539e86cb10-0: Fetching next work item. Current active work-item count: 1. Maximum active work-item count: 80. Timeout: 30s
dbug: DurableTask.Core[27]
      TaskOrchestrationDispatcher-7b9d12ee266842e6936a87539e86cb10-0: Processing work-item '2369fa71719547c2bbda85826f244cb9'
```

### Expected behavior
HTTP trigger should work and orchestration should started and finished OK.

### Actual behavior
Calling orchestration failed with exception 

```plain
fail: Function.TestDurableFunctionsOrchestration[3]
      Executed 'TestDurableFunctionsOrchestration' (Failed, Id=71b08df3-deb2-4a52-8ff8-b7a215bbbfcd, Duration=4ms)
System.InvalidOperationException: Unable to load metadata for function 'TestDurableFunctionsOrchestration'.
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.StartFunction(FunctionInstanceLogEntry item) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:line 125
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:line 89
   at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionEventCollector.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\CompositeFunctionEventCollector.cs:line 23
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functi
```

### Known workarounds
It work for python environments, but you need to add `"externalClient": true` to bindings. [https://github.com/Azure/azure-functions-core-tools/issues/2345] However adding `ExternalClient = true` in `[DurableClient] IDurableOrchestrationClient starter` in C# do not work.

### App Details

- **Durable Functions extension version**: 2.6.1
- **Azure Functions runtime version**: 3.0.11
- **Programming language used**: C#

### If deployed to Azure

I tried it in AKS, but the result is the same. 

Let me know if you need more data.

**Comment by cgillum** [comment]
If the problem was with `ExternalClient = true`, then I think I'd expect there to be a different error message explaining that the orchestrator function wasn't found. The error about metadata seems different. I've actually seen a similar issue when running on Kubernetes that seems to be caused by a race condition in the Azure Functions host. I'm not sure why it seems to happen most frequently with Durable Functions, though. The workaround for me was to increase the resource allocation for the containers. Can you try that and see if it helps?

**Comment by koscelansky** [comment]
I tested it one more time and still  no luck. I added external client here https://github.com/koscelansky/issue-k8s-durable-func-csharp/blob/fec2d4f13080ad6076c5640f76e0291cda93aa7e/TestDurableFunctionsOrchestration.cs#L39 . But I also noticed, that sometimes the orchestrator will run. It is however very rarely, like 1 in 10. When running in AKS I tried it with standard Bs VMs, but there was barely few triggers, not like I was trying 1000s of triggers. CPU was under 5% on those pods. 

What I do not understand is why in python it is working with `externalClient: true`.

**Comment by cgillum** [comment]
@anirudhgarg who can help investigate issues that are specific to running Functions on Kubernetes? I see this problem above frequently but only in Kubernetes and it's very intermittent. My understanding from talking about this issue with @balag0 a while ago is that it's likely to be some race condition in the Azure Functions host startup code.

I'm specifically referring to this error message ("Unable to load metadata for function"):
```
System.InvalidOperationException: Unable to load metadata for function 'TestDurableFunctionsOrchestration'.
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.StartFunction(FunctionInstanceLogEntry item) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:line 125
   at Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.FunctionInstanceLogger.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in /src/azure-functions-host/src/WebJobs.Script.WebHost/Diagnostics/FunctionInstanceLogger.cs:line 89
   at Microsoft.Azure.WebJobs.Host.Loggers.CompositeFunctionEventCollector.AddAsync(FunctionInstanceLogEntry item, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\CompositeFunctionEventCollector.cs:line 23
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functi
```

**Comment by anirudhgarg** [comment]
Hi @cgillum  - @mukundnigam can help route. He is helping on running Functions on Kubernetes.

**Comment by mukundnigam** [comment]
tagging @krishna-kariya

**Comment by krishna-kariya** [comment]
Sure, @mukundnigam. I will look into the issue.

**Comment by koscelansky** [comment]
Hi, thanks for looking into it. I tried one more thing and that is to physically split the functions, one deployment with http trigger and the other one with activity and orchestrations. Than I need to add `ExternalClient = true` to http trigger (it will otherwise complain), after this midification it is running flawlessly. So  there is only issue when environment variables `AzureFunctionsJobHost__functions__X` are used to enable just some functions.

**Comment by robersonliou** [comment]
Hello @krishna-kariya , 

any update here?
