### ISSUE TITLE
IDurableOrchestrationClient.ListInstancesAsync throws excepton on .NET Framework 4.8 when used in WebJobs

### ISSUE THREAD

**Issue by michaelelleby** [Azure/azure-functions-durable-extension#2292]
### Description
Trying to list instances of orchestrators with IDurableOrchestrationClient.ListInstancesAsync() crashes on .NET Framework 4.8. The same code works on .NET 6.
I am using the Azurite emulator version 3.19.0 for storage with the connection string `AzureWebJobsStorage` set to `UseDevelopmentStorage=true`
The code is running as an Azure WebJob.

### Expected behavior
List of instances should be returned.

### Actual behavior
> A clear and concise description of what actually happened.
```
DurableTask.AzureStorage.Storage.DurableTaskStorageException: The property 'value' does not exist on type 'devstoreaccount1.Tables'. Make sure to only use property names that are defined by the type. ---> Microsoft.WindowsAzure.Storage.StorageException: The property 'value' does not exist on type 'devstoreaccount1.Tables'. Make sure to only use property names that are defined by the type. ---> Microsoft.Data.OData.ODataException: The property 'value' does not exist on type 'devstoreaccount1.Tables'. Make sure to only use property names that are defined by the type.
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadUndeclaredProperty(IODataJsonLightReaderEntryState entryState, String propertyName, Boolean propertyWithValue)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryPropertyWithValue(IODataJsonLightReaderEntryState entryState, String propertyName)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.<>c__Dis
playClass2.<ReadEntryContent>b__0(PropertyParsingResult propertyParsingResult, String propertyName)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightDeserializer.ProcessProperty(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, Func`2 readPropertyAnnotationValue, Action`2 handleProperty)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightEntryAndFeedDeserializer.ReadEntryContent(IODataJsonLightReaderEntryState entryState)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadEntryStart(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker, SelectedPropertiesNode selectedProperties)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementationSynchronously(DuplicatePropertyNamesChecker duplicatePropertyNamesChecker)
   at Microsoft.Data.OData.JsonLight.ODataJsonLightReader.ReadAtStartImplementation()
   at Microsoft.Data.OData.ODataReaderCore.ReadImplementation()
   at Microsoft.Data.OData.ODataReaderCore.ReadSynchronously()
   at Microsof
t.Data.OData.ODataReaderCore.InterceptException[T](Func`1 action)
   at Microsoft.Data.OData.ODataReaderCore.Read()
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.ReadOdataEntity(TableResult result, TableOperation operation, IODataResponseMessage respMsg, OperationContext ctx, ODataMessageReaderSettings readerSettings, String accountName, TableRequestOptions options) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Table\\Protocol\\TableOperationHttpResponseParsers.cs:line 435
   at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpResponseParsers.TableOperationPostProcess(TableResult result, TableOperation operation, RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx, TableRequestOptions options, String accountName) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Table\\Protocol\\TableOperationHttpResponseParsers.cs:line 123
   at Microsoft.
WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass18.<RetrieveImpl>b__17(RESTCommand`1 cmd, HttpWebResponse resp, OperationContext ctx) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Table\\TableOperation.cs:line 230
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessEndOfRequest[T](ExecutionState`1 executionState) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Executor\\Executor.cs:line 898
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndOperation[T](ExecutionState`1 executionState) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Executor\\Executor.cs:line 425
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Util\\StorageAsyncResult.
cs:line 77
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.EndCreateIfNotExists(IAsyncResult asyncResult) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Table\\CloudTable.cs:line 1183
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar) in c:\\Program Files (x86)\\Jenkins\\workspace\\release_dotnet_master\\Lib\\ClassLibraryCommon\\Core\\Util\\AsyncExtensions.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at DurableTask.AzureStorage.TimeoutHandler.<ExecuteWithTimeout>d__3`1.MoveNext() in /_/src/DurableTask.AzureStorage/TimeoutHandler.cs:line 48
--- End of stack trace from p
revious location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.Storage.AzureStorageClient.<MakeStorageRequest>d__33`1.MoveNext() in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 136
   --- End of inner exception stack trace ---
   at DurableTask.AzureStorage.Storage.AzureStorageClient.<MakeStorageRequest>d__33`1.MoveNext() in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.Storage.Table.<CreateIfNotExistsAsync>d__10.MoveNext() in /_/src/DurableTask.AzureStorage/St
orage/Table.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<GetTaskHubCreatorTask>d__52.MoveNext() in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 328
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<EnsureTaskHubAsync>d__51.MoveNext() in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 304
--- End of stack trace from previous location where exception was thrown ---
   at System.R
untime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<GetOrchestrationStateAsync>d__110.MoveNext() in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 1730
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProvider.<GetOrchestrationStateWithPagination>d__31.MoveNext() in D:\\a\\_work\\1\\s\\src\\WebJobs.Extensions.DurableTask\\AzureStorageDurabilityProvider.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSucces
s(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NetFX48.Functions.<TimerStart>d__0.MoveNext() in C:\\Users\\Michael\\source\\repos\\DurableTaskListInstancesBug\\NetFX48\\Functions.cs:line 12
```

### Relevant source code snippets
```csharp
public class Functions
{
	public async Task TimerStart([TimerTrigger("*/5 * * * * *")] TimerInfo myTimer, [DurableClient] IDurableOrchestrationClient client)
	{
		await client.ListInstancesAsync(new OrchestrationStatusQueryCondition(), CancellationToken.None);
	}
}
```

I have created a small sample project at https://github.com/michaelelleby/DurableTaskListInstancesBug to demonstrate the issue. The Git branch `Net6` contains the same code, targeting .NET 6 instead of .NET Framework 4.8 and that branch works as expected. Therefore this is a bug specifically in .NET Framework 4.8, and possibly earlier .NET Framework versions.

The .NET 6 code uses version 3.0.33 of `Microsoft.Azure.WebJobs`, while the .NET Framework 4.8 code uses version 2.3.0 of `Microsoft.Azure.WebJobs` because .NET 6 requires version 3.0.31 or newer and .NET Framework 4.8 does not compile with version 3.0.31 because of bug #2291

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.8.1
- **Azure Functions runtime version (1.0 or 2.0)**: N/A
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by michaelelleby** [comment]
I discovered this only happens when I use Azurite for storage. If I use a connection string for a real Azure Storage Account, the problem goes away.

**Comment by cgillum** [comment]
We've been noticing a few problems with Azurite integration lately. It's possible that some of the older Azure Storage SDK dependencies we have in the .NET 4.x flavor of Durable Functions are not compatible with Azurite. My personal recommendation is to try and stick with the old Azure Storage Emulator for local development. It continues to work flawlessly, though we should definitely look into whether we can improve our Azurite integration to account for cases like yours.

FYI @AnatoliB
