### ISSUE TITLE
Durable function fails with `TaskCanceledException` and never gets retried

### ISSUE THREAD

**Issue by RichardBurns1982** [Azure/azure-functions-durable-extension#2454]

**Comment by jviau** [comment]
Addressed, pending release of 2.9.5

**Comment by apringle** [comment]
> Addressed, pending release of 2.9.5

Thank you, is there any timeframe or plan for this release? Our upgrades are currently blocked pending this fix.

**Comment by RichardBurns1982** [comment]
> Addressed, pending release of 2.9.5

Thanks @jviau, does this need fixing in Microsoft.Azure.Functions.Worker.Extensions.DurableTask as we are running in isolated which is where we have encountered this problem.

**Comment by jviau** [comment]
@RichardBurns1982 - yes, this fix is for Java and dotnet isolated durable extensions. We will be aiming to release soon here.

**Comment by jviau** [comment]
> I see that 2.9.5 of Microsoft.Azure.WebJobs.Extensions.DurableTask was released yesterday, do you know when you will be releasing Microsoft.Azure.Functions.Worker.Extensions.DurableTask update which will include this fix for isolated?

No release is needed. Rebuilding your worker app should pick up the newer version of `Microsoft.Azure.WebJobs.Extensions.DurableTask`

**Comment by RichardBurns1982** [comment]
> 

Thanks jviau

I might need a little help understanding that.  We are not referencing Microsoft.Azure.WebJobs.Extensions.DurableTask we are only referencing Microsoft.Azure.Functions.Worker.Extensions.DurableTask in isolated, this hasn't had a release since April 7th.  I'm not seeing any dependencies to Microsoft.Azure.WebJobs.Extensions.DurableTask.

As I understand it Microsoft.Azure.WebJobs.Extensions.DurableTask is for the legacy and soon to be deprecated in-process with .net 8 I believe.

We've moved all our functions to isolated and removed all legacy packages for in-process and referencing the new ones such as Microsoft.Azure.Functions.Worker.Extensions.DurableTask.  This is where we are seeing the problem, we never saw it in isolated.

Many thanks.

**Comment by nhuurnink** [comment]
We have the same problem, also using Microsoft.Azure.Functions.**Worker**.Extensions.DurableTask

Will there be an upgrade for this extension as well?

**Comment by jviau** [comment]
The upgrade experience does look like you aren't doing anything, but dotnet isolated function apps have a build target which resolves the webjobs (host) extensions. In this case, the package `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` has an [attribute](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/AssemblyInfo.cs#L7) which tells the build task to pull in `Microsoft.Azure.WebJobs.Extensions.DurableTask/2.9.*`. Since we use a `*` in the version, simply building your app again should trigger a restore of the latest version.

So getting the new fix should be as simple as re-building and deploying your app.

**Comment by RichardBurns1982** [comment]
> The upgrade experience does look like you aren't doing anything, but dotnet isolated function apps have a build target which resolves the webjobs (host) extensions. In this case, the package `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` has an [attribute](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/AssemblyInfo.cs#L7) which tells the build task to pull in `Microsoft.Azure.WebJobs.Extensions.DurableTask/2.9.*`. Since we use a `*` in the version, simply building your app again should trigger a restore of the latest version.
> 
> So getting the new fix should be as simple as re-building and deploying your app.

Thank you @jviau, I did not know that and will keep an eye out on the code in future.

I will raise a separate bug for the TaskCancelledException as regardless of Durable this is still a problem filling up our App Insights errors

**Comment by revealer409** [comment]
I am using durable orchestration with multiple activities and sub orchestrations for processing Master data from CSV to json and then dump into Npgsql but i am getting this issue.

I have tried different ways to get rid of this issue but still getting failed 9 out of 10 runs.

SDK & Packages details below.
  <TargetFramework>net8.0</TargetFramework>
  <AzureFunctionsVersion>v4</AzureFunctionsVersion>
  
  
  Packages:
  
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="1.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.22.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.2.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.13.4" />
    

[DownloadFileFromFtp]:(End) Downloading Complete
[2024-06-09T12:10:13.130Z] An error occurred while executing the orchestrator function 'DownloadFileFromFtpOrchestration'.
[2024-06-09T12:10:13.131Z] Result: An error occurred while executing the orchestrator function 'DownloadFileFromFtpOrchestration'.
Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
[2024-06-09T12:10:13.132Z]    at Microsoft.Azure.Functions.Worker.Context.Features.DefaultFunctionInputBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultFunctionInputBindingFeature.cs:line 32
[2024-06-09T12:10:13.132Z]    at Greenbox.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\GreenBox\Solution\Functionapp\Greenbox\Greenbox\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 36
[2024-06-09T12:10:13.133Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-06-09T12:10:13.134Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\extensions\Worker.Extensions.Http.AspNetCore\src\FunctionsMiddleware\FunctionsHttpProxyingMiddleware.cs:line 38
