### ISSUE TITLE
TaskOrchestrationContext.ContinueAsNew with preserveUnprocessedEvents: true reencodes events

### ISSUE THREAD

**Issue by ZTonks** [Azure/azure-functions-durable-extension#2589]
There appears to be an issue with usage of `ContinueAsNew` with durable orchestrations in .NET7 with isolated process Azure functions. We have found that preserving unprocessed events causes the serialized object in the orchestration history to be encoded again as a string, which then causes issues when the worker comes to deserialize this object and finds it is double encoded.

[This repository](https://github.com/ZTonks/serialization-test) contains a minimal repro of the bug. In particular there are three branches, two of which are using isolated process (`isolated`, `hack`) (`isolated` is the main reproduction of the bug) and the other in-process (which does not exhibit the bug). The `hack` branch contains a workaround for the bug using isolated.

The minimal repro has:
* A timed function sending events to an eternal orchestration.
* An eternal orchestration consuming events, but also waiting on a durable timer at a longer schedule than that of the timed function such that there are unconsumed events that need to be preserved.
* The eternal orchestration calls `context.ContinueAsNew(preserveUnprocessedEvents: true)` to preserve events, which get reencoded under the isolated process model, causing the bug. They are not reencoded under out of process.

The reencoded events look like the attached image 
![encoding-taskhub](https://github.com/Azure/azure-functions-dotnet-worker/assets/21169977/99ea9666-9e48-4373-8d28-f408300c7ff6) for the orchestration history table.

You'll see on the `hack` branch that a 'try to deserialize twice else once' approach is a workaround for this issue. As it happens, in configuring the worker with our own custom serializer, we were not able to observe any instances where the custom serializer is asked to serialize an already serialized object.

Stack trace for bug on isolated, deserializing an event after `ContinueAsNew`:
```
[2023-09-13T10:40:30.419Z] Function 'DoSomething', Invocation id 'daa1a9ae-cd62-42a8-bfc6-f4018bb321a6': An exception was thrown by the invocation.
[2023-09-13T10:40:30.424Z] Result: Function 'DoSomething', Invocation id 'daa1a9ae-cd62-42a8-bfc6-f4018bb321a6': An exception was thrown by the invocation.
Exception: System.Text.Json.JsonException: The JSON value could not be converted to serialization_test.MyObject. Path: $ | LineNumber: 0 | BytePositionInLine: 55.
[2023-09-13T10:40:30.428Z]    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
[2023-09-13T10:40:30.432Z]    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2023-09-13T10:40:30.436Z]    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
[2023-09-13T10:40:30.451Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2023-09-13T10:40:30.456Z]    at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
[2023-09-13T10:40:30.460Z]    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
[2023-09-13T10:40:30.464Z]    at System.Text.Json.JsonSerializer.Deserialize(ReadOnlySpan`1 utf8Json, Type returnType, JsonSerializerOptions options)
[2023-09-13T10:40:30.475Z]    at Azure.Core.Serialization.JsonObjectSerializer.Deserialize(Stream stream, Type returnType, CancellationToken cancellationToken)
[2023-09-13T10:40:30.483Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.ObjectConverterShim.Deserialize(String data, Type targetType) in /_/src/Worker.Extensions.DurableTask/ObjectConverterShim.cs:line 32
[2023-09-13T10:40:30.501Z]    at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CompleteExternalEvent(String eventName, String rawEventPayload)
[2023-09-13T10:40:30.517Z]    at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationShim.RaiseEvent(OrchestrationContext context, String name, String input)
[2023-09-13T10:40:30.530Z]    at DurableTask.Core.TaskOr
![encoding-taskhub](https://github.com/Azure/azure-functions-dotnet-worker/assets/21169977/e4bfc0ef-d92b-46e6-ad37-3143d5ddc9a9)
chestrationContext.HandleEventRaisedEvent(EventRaisedEvent eventRaisedEvent, Boolean skipCarryOverEvents, TaskOrchestration taskOrchestration) in /_/src/DurableTask.Core/TaskOrchestrationContext.cs:line 411
[2023-09-13T10:40:30.545Z]    at DurableTask.Core.TaskOrchestrationExecutor.ProcessEvent(HistoryEvent historyEvent) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 225
[2023-09-13T10:40:30.563Z]    at DurableTask.Core.TaskOrchestrationExecutor.<ExecuteCore>g__ProcessEvents|11_0(IEnumerable`1 events) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 115
[2023-09-13T10:40:30.574Z]    at DurableTask.Core.TaskOrchestrationExecutor.ExecuteCore(IEnumerable`1 pastEvents, IEnumerable`1 newEvents) in /_/src/DurableTask.Core/TaskOrchestrationExecutor.cs:line 128
```

**Comment by cgillum** [comment]
@jviau do you know what this issue might be?

**Comment by jviau** [comment]
It is a double serialization issue: https://github.com/microsoft/durabletask-dotnet/blob/main/src/Worker/Core/Shims/TaskOrchestrationContextWrapper.cs#L241C37-L241C37
