### ISSUE TITLE
Orchestration - ScheduleNewOrchestrationInstanceAsync fails in versions >1.16.0 1.16.1 

### ISSUE THREAD

**Issue by alhell** [Azure/azure-functions-durable-extension#2668]
After upgrading to Microsoft.Azure.Functions.Worker.Sdk 1.16.0/1.16.1, the orchestration has stopped working. We have reverted to 1.15.1.

Error logs below:

`[2023-11-11T20:36:04.621Z]    --- End of inner exception stack trace ---
[2023-11-11T20:36:04.623Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-11-11T20:36:04.627Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-11-11T20:36:04.630Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-11-11T20:36:04.631Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-11-11T20:36:04.633Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.634Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.635Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.636Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-11-11T20:36:04.637Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.638Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-11-11T20:36:04.638Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-11-11T20:36:04.641Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-11-11T20:36:04.643Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-11-11T20:36:04.643Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-11-11T20:36:04.644Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-11-11T20:36:04.645Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.647Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.648Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.649Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-11-11T20:36:04.650Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.651Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-11-11T20:36:04.652Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-11-11T20:36:04.653Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77.
[2023-11-11T20:36:04.659Z] Executed 'Functions.SendEnvelopeOrchestratorStarter' (Failed, Id=3ab0b77b-776e-49cb-9b4b-972877c9b04a, Duration=837ms)
[2023-11-11T20:36:04.660Z] System.Private.CoreLib: Exception while executing function: Functions.SendEnvelopeOrchestratorStarter. System.Private.CoreLib: Result: Failure
Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode="Unknown", Detail="Exception was thrown by handler."))
[2023-11-11T20:36:04.661Z]  ---> Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
[2023-11-11T20:36:04.662Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.ScheduleNewOrchestrationInstanceAsync(TaskName orchestratorName, Object input, StartOrchestrationOptions options, CancellationToken cancellation)
[2023-11-11T20:36:04.663Z]    at DocusignIntegrator.Function.SendEnvelopeOrchestration.SendEnvelopeOrchestratorStarter(HttpRequestData req, DurableTaskClient client, FunctionContext executionContext) in C:\Users\helal.futloo\source\repos\DocusignIntegrator\DocusignIntegrator\Function\SendEnvelopeOrchestrator.cs:line 26
[2023-11-11T20:36:04.664Z]    --- End of inner exception stack trace ---
[2023-11-11T20:36:04.665Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-11-11T20:36:04.665Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-11-11T20:36:04.666Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-11-11T20:36:04.666Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-11-11T20:36:04.667Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.668Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.668Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.669Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-11-11T20:36:04.669Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.670Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-11-11T20:36:04.670Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-11-11T20:36:04.671Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-11-11T20:36:04.673Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2023-11-11T20:36:04.674Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2023-11-11T20:36:04.675Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32
[2023-11-11T20:36:04.675Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2023-11-11T20:36:04.676Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.677Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.677Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2023-11-11T20:36:04.678Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2023-11-11T20:36:04.680Z] --- End of stack trace from previous location ---
[2023-11-11T20:36:04.681Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
[2023-11-11T20:36:04.682Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2023-11-11T20:36:04.683Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 77
[2023-11-11T20:36:04.683Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.
[2023-11-11T20:41:17.520Z] Language Worker Process exited. Pid=37404.`

**Comment by Megasware128** [comment]
@jviau After some quick testing I noticed the issue happens with the [class-based model (Microsoft.DurableTask.Generators)](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview#source-generator-and-class-based-activities-and-orchestrations). I'm using the class-based model in my codebase and I see in the logging @alhell is too.

**Comment by shueseman** [comment]
I had this same issue with Microsoft.Azure.Functions.Worker.Sdk v1.16.2 and 1.16.4.  When I reverted to 1.15.1 then it worked.

If you want a reproducible example, build and debug Microsoft's own sample code:

https://github.com/microsoft/durabletask-dotnet/tree/main/samples/AzureFunctionsApp

And hit the StartHelloCitiesTyped endpoint.

**Comment by MrAntix** [comment]
> I had this same issue with Microsoft.Azure.Functions.Worker.Sdk v1.16.2 and 1.16.4. When I reverted to 1.15.1 then it worked.
> 
> If you want a reproducible example, build and debug Microsoft's own sample code (their sample uses 1.16.2):
> 
> https://github.com/microsoft/durabletask-dotnet/tree/main/samples/AzureFunctionsApp
> 
> And hit the StartHelloCitiesTyped endpoint.

Still seeing this on calling ```ScheduleNewOrchestrationInstanceAsync``` to a class based orchestrator on 1.17.2
reverting as above allows ```My:TaskOrchestrator<,>``` to run

I can provide a reproduction if you like, but its easy to find
