### ISSUE TITLE
Durable Function App:  SubOrchestration exceptions are lost.

### ISSUE THREAD

**Issue by johnthom** [Azure/azure-functions-durable-extension#2754]
Unlike calls to Activities, when an Orchestration calls a SubOrchestration and the SubOrchestration throws an exception the original details are not captured in the SubOrchestrationFailedException's  FailureDetails.  Instead, the FailureDetails are always null.

This fact makes it **impossible** for the calling orchestration to appropriately react to these scenarios.  Further, the original exception data is **lost**.  A custom workaround is needed to trap and capture any exceptions in the called orchestration and then pass that information back to the caller in some custom return object. This issue pretty much breaks the "scatter-gather" pattern unless some workaround is employed.  

The apparent source of this issue is that when the called orchestration fails the reason and failure details are not captured in the history table (even though the status shows 'failed') therefore this information will be missing when the SubOrchestrationFailedException is generated on the caller side of things.

**Expected behavior...
Like Activities, when an exception is thrown by a called suborchestration, the calling orchestration should receive a SubOrchestrationFailedException with a FailureDetails property containing the original exception's information.**

# Project details...
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated"

    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>

    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.7.2" />

# Code samples...

## Calling orchestration
```
        [Function(nameof(ParentOrchestration))]
        public static async Task ParentOrchestration(
          [OrchestrationTrigger] TaskOrchestrationContext context)
        {
            try
            {
                await context.CallSubOrchestratorAsync<string>(nameof(ChildOrchestration), "some input");
            }
            catch (Exception ex)
            {
                // This is a TaskFailedException with a SubOrchestrationFailedException inner exception.
                // Neither of these exceptions contains any information about the exception thrown by the 
                // the child orchestration (see image).
            }
        }
```
## Called orchestration
```
       [Function(nameof(ChildOrchestration))]
       public static void ChildOrchestration(
        [OrchestrationTrigger] TaskOrchestrationContext context)
       {
           var input = context.GetInput<string>();
           throw new Exception($"foobar from child orch: {input}");
       }
```
# Exception details...

```
Microsoft.DurableTask.TaskFailedException: Task 'ChildOrchestration' (#0) failed with an unhandled exception: Exception of type 'DurableTask.Core.Exceptions.SubOrchestrationFailedException' was thrown.
 ---> DurableTask.Core.Exceptions.SubOrchestrationFailedException: Exception of type 'DurableTask.Core.Exceptions.SubOrchestrationFailedException' was thrown.
   at DurableTask.Core.TaskOrchestrationContext.CreateSubOrchestrationInstanceCore[T](String name, String version, String instanceId, Object input, IDictionary`2 tags) in /_/src/DurableTask.Core/TaskOrchestrationContext.cs:line 191
   at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CallSubOrchestratorAsync[TResult](TaskName orchestratorName, Object input, TaskOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CallSubOrchestratorAsync[TResult](TaskName orchestratorName, Object input, TaskOptions options)
```

![exception_capture](https://github.com/Azure/durabletask/assets/162244914/dad023be-b1bf-4bd6-9a0d-e4765ec54c91)

**Comment by johnthom** [comment]
Correct.  I'm running this locally from a VisualStudio 2022 debug session using the storage emulator (azurite).
