### ISSUE TITLE
Durable Function - dotnet-isolated - Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")

### ISSUE THREAD

**Issue by gui28347** [Azure/azure-functions-durable-extension#2862]
- Trying to migrate a function running in-process to out-of-process dotnet-isolated 7.

- Same code works perfectly in in-process mode. Causing this exception in dotnet-isolated 7 after migrating the required code to run as dotnet-isolatd.

Stack: 

```LOG
[2023-11-18T04:13:01.793Z] Function 'MainActivityVM', Invocation id 'b81a7a79-437c-4d76-8ae2-64e48fbbb62e': An exception was thrown by the invocation.
[2023-11-18T04:13:01.794Z] Result: Function 'MainActivityVM', Invocation id 'b81a7a79-437c-4d76-8ae2-64e48fbbb62e': An exception was thrown by the invocation.
Exception: System.AggregateException: One or more errors occurred. (RunMain Exception: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
[2023-11-18T04:13:01.795Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.RaiseEventAsync(String instanceId, String eventName, Object eventPayload, CancellationToken cancellation)
[2023-11-18T04:13:01.795Z]    at TEST99.SampleFunction.RunMain(FunctionContext context, DurableTaskClient dclient, String vmname, String vmtype) in C:\temp\investigate\AzureAutomation_PersonalDOTNET8\TEST99\SampleFunction.cs:line 82)
[2023-11-18T04:13:01.796Z]  ---> System.Exception: RunMain Exception: Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
[2023-11-18T04:13:01.797Z]    at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.RaiseEventAsync(String instanceId, String eventName, Object eventPayload, CancellationToken cancellation)
[2023-11-18T04:13:01.797Z]    at TEST99.SampleFunction.RunMain(FunctionContext context, DurableTaskClient dclient, String vmname, String vmtype) in C:\temp\investigate\AzureAutomation_PersonalDOTNET8\TEST99\SampleFunction.cs:line 82
[2023-11-18T04:13:01.798Z]    at TEST99.SampleFunction.RunMain(FunctionContext context, DurableTaskClient dclient, String vmname, String vmtype) in C:\temp\investigate\AzureAutomation_PersonalDOTNET8\TEST99\SampleFunction.cs:line 93
[2023-11-18T04:13:01.799Z]    --- End of inner exception stack trace ---
```

```csharp
 [Function("MainActivityVM")]
 public static async Task<string> RunMain(
 [ActivityTrigger] FunctionContext context,
 [DurableClient] DurableTaskClient dclient, string vmname, string vmtype)
 {
     CustomStatusDurableFunction customStatus = new();
     try
     {
         int i = 0;
         while (true)
         {
             i++;
             customStatus.progressBar = i;
             await dclient.RaiseEventAsync(context.InvocationId, "StatusUpdate", customStatus); // line 82
             System.Threading.Thread.Sleep(2000);
             if (i == 100)
             {
                 break;
             }
         }
         return "OK";
     }
     catch (Exception ex)
     {
         throw new Exception($"RunMain Exception: {ex}"); // line 93
     }
 }
 ```

**Comment by MarcinJuraszek** [comment]
Any updates on this? This goes very much against what the document claims when it comes to external events:

> If there is no orchestration instance with the specified instance ID, the event message is discarded.
>
> from [Handling external events in Durable Functions (Azure Functions)
](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-external-events?tabs=csharp#send-events)

**Comment by MarcinJuraszek** [comment]
Looking more into this, I think I tracked it down to this:

```
        private bool CheckStatusBeforeRaiseEvent
            => this.durableTaskOptions.ThrowStatusExceptionsOnRaiseEvent ?? this.durabilityProvider.CheckStatusBeforeRaiseEvent;
```

Unless you set `ThrowStatusExceptionOnRaiseEvent` explicitly, it'll use whatever the durability provider says we should do, which for Azure Storage says you should check here: https://github.com/Azure/azure-functions-durable-extension/blob/d01791972a4b9f439b3e83f8a0e2f3e80a5b1914/src/WebJobs.Extensions.DurableTask/AzureStorageDurabilityProvider.cs#L59

And with that being `true` the `RaiseEventInternalAsync` will first check if the instance is up and healthy, and throw if not [here](https://github.com/Azure/azure-functions-durable-extension/blob/d01791972a4b9f439b3e83f8a0e2f3e80a5b1914/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L857). It's throwing `InvalidOperationException` but I guess for isolated gRPC gets in a way and ultimately we see `RpcException`.

Setting following in hosts.json makes the exception not happen:

```
{
    "version": "2.0",
    "extensions": {
        "durableTask": {
            "throwStatusExceptionsOnRaiseEvent": false
        }
    }
}
```

**Comment by Fazer01** [comment]
We are facing exaclty the same issue.

@MarcinJuraszek I think you are looking in the wrong repo for the `DurableClient`. For dotnet-isolated you need the `DurableTaskClient` implementation in the repository where I have posted this issue. (correct me if I'm wrong). 

In the previous 'dotnet in process' mode the RaiseEventAsync works like a charm and does the correct thing when a non-existent orchestratorid is used for `RaiseEventAsync`. 

As stated [here (IDurableOrchestrationClient)](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableOrchestrationClient.cs#L182) 
- `ArgumentException` when the instance id does not correspond to a valid orchestration instance.
- `InvalidOperationException` The orchestration instance with the provided instance id is not running. 
 

For the dotnet-isolated mode however, the documentation says it does silently eat the event that is raised, but in practice the `RpcException` is thrown... 

Just verified that `"throwStatusExceptionsOnRaiseEvent": false` in the host.json will not throw any exception at all...

**Comment by betim-raqi** [comment]
Same issue, RaiseEventAsync throws when instance not found so the documentation is incorrect

**Comment by alexander-lanin** [comment]
Same issue

**Comment by nytian** [comment]
The `throwStatusExceptionsOnRaiseEvent` setting currently only applies to `DurableClient` used in .NET in-proc and does not apply to `DurableTaskClient` at .NET isolated . I will open a PR soon to address this.

**Comment by nytian** [comment]
Hey @jcageman  I guess what you have is a different issue --when purging instance, it will return error when your instance doesn't exist or it doesn't complete yet(its status might be Pending, Running, or Suspended). We don't allow purge in-flight instances.

**Comment by jcageman** [comment]
> Hey [@jcageman](https://github.com/jcageman) I guess what you have is a different issue --when purging instance, it will return error when your instance doesn't exist or it doesn't complete yet(its status might be Pending, Running, or Suspended). We don't allow purge in-flight instances.

```
            var result = await client.PurgeAllInstancesAsync(new PurgeInstancesFilter(DateTime.MinValue, DateTime.Today.AddDays(-30),
                    new List<OrchestrationRuntimeStatus>
                    {
                        OrchestrationRuntimeStatus.Completed,
                        OrchestrationRuntimeStatus.Failed,
                        OrchestrationRuntimeStatus.Terminated
                    })
                );
```

That used to fail some versions ago due to MinValue or null value for the from parameter, don't know if it's still reproduceable today. the workaround was not setting DateTime to MinValue.. which used to work in inprocess. The Grpc exception didn't give any clue what was going wrong.

**Comment by nytian** [comment]
@jcageman oh yes you are right. The exception returned by PurgeInstanceAsync is not clear, and [this PR](https://github.com/Azure/azure-functions-durable-extension/pull/3106)  helped improved the exception returned from it. which will also be included in our next release as PR metioned above.  And I will update this thread once the release is out.

**Comment by nytian** [comment]
Close as completed.

**Comment by nytian** [comment]
Hey, this change has been included in this release. NuGet link is also included in this release notes. Check[ here ](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.4.0-worker-extension)
