### ISSUE TITLE
Issue calling the durable function

### ISSUE THREAD

**Issue by DawichR** [Azure/azure-functions-durable-extension#2931]
Hi all, I started to work with Durable Function to solve an issue with timeout.. 

```
[2024-10-09T12:36:57.829Z] Function 'GetTransactionByTypeToDataLake_HttpStart', Invocation id 'd9d85b85-2f74-4212-9a6f-46b69426a9c5': An exception was thrown by the invocation.
[2024-10-09T12:36:57.829Z] Result: Function 'GetTransactionByTypeToDataLake_HttpStart', Invocation id 'd9d85b85-2f74-4212-9a6f-46b69426a9c5': An exception was thrown by the invocation.
Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.DurableTask.Client.DurableTaskClient' while attempting to activate 'AlgOperations.Functions.Functions.Transaction.Orchestrator.DurableTransactionFunction'.
[2024-10-09T12:36:57.829Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2024-10-09T12:36:57.830Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2024-10-09T12:36:57.830Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2024-10-09T12:36:57.830Z]    at AlgOperations.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Functions\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 68
[2024-10-09T12:36:57.831Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-10-09T12:36:57.831Z]    at AlgOperations.Core.Logger.LoggingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Core\Logger\LoggingMiddleware.cs:line 21
[2024-10-09T12:36:57.831Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
Stack:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2024-10-09T12:36:57.832Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2024-10-09T12:36:57.832Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2024-10-09T12:36:57.832Z]    at AlgOperations.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Functions\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 68
[2024-10-09T12:36:57.833Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-10-09T12:36:57.833Z]    at AlgOperations.Core.Logger.LoggingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Core\Logger\LoggingMiddleware.cs:line 21
[2024-10-09T12:36:57.833Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89.
[2024-10-09T12:36:57.846Z] Executed 'Functions.GetTransactionByTypeToDataLake_HttpStart' (Failed, Id=d9d85b85-2f74-4212-9a6f-46b69426a9c5, Duration=130ms)
[2024-10-09T12:36:57.846Z] System.Private.CoreLib: Exception while executing function: Functions.GetTransactionByTypeToDataLake_HttpStart. System.Private.CoreLib: Result: Failure
Exception: System.InvalidOperationException: Unable to resolve service for type 'Microsoft.DurableTask.Client.DurableTaskClient' while attempting to activate 'AlgOperations.Functions.Functions.Transaction.Orchestrator.DurableTransactionFunction'.
[2024-10-09T12:36:57.846Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2024-10-09T12:36:57.847Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2024-10-09T12:36:57.847Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2024-10-09T12:36:57.847Z]    at AlgOperations.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Functions\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 68
[2024-10-09T12:36:57.848Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-10-09T12:36:57.848Z]    at AlgOperations.Core.Logger.LoggingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Core\Logger\LoggingMiddleware.cs:line 21
[2024-10-09T12:36:57.848Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-10-09T12:36:57.849Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
Stack:    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2024-10-09T12:36:57.849Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2024-10-09T12:36:57.849Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2024-10-09T12:36:57.850Z]    at AlgOperations.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Functions\obj\Debug\net8.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 68
[2024-10-09T12:36:57.850Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2024-10-09T12:36:57.850Z]    at AlgOperations.Core.Logger.LoggingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in E:\Novatech\Repositorios\magaya-azure-function\AlgOperations.Core\Logger\LoggingMiddleware.cs:line 21
[2024-10-09T12:36:57.851Z]    at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 89
[2024-10-09T12:36:57.851Z]    at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88.`
```

I'm getting this after make a call to my function which I think is defined as the examples.

program.cs
```csharp
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(worker =>
    {
        new DurableTaskExtensionStartup().Configure(worker);
        worker.UseMiddleware<LoggingMiddleware>();
    })
```

function:
```csharp
    public class DurableTransactionFunction
    {
        private readonly DurableTaskClient _durableTaskClient;
        private readonly ILogger _logger;

        public DurableTransactionFunction(DurableTaskClient durableTaskClient, ILoggerFactory loggerFactory)
        {
            _durableTaskClient = durableTaskClient;
            _logger = loggerFactory.CreateLogger<DurableTransactionFunction>();
        }

        [Function("GetTransactionByTypeToDataLake_HttpStart")]
        public async Task<HttpResponseData> HttpStart(
            [HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequestData req,
            FunctionContext executionContext)
        {
            ProcessDataParamsInputDto<GetTransactionByTypeToDataLakeParamsInputDto> processInputParams = ProcessDataParamsInputDto<GetTransactionByTypeToDataLakeParamsInputDto>.GetFromHttpRequest(req);

            string instanceId = await _durableTaskClient.ScheduleNewOrchestrationInstanceAsync("GetTransactionByTypeToDataLakeOrchestrator", processInputParams);

            HttpResponseData response = req.CreateResponse(HttpStatusCode.OK);
            await response.WriteStringAsync($"Orchestration started with ID: {instanceId}");

            return response;
        }
    }
```

Btw those are the references packages that my project has:
```xml
<ItemGroup>
   <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
   <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
   <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.22.0" />
   <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.0" />
   <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
   <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" />
   <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
</ItemGroup>
```
Any idea what is going on?

**Comment by cgillum** [comment]
Try removing this line from Program.cs:

```csharp
        new DurableTaskExtensionStartup().Configure(worker);
```

This shouldn't be necessary, and it's unclear what the potential side effects of adding it might be.
