### ISSUE TITLE
Exception after migration to isolated model

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/azure-functions-durable-extension#2952]
Running into the following exception after migrating Azure Function into isolated worker model. What could be causing this?
```
    Exception while executing function: Functions.OrchestratorFunction Result: Failure

  Exception: System.InvalidOperationException: An ExecutionStarted event is required.

       at DurableTask.Core.OrchestrationRuntimeState.GetExecutionStartedEventOrThrow() in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 210
       at DurableTask.Core.OrchestrationRuntimeState.get_Name() in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 140
       at Microsoft.DurableTask.Worker.Grpc.GrpcOrchestrationRunner.LoadAndRun(String encodedOrchestratorRequest, ITaskOrchestrator implementation, IServiceProvider services)
       at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\Worker.Extensions.DurableTask\DurableTaskFunctionsMiddleware.cs:line 58
       at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91
       at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88
    Stack:    at DurableTask.Core.OrchestrationRuntimeState.GetExecutionStartedEventOrThrow() in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 210
       at DurableTask.Core.OrchestrationRuntimeState.get_Name() in /_/src/DurableTask.Core/OrchestrationRuntimeState.cs:line 140
       at Microsoft.DurableTask.Worker.Grpc.GrpcOrchestrationRunner.LoadAndRun(String encodedOrchestratorRequest, ITaskOrchestrator implementation, IServiceProvider services)
       at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.DurableTaskFunctionsMiddleware.RunOrchestrationAsync(FunctionContext context, BindingMetadata triggerBinding, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\Worker.Extensions.DurableTask\DurableTaskFunctionsMiddleware.cs:line 58
       at Microsoft.Azure.Functions.Worker.FunctionsApplication.InvokeFunctionAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\FunctionsApplication.cs:line 91
       at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a\_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 88 
```

**Comment by cgillum** [comment]
@lipalath-ms a few questions for you:

1. what nuget package versions is your app using?
2. do you have any application settings or environment variables that could be affecting these settings?
3. do you have a minimal reproducer project that you can share for us to use for debugging?

**Comment by lipalath-ms** [comment]
@cgillum Thank you! Figured out that it was due to AzureFunctionsJobHost:extensions:durableTask:extendedSessionsEnabled property set to True for the azure function. Is there an alternate property that could be assigned for azure functions migrated to .NET 8 isolated model?

**Comment by cgillum** [comment]
Glad we were able to quickly identify the cause!

> Is there an alternate property that could be assigned for azure functions migrated to .NET 8 isolated model?

Unfortunately, not at this time. The `extendedSessionsEnabled` property only works for in-proc apps. We don't yet have a way to enable this optimization in out-of-proc scenarios. It shouldn't be a blocker since it's just an optimization, unless your app is doing things like extreme fan-outs or running orchestrations that call multiple activities with large input or output payloads.

**Comment by lipalath-ms** [comment]
@cgillum  Our functions are running orchestrations that call multiple activities with large input and output payloads.

**Comment by lipalath-ms** [comment]
This is the exception I'm seeing now:

Caught unexpected exception in Part# 3, marking sync job as errored. Exception:
Microsoft.DurableTask.TaskFailedException: Task 'SubOrchestratorFunction' (#1) failed with an unhandled exception: Non-Deterministic workflow detected: A previous execution of this orchestration scheduled an activity task with sequence number 7 named 'GeCountFunction', but the current orchestration replay instead scheduled an activity task named 'UpdaterFunction' with this sequence number.  Was a change made to the orchestrator code after this instance had already started running?
   at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CallSubOrchestratorAsync[TResult](TaskName orchestratorName, Object input, TaskOptions options)
   at OrchestratorFunction.RunOrchestratorAsync(TaskOrchestrationContext context)

**Comment by cgillum** [comment]
@lipalath-ms can you create a new issue for this? Having `extendedSessionsEnabled` set to `false` is the only supported configuration for .NET Isolated. Non-determinism errors shouldn't be related to turning off this setting.
