### ISSUE TITLE
Azure Deployment - Repeated Grpc.Core.RpcException: Status(StatusCode="XXX", Detail="Error connecting to subchannel.", "System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions"

### ISSUE THREAD

**Issue by dfaivre** [Azure/azure-functions-durable-extension#2970]
### Description
We get repeated intermittent GRPC RpcExceptions in our deployed durable functions app, seemingly when it's trying to connect to the side car?

### Expected behavior
A retry, or a reliable GRPC connection to the sidecar

### Actual behavior
Randomly fails

### Relevant source code snippets
```
Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error connecting to subchannel.", DebugException="System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions.")
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.SocketConnectivitySubchannelTransport.TryConnectAsync(ConnectContext context)
   --- End of inner exception stack trace ---
   at Grpc.Net.Client.Balancer.Internal.ConnectionManager.PickAsync(PickContext context, Boolean waitForReady, CancellationToken cancellationToken)
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)
   at Microsoft.DurableTask.Client.Grpc.GrpcDurableTaskClient.GetInstancesAsync(String instanceId, Boolean getInputsAndOutputs, CancellationToken cancellation)
[internal code]...
--- End of stack trace from previous location ---
[internal code]...
```

### Known workarounds
I think I'd basically need to create a custom `DurableTaskClient` that proxied all the calls wrapped in retry logic?

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.7, Microsoft.Azure.Functions.Worker 1.23.0, App Setting FUNCTIONS_EXTENSION_VERSION = ~4
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: .net 8.0 isolated (c#)

### Screenshots
None

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 2024-11-19T19:13:48.0385569Z
- **Function App name**: (please email me if you need/want it)
- **Function name(s)**:  Ops_OpInputPipelineStarterFunction
- **Azure region**: Central
- **Orchestration instance ID(s)**: none (it's trying to start an orchestration)
- **Azure storage account name**:  (please email me if you need/want it)
- **Invocation ID**: 023972b3-9b18-449c-9562-83abf5ae465e
- **HostInstance ID**: cdf5caea-5b96-4052-ac69-46738ab06aa8
- **SDK Version**: azurefunctions: 4.1036.3.23284
- **Operation ID**: 6832f51c05c0bd19c117b7a64ce4bb93
- **Application ID**: d430d61a-6e7c-4d9d-8a92-eb7f7dd63011

**Comment by cgillum** [comment]
gRPC connection errors are generally not expected unless one of either the host process (which I think you're referring to as the sidecar) or the worker process crashes. Can you check to see if the Azure Functions host process might be recycling?

**Comment by dfaivre** [comment]
Thanks Chris! I'm not entirely sure how to check if the host process is recycling?

It might make sense that the host process is dying, as once it starts throwing the errors, the only way to clear them is to restart the functions app. So my retry work around probably wouldn't work...

**Comment by cgillum** [comment]
@nytian mentioned a similar case to me yesterday. We suspect that this kind of problem might happen if the host process recycles and the worker process doesn't, in which case the host process starts listening on a different port than what the worker process is expecting.

I was able to find your app using the information you provided (thanks!) and while it's not easy for me to know whether there's a host restart (I can see host starting, but not necessarily stopping), I do see a couple of cases where there was at least two host startup events on the same VM within a 10 minute window.

RoleInstance | TIMESTAMP | count_ | min_TIMESTAMP | max_TIMESTAMP
-- | -- | -- | -- | --
pd0MediumDedicatedWebWorkerRole_IN_15289 | 2024-11-18 23:40:00.0000000 | 2 | 2024-11-18 23:40:11.2751149 | 2024-11-18 23:47:38.5501626
pd0MediumDedicatedWebWorkerRole_IN_15188 | 2024-11-18 23:40:00.0000000 | 2 | 2024-11-18 23:41:12.6843653 | 2024-11-18 23:48:30.2643996

They didn't quite match up with the timestamp you provided, however, so I'm not sure if these are related. By the way, are you running on the Consumption plan? It seems like your app is changing VMs pretty regularly.

If you haven't done so already, it might be worth opening an Azure Support request so that we can get more experts looking into this.

**Comment by dfaivre** [comment]
@cgillum - thanks for taking the time to look into all of this. 

- We're on the Elastic Premium plan - so in theory it behaves like consumption....
- Looks like there was a small spike of errors around: 2024-11-18T23:50:47.2385233Z- so pretty close to what you were seeing.
- I have a support request opened on 11/7/2024 and have sent them this GitHub issue. I opened this because they seemed to be having a hard time making any progress... :) **Support request ID: 2411070040008596**

**Comment by dfaivre** [comment]
cross ref: https://github.com/microsoft/durabletask-dotnet/issues/353

**Comment by nytian** [comment]
@dfaivre  Hey thanks for opening the ticket. Do you have more recent app with this issue in recent 6 month? So that I can check the logs.

**Comment by dfaivre** [comment]
@nytian - thanks for checking in! This week actually I'm pretty sure we're fighting with the same Azure (Durable?) Functions runtime dying and not being able to restart, which then basically takes down our entire functions app. It's a RpcException - Http Timeout error this time though. If you have any advice on where best to file the ticket beyond this issue, I'd appreciate it!

------

We have a service bus function that listens for a service bus message, and starts a durable function orchestration. It will, maybe a couple times a die, start repeatedly failing with timeout RpcExceptions, assumedly when calling the underlying functions runtime. From the Azure troubleshooting, it looks like there are "Port 4001 in use errors" that would also point to the Azure Functions runtime failing. The only way to fix it is to restart the entire Functions App.

Time period: 2025-10-23 – 8:15 AM \- 3:00PM US/Chicago/Central Time

In the logging below \- we restarted the Functions App at \~8:50AM and \~3:00PM. The auto scale instance spikes are, I assume, the Service Bus functions starting a bunch of Durable Orchestrations.

It seems like we scale down to one auto scale instance, that instance's functions runtime dies and can't restart, then our functions become stuck until we restart. When multiple instances are running, it seems more robust, since as long as there is at least one instance with the functions runtime healthy, it can push through Orchstration starts.

## Azure Errors Report
*Time in UTC*  
<img width="2020" height="476" alt="Image" src="https://github.com/user-attachments/assets/de541456-22a4-4a0e-b96b-540833a396ef" />

## Timeout Error History
*Time in Central*  
<img width="2024" height="1154" alt="Image" src="https://github.com/user-attachments/assets/2faec288-273d-49fb-ac5c-84b5395326e4" />

## Function Auto Scale Instance Count
*Time in Central Time*  
<img width="2048" height="694" alt="Image" src="https://github.com/user-attachments/assets/ad07ae0d-2178-41c9-a941-9e9ad5b7a814" />

**Comment by dfaivre** [comment]
I also opened a Microsoft Q & A - since that's what the Azure troubleshooter told me to do: https://learn.microsoft.com/en-us/answers/questions/5596588/service-bus-azure-function-repeatedly-fails-with-t

**Comment by nytian** [comment]
Thanks for the info @dfaivre  I am taking a look and will update here soon.
