### ISSUE TITLE
Activity Failures should return activity's exception, not a TaskFailedException

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#314]
I tried a feature of Custom RetryOption. However, I found an issue.

1.  Exception Type is NOT FunctionFailedException

I write code like following. 

```
            var option = new RetryOptions(System.TimeSpan.FromSeconds(5), 3);
                option.Handle = (e) => {                
                    if (!context.IsReplaying)
                    {
                        log.Info("******* Call back called");
                        log.Info(e.ToString());
                        log.Info("*****");
                    }
                    return true; };
                outputs.Add(await context.CallActivityWithRetryAsync<string>("DurableSpike_RetryIt", option, "RetryIt"));
                     :

        [FunctionName("DurableSpike_RetryIt")]
        public static async Task<string> RetryItAsync([ActivityTrigger] string name, TraceWriter log)
        {
            log.Info("Activity RetryItAsync has been called");
            throw new System.Exception("This is execption from Activity");
        }
```

I expect the lambda's parameter for the RetryOption.Handle should be FunctionFailedException. However it is TaskFailedException. I use Durable Functions v1.4.1

```
[17/05/2018 05:28:19] ******* Call back called
[17/05/2018 05:28:19] DurableTask.Core.Exceptions.TaskFailedException: Exception while executing function: DurableSpike_RetryIt
[17/05/2018 05:28:19]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[17/05/2018 05:28:19]    at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskInternal>d__14.MoveNext()
[17/05/2018 05:28:19] --- End of stack trace from previous location where exception was thrown ---
[17/05/2018 05:28:19]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[17/05/2018 05:28:19]    at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskToWorker>d__13`1.MoveNext()
[17/05/2018 05:28:19] --- End of stack trace from previous location where exception was thrown ---
[17/05/2018 05:28:19]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[17/05/2018 05:28:19]    at DurableTask.Core.TaskOrchestrationContext.<ScheduleTask>d__12`1.MoveNext()
[17/05/2018 05:28:19] --- End of stack trace from previous location where exception was thrown ---
[17/05/2018 05:28:19]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[17/05/2018 05:28:19]    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
[17/05/2018 05:28:19]    at DurableTask.Core.RetryInterceptor`1.<Invoke>d__4.MoveNext()
[17/05/2018 05:28:19] *****
```

To Reproduce, you can use this code. 

```
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;

namespace DurableFunctionSpike
{
    public static class DurableSpike
    {
        [FunctionName("DurableSpike")]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext context, TraceWriter log)
        {
            var outputs = new List<string>();

            // Replace "hello" with the name of your Durable Activity Function.
            outputs.Add(await context.CallActivityAsync<string>("DurableSpike_Hello", "Tokyo"));
            outputs.Add(await context.CallActivityAsync<string>("DurableSpike_Hello", "Seattle"));

            outputs.Add(await context.CallActivityAsync<string>("DurableSpike_Hello", "London"));


            var option = new RetryOptions(System.TimeSpan.FromSeconds(5), 3);
                option.Handle = (e) => {
                    if (!context.IsReplaying)
                    {
                        log.Info("******* Call back called");
                        log.Info(e.ToString());
                        log.Info("*****");
                    }
                    return true; };

            outputs.Add(await context.CallActivityWithRetryAsync<string>("DurableSpike_RetryIt", option, "RetryIt"));
            // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
            return outputs;
        }

        [FunctionName("DurableSpike_Hello")]
        public static string SayHello([ActivityTrigger] string name, TraceWriter log)
        {
            log.Info($"Saying hello to {name}.");
            return $"Hello {name}!";
        }
        
        [FunctionName("DurableSpike_RetryIt")]
        public static async Task<string> RetryItAsync([ActivityTrigger] string name, TraceWriter log)
        {
            log.Info("Activity RetryItAsync has been called");
            throw new System.Exception("This is execption from Activity");
            //while(true)
            //{
            //    await Task.Delay(10 * 1000);
            //}
            //return "Never finish";

        }

        [FunctionName("DurableSpike_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
            [OrchestrationClient]DurableOrchestrationClient starter,
            TraceWriter log)
        {
            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync("DurableSpike", null);

            log.Info($"Started orchestration with ID = '{instanceId}'.");

            return starter.CreateCheckStatusResponse(req, instanceId);
        }
    }
}
```

**Comment by shibayan** [comment]
@TsuyoshiUshio This will be the intended behavior. `RetryOptions#Handle` is only a wrapper around DurableTask.Core.
(`FunctionFailedException` is just a change of the contents of `TaskFailedException`.)

However, I feel some discomfort. I'd like to receive exceptions that actually occurred rather than DurableTask exception types.

#### Example

```csharp
var option = new RetryOptions(System.TimeSpan.FromSeconds(5), 3)
{
    // Dislike it
    // ex is TaskFailedException or SubOrchestrationFailedException
    //Handle = (ex.InnerException is HttpRequestException || ex.InnerException is SocketException)

    // Like it
    Handle = (ex is HttpRequestException || ex is SocketException)
};
```

Since it is a retrying process, I do not feel the necessity of wrapping with another Exception.
Thanks.

**Comment by TsuyoshiUshio** [comment]
Hi @shibayan 
Thank you for the comment.  I can't remember why I thought something like this. Maybe documentation at that time? Anyway, we might be able to close this issue. :)  Also your recommendation is totally make sense. Currently, RetryIntercepter is executed on the OrchestrationContext for example. Activity and Orchestration Dispatcher throws TaskFailedException. So the RetryIntercepter accept the TaskFailedException. We might can change that part, however, it can be an breaking change. What do you think @cgillum ?

**Comment by shibayan** [comment]
In my opinion, it is possible to support by adding a custom implementation of `RetryOptions#Handle` without touching the DurableTask.Core.

https://github.com/Azure/azure-functions-durable-extension/blob/11463dd93da837d790adeeecf7dda61c2c94b80d/src/WebJobs.Extensions.DurableTask/RetryOptions.cs#L95-L99

I want to make an optimal retry for each exception :)

**Comment by TsuyoshiUshio** [comment]
It much better than I wrote! Thank you. However, it still introduce the behavior change for the Durable Functions's side. We have a good chance to have a breaking change so, Let's wait for the Chris's reaction. :)

**Comment by cgillum** [comment]
Yes, this would be a breaking change. That's okay though since we are starting to plan for the 2.0 release, which is a breaking change release. We can include this change as part of 2.0.

**Comment by mcgear** [comment]
Hello, this is a little off topic, but not entirely...  I am wondering why only support exceptions in terms of retry?  It would be nice to have a handle for an exception and a handle for the actual return type...  Say the Activity actually wants to intelligently handle exceptions and return some type of response and based on that response execute or don't execute retry?

**Comment by cgillum** [comment]
We had a similar request for something like this recently. Take a look at [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/1185) and feel free to add comments.

**Comment by ConnorMcMahon** [comment]
This should be tracked alongside of #313, wrapped behind a feature flag.

**Comment by biltongza** [comment]
Bump on this. It's 2025 and we are 2 major versions later, and I still get absolutely useless stack traces from durable functions.

Example:
```
[2025-08-26T12:50:26.617Z] An error occurred while executing the orchestrator function 'OrchestrateSyncServiceConnectionUsages'.
[2025-08-26T12:50:26.621Z] Result: An error occurred while executing the orchestrator function 'OrchestrateSyncServiceConnectionUsages'.
Exception: System.AggregateException: One or more errors occurred. (Task 'GetServiceConnectionAuthorisations' (#1076) failed with an unhandled exception: Exception while executing function: Functions.GetServiceConnectionAuthorisations)
[2025-08-26T12:50:26.625Z]  ---> Microsoft.DurableTask.TaskFailedException: Task 'GetServiceConnectionAuthorisations' (#1076) failed with an unhandled exception: Exception while executing function: Functions.GetServiceConnectionAuthorisations
[2025-08-26T12:50:26.627Z]  ---> DurableTask.Core.Exceptions.TaskFailedException: Exception of type 'DurableTask.Core.Exceptions.TaskFailedException' was thrown.
[2025-08-26T12:50:26.629Z]    at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskInternal(String name, String version, String taskList, Type resultType, ScheduleTaskOptions options, Object[] parameters) in /_/src/DurableTask.Core/TaskOrchestrationContext.cs:line 143
[2025-08-26T12:50:26.632Z]    at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskToWorker[TResult](String name, String version, String taskList, ScheduleTaskOptions options, Object[] parameters) in /_/src/DurableTask.Core/TaskOrchestrationContext.cs:line 107
[2025-08-26T12:50:26.636Z]    at DurableTask.Core.TaskOrchestrationContext.ScheduleTask[TResult](String name, String version, ScheduleTaskOptions options, Object[] parameters)
[2025-08-26T12:50:26.639Z]    at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CallActivityAsync[T](TaskName name, Object input, TaskOptions options)
[2025-08-26T12:50:26.641Z]    --- End of inner exception stack trace ---
[2025-08-26T12:50:26.643Z]    at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CallActivityAsync[T](TaskName name, Object input, TaskOptions options)
[2025-08-26T12:50:26.644Z]    at Azdo.Graph.Functions.ServiceConnections.SyncServiceConnectionUsages.OrchestrateSyncServiceConnectionUsages(TaskOrchestrationContext orchestrationContext) in D:\repos\METIS-metrics\src\Azdo.Graph\Azdo.Graph.Functions\ServiceConnections\SyncServiceConnectionUsages.cs:line 42
[2025-08-26T12:50:26.646Z]    at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 22
[2025-08-26T12:50:26.648Z]    --- End of inner exception stack trace ---
[2025-08-26T12:50:26.649Z]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2025-08-26T12:50:26.652Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2025-08-26T12:50:26.654Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2025-08-26T12:50:26.656Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2025-08-26T12:50:26.657Z] --- End of stack trace from previous location ---
[2025-08-26T12:50:26.659Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2025-08-26T12:50:26.661Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2025-08-26T12:50:26.662Z] --- End of stack trace from previous location ---
[2025-08-26T12:50:26.664Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 49
[2025-08-26T12:50:26.666Z]    at Azdo.Graph.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\repos\METIS-metrics\src\Azdo.Graph\Azdo.Graph.Functions\obj\Debug\net9.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 258
[2025-08-26T12:50:26.668Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2025-08-26T12:50:26.671Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /_/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
[2025-08-26T12:50:26.675Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.EnsureSynchronousExecution(FunctionContext functionContext, FunctionExecutionDelegate next, FunctionsOrchestrationContext orchestrationContext) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 81
[2025-08-26T12:50:26.678Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.RunAsync(TaskOrchestrationContext context, Object input) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 51
Stack:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[2025-08-26T12:50:26.682Z]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[2025-08-26T12:50:26.686Z]    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
[2025-08-26T12:50:26.688Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2025-08-26T12:50:26.690Z] --- End of stack trace from previous location ---
[2025-08-26T12:50:26.692Z]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[2025-08-26T12:50:26.695Z]    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
[2025-08-26T12:50:26.698Z] --- End of stack trace from previous location ---
[2025-08-26T12:50:26.700Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 49
[2025-08-26T12:50:26.703Z]    at Azdo.Graph.Functions.DirectFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\repos\METIS-metrics\src\Azdo.Graph\Azdo.Graph.Functions\obj\Debug\net9.0\Microsoft.Azure.Functions.Worker.Sdk.Generators\Microsoft.Azure.Functions.Worker.Sdk.Generators.FunctionExecutorGenerator\GeneratedFunctionExecutor.g.cs:line 258
[2025-08-26T12:50:26.707Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2025-08-26T12:50:26.710Z]    at Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore.FunctionsHttpProxyingMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in /_/extensions/Worker.Extensions.Http.AspNetCore/src/FunctionsMiddleware/FunctionsHttpProxyingMiddleware.cs:line 38
[2025-08-26T12:50:26.713Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.EnsureSynchronousExecution(FunctionContext functionContext, FunctionExecutionDelegate next, FunctionsOrchestrationContext orchestrationContext) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 81
[2025-08-26T12:50:26.718Z]    at Microsoft.Azure.Functions.Worker.Extensions.DurableTask.FunctionsOrchestrator.RunAsync(TaskOrchestrationContext context, Object input) in /_/src/Worker.Extensions.DurableTask/FunctionsOrchestrator.cs:line 51.
[2025-08-26T12:50:26.771Z] Executed 'Functions.OrchestrateSyncServiceConnectionUsages' (Failed, Id=55aea8cf-3683-49b0-b9fa-17ad95792ede, Duration=1589ms)
[2025-08-26T12:50:26.775Z] System.Private.CoreLib: Exception while executing function: Functions.OrchestrateSyncServiceConnectionUsages. Microsoft.Azure.WebJobs.Extensions.DurableTask: One or more errors occurred. (Task 'GetServiceConnectionAuthorisations' (#1076) failed with an unhandled exception: Exception while executing function: Functions.GetServiceConnectionAuthorisations).
[2025-08-26T12:50:26.785Z] a953782e3d0f4393968d3882238db4d3: Function 'OrchestrateSyncServiceConnectionUsages (Orchestrator)' failed with an error. Reason: DurableTask.Core.Exceptions.OrchestrationFailureException
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.OutOfProcMiddleware.<>c__DisplayClass10_0.<<CallOrchestratorAsync>b__0>d.MoveNext() in /_/src/WebJobs.Extensions.DurableTask/OutOfProcMiddleware.cs:line 150
[2025-08-26T12:50:26.788Z] --- End of stack trace from previous location ---
[2025-08-26T12:50:26.791Z]    at Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.<>c__DisplayClass7_0.<<TryExecuteAsync>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs:line 51
[2025-08-26T12:50:26.795Z] --- End of stack trace from previous location ---
[2025-08-26T12:50:26.797Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 581
[2025-08-26T12:50:26.799Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 527
[2025-08-26T12:50:26.801Z]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 306. IsReplay: False. State: Failed. RuntimeStatus: Failed. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 3.4.1. SequenceNumber: 7234. TaskEventId: -1
```

This gives me **zero** useful information for debugging.

**Comment by YunchuWang** [comment]
Closing this as not planned for the legacy in-process API.

The literal request—passing the original live activity exception object to `RetryOptions.Handle` instead of `DurableTask.Core.Exceptions.TaskFailedException`—cannot be implemented only in this extension without changing the Durable Task Framework contract. Activity failures cross a durable serialization/replay boundary, and `RetryOptions.Handle` is invoked by DTFx before the Functions extension converts a final failure into `FunctionFailedException`. Changing that parameter now would be a breaking change.

The current .NET isolated API addresses the underlying scenario without reconstructing arbitrary exception objects: retry handlers can inspect `RetryContext.LastFailure`, including `TaskFailureDetails.ErrorType`, `Message`, `InnerFailure`, and `IsCausedBy<T>()`, via `TaskOptions.FromRetryHandler(...)`. The `TaskFailedException` wrapper remains intentional, while the structured failure details preserve the information needed for selective retry logic.

If a future DTFx major version wants different exception semantics, that should be proposed as an explicit breaking-design item in `Azure/durabletask`, with compatibility and cross-process serialization behavior defined there.
