### ISSUE TITLE
DurableTask 1.5.0 + Functions v2: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0

### ISSUE THREAD

**Issue by paulceli** [Azure/azure-functions-durable-extension#359]
I updated to 1.5.0. I had the following error while building at first:

```
Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
 sebp.Mobile.TestApp.Func (>= 1.0.0) -> Microsoft.Azure.WebJobs.Extensions.DurableTask (>= 1.5.0) -> DurableTask.AzureStorage.Private (>= 1.2.4) -> Newtonsoft.Json (>= 11.0.2) 
 sebp.Mobile.TestApp.Func (>= 1.0.0) -> Microsoft.NET.Sdk.Functions (>= 1.0.13) -> Newtonsoft.Json (>= 10.0.3).
```
So I added the latest version of Nuget 'Newtonsoft.Json'. Now it builds OK but I get the following errors while starting the app:

```
                  %%%%%%
                 %%%%%%
            @   %%%%%%    @
          @@   %%%%%%      @@
       @@@    %%%%%%%%%%%    @@@
     @@      %%%%%%%%%%        @@
       @@         %%%%       @@
         @@      %%%       @@
           @@    %%      @@
                %%
                %

Hosting environment: Production
Content root path: /Users/paulceli/Sources/MobileBanking_UITests/sebp.Mobile.TestApp.Func/bin/Debug/netstandard2.0
Now listening on: http://localhost:7071
Application started. Press Ctrl+C to shut down.
[06/22/2018 12:10:39] Reading host configuration file '/Users/paulceli/Sources/MobileBanking_UITests/sebp.Mobile.TestApp.Func/bin/Debug/netstandard2.0/host.json'
[06/22/2018 12:10:39] Host configuration file read:
[06/22/2018 12:10:39] {}
[06/22/2018 12:10:39] Starting Host (HostId=ls888-1606649231, InstanceId=c70bb3a3-06be-436c-8c0d-7c467deea131, Version=2.0.11651.0, ProcessId=2429, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)
[06/22/2018 12:10:39] Unable to configure java worker. Could not find JAVA_HOME app setting.
[06/22/2018 12:10:39] 
[06/22/2018 12:10:39] Could not configure language worker Java.
[06/22/2018 12:10:39] 
[06/22/2018 12:10:40] Loaded custom extension: DurableTaskExtension from 'referenced by: Method='sebp.Mobile.TestApp.Func.CompareTestRuns.HttpStart', Parameter='starter'.'
Warning: Only got partial types from assembly: Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
[06/22/2018 12:10:41] A ScriptHost error has occurred
[06/22/2018 12:10:41] Microsoft.Azure.WebJobs.Extensions.DurableTask: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
[06/22/2018 12:10:41] Stopping Host
```

😢
help thanks

**Comment by cgillum** [comment]
Just to provide some context, this should only impact precompiled projects which target Azure Functions v2.

You can workaround the build error by explicitly adding a reference to **Newtonsoft.Json** in your .csproj file, as the build error message suggests:

```xml
<PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
```

This happens because [Microsoft.NET.Sdk.Functions v1.0.13](https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.13) has not been updated yet to match the **Newtonsoft.Json** version which is used in public Azure. The Azure Functions team is aware of this issue and will be releasing an update soon.

I'm not sure what would be causing your runtime error. Some things to check:

1. Are you targeting the correct version of Newtonsoft.Json?
2. Are you running the latest version of the Azure Functions tools and/or the latest version of the Azure Functions CLI?

**Comment by paulceli** [comment]
Hey,
Yes, I have added the correct reference to 11.0.2 Newtonsoft.Json package.
This solved the compilation error.

This ticket is more about the runtime error:

```
[06/22/2018 12:10:40] Loaded custom extension: DurableTaskExtension from 'referenced by: Method='sebp.Mobile.TestApp.Func.CompareTestRuns.HttpStart', Parameter='starter'.'
Warning: Only got partial types from assembly: Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null
Exception message: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Microsoft.Azure.WebJobs.Host.Indexers.DefaultTypeLocator.FindTypes(Assembly assembly, IEnumerable`1 extensionAssemblies) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\DefaultTypeLocator.cs:line 120
[06/22/2018 12:10:41] A ScriptHost error has occurred
[06/22/2018 12:10:41] Microsoft.Azure.WebJobs.Extensions.DurableTask: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
```

Could it be a hard coded reference somewhere that would not resolve on Mac?


I'm using Visual Studio Mac on the beta channel to get the new feature that allow to publish functions to azure. Here is the version :

> Visual Studio Community 2017 for Mac (Preview)
> Version 7.6 Preview (7.6 build 1773)

About your question on the version of the azure tools / Functions CLI I'm using.. I'm not sure how I can verify this. In the previous log I posted, it mentions this :

> Starting Host (HostId=ls888-1606649231, InstanceId=c70bb3a3-06be-436c-8c0d-7c467deea131, Version=2.0.11651.0, ProcessId=2429, AppDomainId=1, Debug=False, ConsecutiveErrors=0, StartupCount=1, FunctionsExtensionVersion=)

The same project was working OK with version 1.4.1.


Thanks a lot

**Comment by cgillum** [comment]
@paulceli Thanks for these details. My guess is that the Functions CLI version used by Visual Studio for Mac has not been updated to match what is currently deployed to Azure. Functions v2 is evolving pretty rapidly as it marches towards GA, so certain parts are going to be behind.

FYI @jeffhollan in case we want to follow up with the VS for Mac team on getting up-to-date with our latest CLI version.

Anyways, I think your best option at this point is to download the Functions CLI manually (install instructions are [here](https://github.com/Azure/azure-functions-core-tools#azure-functions-core-tools)) and do your local development that way. Can you verify whether this unblocks your local development?

**Comment by paulceli** [comment]
@cgillum Thanks for the workaround ! works perfect 👌.
Didn't knew I was using so cutting edge tech. 😀 

nice work guys 👍

**Comment by mikhailshilkov** [comment]
Upgrading `Microsoft.NET.Sdk.Functions` to version `1.0.14` seems to resolve this issue. Should we update samples?

**Comment by jeffhollan** [comment]
Update to templates just got merged out and should roll out to VS tooling very soon https://github.com/Azure/azure-functions-tooling-feed/pull/4

**Comment by cgillum** [comment]
Awesome! Yes, we should definitely update the samples...

**Comment by cgillum** [comment]
@mikhailshilkov I believe your F# sample is the only one which is precompiled and targets v2 currently. For some reason, I can't get it running at all. Not sure if it's a CLI issue or something on my machine. Are you able to get it working with these changes?

**Comment by mikhailshilkov** [comment]
@cgillum Hmm, it starts seemingly fine, but I get 404 from start endpoints... Can't figure it out yet, I thought it was working before. I updated to the latest CLI.

**Comment by cgillum** [comment]
@mikhailshilkov Odd. There was a bug in a previous version of the CLI which broke webhooks (status query, etc.), but the start endpoint is just a regular HTTP trigger, right? I'm not sure what would have regressed that.

**Comment by mikhailshilkov** [comment]
@cgillum What does your "can't get it running" look like?

**Comment by ajayraaviv** [comment]
Azure Functions CLI Tools version 2.2.2 fixed the issue in my case

**Comment by Lakiwann** [comment]
I had the same problem with Win10 environment using Visual Studio 2017 15.7.5.  I had to upgrade the Azure Functions and Web Jobs Tools (Tools -> Extensions and Updates -> Azure Functions and Web Jobs Tools) to version 15.0.40617.0.  I had the problem with the version 15.0.40608.0 that I previously had installed.

**Comment by TonyWoo** [comment]
thank you @Lakiwann , it struggled me 2 hours. I just updated the azure functions and web jobs tools from 15.0.40608.0 to v 15.0.40617.0 as your said, and then it works.
