### ISSUE TITLE
Very large input to CallActivityAsync is not serialisable

### ISSUE THREAD

**Issue by CiaranMacCarthaigh** [Azure/azure-functions-durable-extension#437]
### Issue

When calling a function via `CallActivityAsync` and passing as the `input` a large amount of data (for example, a large array) the function fails with a `System.ArgumentOutOfRangeException`.

### Root cause

From looking at the stack trace (reproduced below) it appears that it's trying to serialise the parameter (i.e. the large data array) to a JSON string, but the data is so big that it cannot be serialised.

If you need a sample project, let me know and I'll provide it.

### Environment
Packages:
 - Microsoft.Azure.WebJobs.Extensions.DurableTask: v1.6.1
 - Microsoft.Azure.WebJobs.Extensions.Storage: 3.0.0-beta8
 - Microsoft.NET.Sdk.Functions: 1.0.21

### Stack trace

     17a4d4ef23434cdab10d4fd87e7f2e57: Function 'ProcessDataRows (Orchestrator)' failed with an error. Reason: System.ArgumentOutOfRangeException: The length cannot be greater than the capacity.
     Parameter name: valueCount
        at System.Text.StringBuilder.Append(Char* value, Int32 valueCount)
        at System.Text.StringBuilder.AppendHelper(String value)
        at System.Text.StringBuilder.Append(String value)
        at System.IO.StringWriter.Write(String value)
        at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
        at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
        at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
        at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
        at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
        at DurableTask.Core.Serializing.JsonDataConverter.Serialize(Object value, Boolean formatted)
        at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskInternal(String name, String version, String tasklist, Type resultType, Object[] parameters)
        at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskToWorker[TResult](String name, String version, String tasklist, Object[] parameters)
        at DurableTask.Core.TaskOrchestrationContext.ScheduleTask[TResult](String name, String version, Object[] parameters)
        at Microsoft.Azure.WebJobs.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, String instanceId, RetryOptions retryOptions, Object input)
        at UnreliableAzureFunctions.UnreliableFunction.ProcessDataRows(DurableOrchestrationContext context, ILogger logger) in C:\Users\Ciaran\RiderProjects\UnreliableAzureFunctions\UnreliableAzureFunctions\UnreliableFunction.cs:line 41
        at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
        at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 63
        at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput). IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.6.1. SequenceNumber: 5.

**Comment by cgillum** [comment]
Interesting. It appears to be some kind of limitation in Newtonsoft.Json. How long is the list that is being serialized?

**Comment by CiaranMacCarthaigh** [comment]
I've used a jagged array of `strings`. The base array is 50000 long, and each sub-array has length 12, so a total of 600000. Each string in the array is 5000 long.

The method I used for creating the reproduction data is:

    private static string[][] CreateALoadOfData()
    {
        var rows = new string[50000][];
        for (int index = 0; index < rows.Length; index++)
        {
            string[] rowData = new string[12];
            for (int dataIndex = 0; dataIndex < rowData.Length; dataIndex++)
            {
                rowData[dataIndex] = new string('B', 5000);
            }
            rows[index] = rowData;
       }
       return rows;
    }

It's a bit of an extreme data set, but I've seen it happen with smaller arrays consisting of more complicated data types (with many named properties). I think it depends on the type that's being serialised.

One more thing: I'm sorry, I copied the wrong stack trace in the original message. The previous stack trace was when _returning_ from a function, the new stack trace is for the _input_ to a function. However I think the issue is the same: Newtonsoft.Json cannot handle the size of the data, or the data is too big for `StringBuilder`. Should I update the original post to explicitly mention both cases?

**Comment by CiaranMacCarthaigh** [comment]
I've done a bit of investigating myself into the issue. The issue comes about because Newtonsoft.Json uses a `StringWriter` when serialising data, and `StringWriter` itself uses a `StringBuilder` internally for storing the data. So far so good.

The underlying issue is that `StringBuilder` has a [`MaxCapacity`](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.maxcapacity?view=netframework-4.7.2#System_Text_StringBuilder_MaxCapacity) property, of type `Int32`. Essentially it means that the contents of a `StringBuilder` can never be greater than `Int32.MaxValue`, or 2147483647 characters long, and therefore Newtonsoft.Json - or any other code using `StringBuilder` - can never handle a string more than 2147483647 characters long. Newtonsoft.Json does not use a different value for `MaxCapacity`.

**Comment by cgillum** [comment]
Closing out this older issue, particularly because it seems to be specific to Newtonsoft.Json.

FWIW, some of these constraints may change when we move to supporting Durable Functions in the .NET Isolated worker, in which case we hope to move away from Newtonsoft.Json.
