### ISSUE TITLE
 An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/azure-functions-durable-extension#452]
```
Activity function 'HttpPost' failed: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
```

```
private static HttpClientService httpClient = new HttpClientService(new System.Net.Http.HttpClient());
        [FunctionName("HttpPost")]
        public static async Task<bool> Run([ActivityTrigger]string input, ILogger log)
        {
           
            await httpClient.PostAsync(input);
            return true;
        }
```

Is this because I host azure function in B1 plan?

**Comment by andrew-vandenbrink** [comment]
Updating the service plan S1 seems fix the issue

**Comment by andrew-vandenbrink** [comment]
This is thing back again on the service which barely doing http post
```
73f0c2197bac45fcaf7c0f62ad20e1e5: Function 'HttpPost (Activity)' failed with an error. Reason: System.Net.Http.HttpRequestException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance. ---> System.InvalidOperationException: An asynchronous socket operation is already in progress using this SocketAsyncEventArgs instance.
   at System.Net.Sockets.SocketAsyncEventArgs.ThrowForNonFreeStatus(Int32 status)
   at System.Net.Sockets.SocketAsyncEventArgs.StartOperationCommon(Socket socket, SocketAsyncOperation operation)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Udocx.Common.Services.HttpClientService.PostAsync(String uri) in C:\Users\andrew\source\repos\Udocx.Ocr.TesseractService\Udocx.Common\Services\HttpClientService.cs:line 21
   at Udocx.Ocr.TesseractService.Services.Client.Http.HttpPost.Run(JObject input, ILogger log) in C:\Users\andrew\source\repos\Udocx.Ocr.TesseractService\Udocx.Ocr.TesseractService\Services\Client\Http\HttpPost.cs:line 28
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 63
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 561
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 508
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 444
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstance instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 249. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: udocx-demo-ocrtesseract. SlotName: Production. ExtensionVersion: 1.6.2. SequenceNumber: 162.
```

**Comment by andrew-vandenbrink** [comment]
Azure service plan already S1
It is barely make http post
Things start going wrong after I make an update to function apps

**Comment by andrew-vandenbrink** [comment]
This issue gone again by changing azure plan service ( from S1 to S2 and then S2 back to S1 ), but could come back again as root cause still unknown)

**Comment by andrew-vandenbrink** [comment]
Maybe this https://github.com/Azure/azure-functions-host/issues/3610 better repo to submit issue
