### ISSUE TITLE
Orchestrationclient TaskHub configurable option.

### ISSUE THREAD

**Issue by praveena-m** [Azure/azure-functions-durable-extension#499]
Instead of hardcoding a taskhub name, need a way to define it in an app setting and refer to it using % signs. 

For instance, if you have a setting called CRON_EXPRESSION, then you can refer that as below (Reference : [https://github.com/Azure/azure-functions-host/issues/1934](url) )
`
public static void Run([TimerTrigger("%CRON_EXPRESSION%")]TimerInfo myTimer, TraceWriter log)
`
Currently below code throws exception.

```csharp
[FunctionName("HttpStart")]
public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, methods: "post", Route = "orchestrators/{functionName}")]
HttpRequestMessage req, [OrchestrationClient(TaskHub ="%MyHubName%")] DurableOrchestrationClient starter, string functionName, TraceWriter log)
{
	// Function input comes from the request content.
	dynamic eventData = await req.Content.ReadAsAsync<object>();
	string instanceId = await starter.StartNewAsync(functionName, eventData);

	log.Info($"Started orchestration with ID = '{instanceId}'.");

	var res = starter.CreateCheckStatusResponse(req, instanceId);
	res.Headers.RetryAfter = new RetryConditionHeaderValue(TimeSpan.FromSeconds(10));
	return res;
}
```

```
### Exception while executing function: HttpStart -> Exception binding parameter 'starter' -> Invalid queue name. Check MSDN for more information about valid queue naming.",
  "errorDetails": "Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: HttpStart ---> System.InvalidOperationException : Exception binding parameter 'starter' ---> System.ArgumentException : Invalid queue name. Check MSDN for more information about valid queue naming.
   at Microsoft.WindowsAzure.Storage.NameValidator.ValidateShareContainerQueueHelper(String resourceName,String resourceType)
   at Microsoft.WindowsAzure.Storage.NameValidator.ValidateQueueName(String queueName)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.GetQueueInternal(CloudQueueClient queueClient,String taskHub,String suffix)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.GetWorkItemQueue(CloudStorageAccount account,String taskHub)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService..ctor(AzureStorageOrchestrationServiceSettings settings,IOrchestrationServiceInstanceStore customInstanceStore)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.<GetClient>b__81_0(OrchestrationClientAttribute attr)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key,Func`2 valueFactory)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.GetClient(OrchestrationClientAttribute attribute)
   at Microsoft.Azure.WebJobs.Host.Bindings.BindingFactory.DelegateConverterBuilder`2.Convert(TAttribute input)
   at Microsoft.Azure.WebJobs.Host.Bindings.PatternMatcher.Invoker`2.<>c__DisplayClass0_0.<Work>b__0(Object input)
   at Microsoft.Azure.WebJobs.Host.Bindings.BindToInputBindingProvider`2.ExactBinding`1.BuildAsync(TAttribute attrResolved,ValueBindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Bindings.BindingBase`1.BindAsync[TAttribute](??)
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,ParameterHelper parameterHelper,TraceWriter traceWriter,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw()
   at async Microsoft.Azure.WebJobs.JobHost.CallAsync(??)
   at async Microsoft.Azure.WebJobs.Script.ScriptHost.CallAsync(String method,Dictionary`2 arguments,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.WebHost.WebScriptHostManager.HandleRequestAsync(FunctionDescriptor function,HttpRequestMessage request,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.Host.FunctionRequestInvoker.ProcessRequestAsync(HttpRequestMessage request,CancellationToken cancellationToken,WebScriptHostManager scriptHostManager,WebHookReceiverManager webHookReceiverManager)
   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.<>c__DisplayClass3_0.<ExecuteAsync>b__0(??)
   at async Microsoft.Azure.WebJobs.Extensions.Http.HttpRequestManager.ProcessRequestAsync(HttpRequestMessage request,Func`3 processRequestHandler,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.WebHost.Controllers.FunctionsController.ExecuteAsync(HttpControllerContext controllerContext,CancellationToken cancellationToken)
   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at async System.Web.Http.Dispatcher.HttpControllerDispatcher.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.WebScriptHostHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at async Microsoft.Azure.WebJobs.Script.WebHost.Handlers.SystemTraceHandler.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
   at async System.Web.Http.HttpServer.SendAsync(HttpRequestMessage request,CancellationToken cancellationToken)
```

**Comment by cgillum** [comment]
This makes a lot of sense. Thanks for opening this issue - we will look into it.

**Comment by cgillum** [comment]
Support for this has been merged into the **dev** branch and will go out with the v1.7.0 release. Thanks for opening this issue!
