### ISSUE TITLE
"Invalid table name" error if task hub name contains special characters

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#505]
I tried to deploy a function app which contained a dash character (`-`) in the task hub name and the functions host failed to start.  The Azure Portal only reported the following text:

```
Invalid table name. Check MSDN for more information about valid table naming.
```

There was no indication of what table it was referring to or why. Here was the actual exception, which was harder to discover:

```
System.ArgumentException : Invalid table name. Check MSDN for more information about valid table naming.
   at Microsoft.WindowsAzure.Storage.NameValidator.ValidateTableName(String tableName) at c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\NameValidator.cs : 190
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore..ctor(AzureStorageOrchestrationServiceSettings settings,MessageManager messageManager,AzureStorageOrchestrationServiceStats stats)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService..ctor(AzureStorageOrchestrationServiceSettings settings,IOrchestrationServiceInstanceStore customInstanceStore)
   at DurableTask.AzureStorage.AzureStorageOrchestrationService..ctor(AzureStorageOrchestrationServiceSettings settings)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.Microsoft.Azure.WebJobs.Host.Config.IExtensionConfigProvider.Initialize(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.InvokeExtensionConfigProviders(ExtensionConfigContext context)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.CreateStaticServices(JobHostConfiguration config)
   at Microsoft.Azure.WebJobs.JobHost.InitializeServices()
   at Microsoft.Azure.WebJobs.Script.Utility.CreateMetadataProvider(JobHost host) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Utility.cs : 362
   at Microsoft.Azure.WebJobs.Script.ScriptHost.LoadBindingExtensions(IEnumerable`1 functionMetadata,JObject hostConfigObject) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 966
   at Microsoft.Azure.WebJobs.Script.ScriptHost.Initialize() at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHost.cs : 299
   at Microsoft.Azure.WebJobs.Script.ScriptHostManager.RunAndBlock(CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Host\ScriptHostManager.cs : 177
```

The durable extension should throw a friendly validation error to make it more clear to the Azure Portal what the problem is.

**Comment by cgillum** [comment]
The associated PR has been merged and will go out with the next release.
