### ISSUE TITLE
Failed orchestrations appearing to be from inconsistent versions after web deploy

### ISSUE THREAD

**Issue by ghills** [Azure/azure-functions-durable-extension#512]
### Summary

We had a handful of orchestrator instances fail based on what appears to be, based on the particular error message, a different version of the function app code running the orchestrator client and the orchestrator instance after an update via web deploy was performed.

### Details

I successfully deployed an update via Web Deploy to our compiled-C# function app that uses durable functions. One of the changes in the update was that two properties in a nested object used as orchestrator input changed from `int` to `int?`.

The general architecture is that we have a handful of sources that are checking for new work-items and adding the work items to an Azure Storage Queue. This queue is then serviced to create an orchestrator instance for each work item.

A batch of 10 new work items was added and we noticed that only 8 came through OK. The other two failed on the `GetInput` call in the orchestrator with the following error:

```
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Int32'. Path 'DocumentMetadata.InternalUpload.CountyId', line 1, position 1509. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at DurableTask.Core.Serializing.JsonDataConverter.Deserialize(String data, Type objectType)
   at DurableTask.Core.Serializing.DataConverter.Deserialize[T](String data)
   at Microsoft.Azure.WebJobs.DurableOrchestrationContext.GetInput[T]()
   at Puller.Pipeline.PullerPipelineOrchestrator.<RunPipelineAsync>d__3.MoveNext()
```

After we noticed this problem we submitted the same batch of 10 work items and 9 came through successfully this time, with the one failure being from the same exact error.

When I inspect the input in the `DurableFunctionsHubInstances` table for the instance IDs on the failures, I see that in all cases the affected property (`DocumentMetadata.InternalUpload.CountyId`) in fact has `null` as the value. This was expected with the new version of the code as it was now nullable and thus had a different default value. The nature of the error, however, led me to believe that the host running the actual orchestration was still using the old version of the software where that property was not nullable.

I manually restarted the function app from the Azure portal to see if that would help "sync" up the running hosts for this application and manually submitted the one missing work item through. We have processed a number of work items through the system since then and so far have not seen the error again.

I've been pouring over the logs trying to find any additional insights but my best guess is my theory, though unconfirmed, that an old version of the code was still being run on some host(s) but I don't know of a way I can tell.

### Timeline

(all times are Pacific)

1. 11/11/18 7:41 PM - Updated software deployed via Web Deploy
2. 11/11/18 8:01 PM - First batch of 10 work items submitted (of which 2 failed)
3. 11/11/18 8:26 PM - Second batch of 10 work items submitted (of which 1 failed)
4. 11/11/18 ~8:45 PM - Function app restarted via Azure Portal
5. 11/11/18 9:01 PM - failed work item from second batch is successfully resubmitted and processed.

### Specific ID Values

I collected the orchestrator instance ID's for all the orchestration instances involved in the above description. I also looked up the `ExecutionId` for each one from the `DurableFunctionsHubInstances` table in the associated storage account. This function app runs in **West US**.

Batch 1 - 10 items, 2 failures
```
instance id, execution id, time started,errored
de22bc478d54484ea8d0410a85dc2d5e,38f65d56be7841228e579b75ae0476e3,"11/11/2018, 8:01:02 PM",false
2e6344d77a254aaea1383e7540f566e6,03a6e5296114400f91a60cd217356322,"11/11/2018, 8:01:02 PM",false
c5fa0fb2b32e44a9b99554242025ca23,f8f4076558c74929b778258ee17edfab,"11/11/2018, 8:01:02 PM",true
b6936ab211a4415fb46ddd17236b5152,1c7bd0fb80104d43a310a085427cc6d5,"11/11/2018, 8:01:02 PM",false
5c42040be0864376afa13e7b9dea2220,e11a3075978540cfb32255ca1c3059b0,"11/11/2018, 8:01:03 PM",false
f6529c1dd6ea48929bdec634b01df3fa,33cf234cf45f4802a3e0694d6e6bc683,"11/11/2018, 8:01:03 PM",false
85d9c10b6b8e440684e33d5662b34fb0,672508156e1c4a98b67295b8426936ae,"11/11/2018, 8:01:03 PM",false
6e5a78253ddf40e7abbea5bbf753f85b,9ab6a6d39c3c46ad9fefc709bb18dd99,"11/11/2018, 8:01:04 PM",false
28f1c9f998624149ab99ffdd235c3d50,da3cc4fe9b724e249e1bc335cb32b93b,"11/11/2018, 8:01:04 PM",true
579c502e3cd54d6b8570786eb79e4665,d92cf89180e848aca07f9557f9e4f706,"11/11/2018, 8:01:04 PM",false
```

Batch 2 - 10 items, 1 failure
```
instance id,execution id,time started,errored
8fbdd66ce5e84f69ab09dfa4177e1850,8cb9f0213d0f45299fdc42212ca9253a,"11/11/2018, 8:26:00 PM",false
2be26e21cfb9465b98d0d6255eb840d8,12f3ba2a818c48bcbdfbf909a6b9022a,"11/11/2018, 8:26:01 PM",false
c4e55a1e6371430c83b8be8f9cc85970,1d8d381884c445429429e28d8f5c38c6,"11/11/2018, 8:26:01 PM",false
5146b9c63def4190a1795b804303f0bb,c1ea80adacc74b75a1f06e546f8fac50,"11/11/2018, 8:26:01 PM",false
69ccdd1f40604d67a25cd6beb6381427,f26569d824e14349a452ed16407e60fb,"11/11/2018, 8:26:01 PM",false
d926bd6af4cf40eaa2a2494e5a7f451d,197a9132fdce401fb337c329e1394945,"11/11/2018, 8:26:02 PM",false
0971d57a62c844f08c4f369f54abc4cc,00f7a7151898422e9835be4ebf105bbd,"11/11/2018, 8:26:02 PM",true
632af4d2e69f43d0999b845f78c1f527,9b14f3a51c54477a8e96651cfda911b1,"11/11/2018, 8:26:02 PM",false
56ca80ff1dc54bb791e788c6d0044047,d384b4029ec64151a119106f23ce21f4,"11/11/2018, 8:26:03 PM",false
40ce3c1108d04760bae5b1a8c63d355e,e11ab48357fb4fb9a6dff906191c6924,"11/11/2018, 8:26:03 PM",false
```

Batch 3 - 1 item (resubmission of failure from Batch 2), 0 failures
```
instance id,execution id,time started,errored
5254c6ce1a5f4ea79a3a40e239a47ec4,cc3f71fa4d624134b369a943585a89de,"11/11/2018, 9:01:01 PM",false
```

Any help understanding what happened and if there is anything we did wrong to cause the problem would be greatly appreciated as right now I am nervous that more errors could pop up. Please let me know if any other information is needed and I will gladly provide it.

**Comment by ghills** [comment]
For purposes of locating our function app it is in `West US` and here is a sample function execution ID w/ timestamp:

`2018-11-12 20:41:00.016 | Function started (Id=143ff771-cd65-4fdc-8dcb-3118c5b609f0)`

**Comment by cgillum** [comment]
Thanks @ghills for reporting this. I wonder if the issue could be (as you suggested) that some instances of the Azure Functions runtime not getting updated with your new code (until the restart).

Have you tried using an alternate deployment method, such as **Run-From-Package**? I'm curious to know if whether that suffers from the same problem. But either way, we'll need to investigate this further.

**Comment by ghills** [comment]
@cgillum I have not tried any other deployment methods - I just learned about "Run-From-Package" after reading up on it.

I can try setting up a test scenario that would be easier for me to switch deployment methods as the current environment that is wired up with our dev-ops for production would not be easy to test with.

I fear, however, that it may not be easy for me to reproduce the behavior as I had deployed these same changes to to our "certification" environment prior to rolling it out into production and didn't encounter the same problems. I will note that the certification environment has far lower consumption and processing so it may not have had the same characteristics in terms of scaling to instances.

In the coming days I will try and put together a simplified version of what happened and try to induce this behavior on Azure again and get back to you.

**Comment by cgillum** [comment]
Thanks. I did some asking around, at it sounds like other customers have run into similar issues. The problem appears to be general to Azure Functions and not specific to Durable Functions. Here is an issue which currently tracks this behavior: https://github.com/Azure/azure-functions-host/issues/2636.

**Comment by cgillum** [comment]
I'm going to go ahead and close this issue since it appears to be a general Azure Functions issue and not a Durable Functions issue. Let's follow up on the linked issue.
