### ISSUE TITLE
SSL Issue calling HTTPStart Function in Javascript

### ISSUE THREAD

**Issue by tknight-diig** [Azure/azure-functions-durable-extension#545]
Hi

I have been trying to get the latest version of durable functions using Javascript running locally however I seem to be getting an SSL Error when invoking the HTTP start function. This is happening on the samples that are in the repo. The error I get is below

Thanks,

Tom

Host lock lease acquired by instance ID '000000000000000000000000F35EE393'.
[12/12/2018 11:44:47] Executing HTTP request: {
[12/12/2018 11:44:47]   "requestId": "eee5da51-07f9-4f6d-9b8a-061dd04287d7",
[12/12/2018 11:44:47]   "method": "POST",
[12/12/2018 11:44:47]   "uri": "/orchestrators/E1_HelloSequence"
[12/12/2018 11:44:47] }
[12/12/2018 11:44:47] Executing 'Functions.HttpStart' (Reason='This function was programmatically called via the host APIs.', Id=d38a9f66-4046-4e2a-872b-7c999f58fe77)
[12/12/2018 11:44:47] Executed 'Functions.HttpStart' (Failed, Id=d38a9f66-4046-4e2a-872b-7c999f58fe77)
[12/12/2018 11:44:47] System.Private.CoreLib: Exception while executing function: Functions.HttpStart. System.Private.CoreLib: Result: Failure
Exception: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:827:

Stack: Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:827:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14).

**Comment by kashimiz** [comment]
This sounds like an instance of [this known issue](https://github.com/Azure/azure-functions-durable-js/issues/28). The workaround in the description should resolve your issue, but if not, please let us know what versions of the `durable-functions` npm package and Microsoft.Azure.WebJobs.Extensions.DurableTask extension (in extensions.csproj) your function app has installed.

**Comment by cgillum** [comment]
Closing in favor of tracking this in the linked issue above.
