### ISSUE TITLE
ArgumentException "The function 'XYZ' doesn't exist" when the functions host recycles

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#577]
### Issue
Given sufficient load on a function app, it's possible that an orchestrator function will fail with the following exception during a host recycle:

```
{InstanceID}: Function 'XYZ (Orchestrator)' failed with an error. Reason: System.ArgumentException: The function 'ABC' doesn't exist, is disabled, or is not an activity function. Additional info: No activity functions are currently registered!
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.ThrowIfFunctionDoesNotExist(String name, FunctionType functionType)
   at Microsoft.Azure.WebJobs.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, String instanceId, RetryOptions retryOptions, Object input)
```
This is caused by an incorrect validation check that occurs when the functions host is shutting down. The result is that the orchestration transitions into a Failed state.

This issue is expected to impact all versions of the Durable Functions extension.

### Workaround
No known workarounds at this time. Any failed orchestrations will need to be restarted from the beginning.

### Technical Details
The problem is that the [DurableTaskListener](https://github.com/Azure/azure-functions-durable-extension/blob/f6f1dce716b68d8baaa99ed64a9db1306577c58d/src/WebJobs.Extensions.DurableTask/Listener/DurableTaskListener.cs#L44-L54) "deregisters" a function when its listener is stopped by the functions runtime. It's possible that an orchestrator function may still be running after the listener has been stopped, in which case the `CallActivityAsync` and `CallSubOrchestratorAsync` APIs will [throw an exception because the target function is no longer listed](https://github.com/Azure/azure-functions-durable-extension/blob/f6f1dce716b68d8baaa99ed64a9db1306577c58d/src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs#L385).

The fix should be to relax this validation so that we don't throw in the case where a function has been "delisted", but rather allow the `CallActivityAsync` or `CallSubOrchestratorAsync` call to succeed. This will allow the message to be written to the queue, and once the listeners are startup up again, the function-call message can be picked up.

**Comment by olitomlinson** [comment]
I've just experienced this exact same exception under high-load.

**DF 1.7.1 **
**Functions V2**

> e62d2d1a-084b-4285-82c2-d7cd1d3ebd65: Function 'Orchestrator (Orchestrator)' failed with an error. Reason: System.ArgumentException: The function 'forward_to_<redacted>' doesn't exist, is disabled, or is not an activity function. Additional info: The following are the active activity functions: 'get_available_<redacted>'.
>    at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.ThrowIfFunctionDoesNotExist(String name, FunctionType functionType) in C:\projects\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\DurableTaskExtension.cs:line 522

**would using the rewind API be a suitable remediation for this? it feels like it should**

**Comment by olitomlinson** [comment]
Also had this for an Orchestrator around the same time : 

> The function 'Orchestrator' doesn't exist, is disabled, or is not an orchestrator function. Additional info: No orchestrator functions are currently registered!

**Comment by shiwani** [comment]
@cgillum  I am using the latest .net core 2.0 ,still facing the same issue .Kindly help.

**Comment by cgillum** [comment]
@shiwani please open a new issue since this one is closed. Also, please include more information so that we can properly investigate.

**Comment by ParthPurani** [comment]
Clearing azure emulator data solved problem for me,

`cd C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator`
`.\AzureStorageEmulator.exe clear all`

_Please educate me if this is the wrong approch._

**Comment by stefanrothnet** [comment]
@ParthPurani Perfect, thanks a lot! Worked for me!

**Comment by antogh** [comment]
@ParthPurani  
Thanks, that helped. 
My problem started when I renamed some functions with more meaningful names
