### ISSUE TITLE
Called activities fail to rehydrate interface inputs correctly

### ISSUE THREAD

**Issue by rifuller** [Azure/azure-functions-durable-extension#619]
**Describe the bug**
Arguments that are interfaces to activity functions fail to deserialize back off the wire.  If the concrete type is instead used, the constructor parameters are all null.  

The parameters to instantiate the classes could be passed instead (eg. strings) but then I still need to pass the IServiceContainer/IContainer to resolve the dependencies in DI which runs into the same blocker as above.

I'm unable to use a static DI container because there is no static ILogger available which is required by other dependencies.

**Investigative information**

- Durable Functions extension version:
- Function App version (1.0 or 2.0): 2.17.1
- Programming language used: C#

***If JavaScript***  N/A
***If deployed to Azure*** N/A

**To Reproduce**

See repro code.

**Expected behavior**
I can pass the dependencies to the activity function, or I can pass the service container.

**Actual behavior**
#1 
```
System.Private.CoreLib: Exception while executing function: Function2_Hello. Newtonsoft.Json: Could not create an instance of type FunctionApp2.IClient. Type is an interface or abstract class and cannot be instantiated. Path 'Item1', line 1, position 180.
[2/22/2019 7:00:37 PM] b3d9882d3da34645865197e1a7036db5: Function 'Function2_Hello (Activity)' failed with an error. Reason: Newtonsoft.Json.JsonSerializationException: Could not create an instance of type FunctionApp2.IClient. Type is an interface or abstract class and cannot be instantiated. Path 'Item1', line 1, position 180.
```

#2 
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: options
  Source=FunctionApp2
  StackTrace:
   at FunctionApp2.Client..ctor(IOptions`1 options) in C:\Users\rifuller\source\repos\FunctionApp2\Function2.cs:line 28
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
```

#3 
```a0d11931aa2f4d48a6eb01c89fbd3bef: Function 'Function2 (Orchestrator)' failed with an error. Reason: Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'Engine' with type 'Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine'. Path '[0].Item1.Engine.Root'.
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
[2/22/2019 7:05:13 PM]    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
[2/22/2019 7:05:13 PM]    at DurableTask.Core.Serializing.JsonDataConverter.Serialize(Object value, Boolean formatted)
[2/22/2019 7:05:13 PM]    at DurableTask.Core.Serializing.JsonDataConverter.Serialize(Object value)
[2/22/2019 7:05:13 PM]    at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskInternal(String name, String version, String taskList, Type resultType, Object[] parameters)
[2/22/2019 7:05:13 PM]    at DurableTask.Core.TaskOrchestrationContext.ScheduleTaskToWorker[TResult](String name, String version, String taskList, Object[] parameters)
[2/22/2019 7:05:13 PM]    at DurableTask.Core.TaskOrchestrationContext.ScheduleTask[TResult](String name, String version, Object[] parameters)
[2/22/2019 7:05:13 PM]    at Microsoft.Azure.WebJobs.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, String instanceId, RetryOptions retryOptions, Object input)
[2/22/2019 7:05:13 PM]    at FunctionApp2.Function2.RunOrchestrator(DurableOrchestrationContext context) in C:\Users\rifuller\source\repos\FunctionApp2\Function2.cs:line 59
[2/22/2019 7:05:13 PM]    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
[2/22/2019 7:05:13 PM]    at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 63
[2/22/2019 7:05:13 PM]    at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in C:\projects\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 92. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.7.1. SequenceNumber: 5.
[2/22/2019 7:05:13 PM] Executed 'Function2' (Failed, Id=5782d1f0-2c47-4e3f-aaf4-d1185375a158)
[2/22/2019 7:05:13 PM] System.Private.CoreLib: Exception while executing function: Function2. System.Private.CoreLib: Orchestrator function 'Function2' failed: Self referencing loop detected for property 'Engine' with type 'Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine'. Path '[0].Item1.Engine.Root'.
```

**Known workarounds**
None I've figured out yet. 

** Repro **
```c#
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace FunctionApp2
{
    public class Args
    {
        public string Val { get; set; }
    }

    public class ClientOptions
    {
    }

    public class Client : IClient
    {
        private readonly IOptions<ClientOptions> options;

        public Client(IOptions<ClientOptions> options)
        {
            this.options = options ?? throw new System.ArgumentNullException(nameof(options));
        }

        public void DoWork(Args args)
        {
        }
    }

    public interface IClient
    {
        void DoWork(Args args);
    }

    public static class Function2
    {
        [FunctionName("Function2")]
        public static async Task RunOrchestrator([OrchestrationTrigger] DurableOrchestrationContext context)
        {
            var services = new ServiceCollection();
            services.AddOptions<ClientOptions>();
            services.AddTransient<IClient, Client>();
            var sp = services.BuildServiceProvider();
            using (var scope = sp.CreateScope())
            {
                // Instantiate here and pass the dependencies in
                var client = scope.ServiceProvider.GetRequiredService<IClient>();
                var args = new Args() { Val = "val" };
                await context.CallActivityAsync("Function2_Hello", (client, args));

                // Pass the service provider itself in
                var args2 = new Args() { Val = "val" };
                await context.CallActivityAsync("Function2_Hello2", (scope.ServiceProvider, args2));
            }
        }

        [FunctionName("Function2_Hello")]
        public static void SayHello([ActivityTrigger] DurableActivityContext inputs)
        {
            // #1 fail to deserialize
            (IClient client, Args args) = inputs.GetInput<(IClient, Args)>();
            client.DoWork(args);

            // #2 ArgumentNullException -  IOptions<ClientOptions>
            (IClient client2, Args args2) = inputs.GetInput<(Client, Args)>();
            client2.DoWork(args2);
        }

        [FunctionName("Function2_Hello2")]
        public static void SayHello2([ActivityTrigger] DurableActivityContext inputs)
        {
            // #3: cant pass ServiceProvider here either to instantiate the 
            // dependencies instead of passing them on the wire for the same reason.
            (ServiceProvider sp, Args args) = inputs.GetInput<(ServiceProvider, Args)>();
            IClient client = sp.GetRequiredService<IClient>();
            client.DoWork(args);
        }

        [FunctionName("Function2_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
            [OrchestrationClient]DurableOrchestrationClient starter,
            ILogger log)
        {
            string instanceId = await starter.StartNewAsync("Function2", null);
            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");
            return starter.CreateCheckStatusResponse(req, instanceId);
        }
    }
}
```

**Comment by rifuller** [comment]
Similar issue to Spark where you want classes to be instantiated on the workers instead of on the driver and then serialized.  Without a way to pass the service container the DI framework is unusable in this model.  I should be able to manually hook up all the dependencies but then you look all the magic of M.Extensions.DependencyInjection or Autofac and such.

Related to: [Dependency Injection support for Functions](https://github.com/Azure/azure-functions-host/issues/3736)

**Comment by cgillum** [comment]
I don't fully understand what the expectation is:

> I can pass the dependencies to the activity function, or I can pass the service container.

Arguments to activity functions are just data that gets serialized to JSON. It may get deserialized on an entirely different VM that has not been initialized with your `ServiceCollection`. I'm not sure how your code samples above would be expected to work in this situation.

Admittedly, I'm not very familiar with the mechanics of DI (I've only done enough of it to scrape by). Can you point me to an example where someone is deserializing a JSON blob into an interface and having it work correctly with DI?

**Comment by rifuller** [comment]
It's a similar problem to what Spark has when serializing data to send to its workers. Those objects obviously have to be serializable but without that knowledge the error may be confusing as the type for arguments is object. 

Solution is to simplify the arguments instead of sending complex objects over the wire.  

Happy to close this unless you would like to improve the documentation or error message.

**Comment by cgillum** [comment]
I think it's reasonable for us to show a better error message when we fail to deserialize inputs. I'll update the title of this issue.
