### ISSUE TITLE
Recursive self referencing JSON response from an activity

### ISSUE THREAD

**Issue by asavaritayal** [Azure/azure-functions-durable-extension#685]
**Describe the bug**
When sending a recursive JSON schema response from an activity function, the string gets modified by the runtime. 

**Known workarounds**
Can be overridden by using a non-JSON looking syntax e.g. adding $ signs at the beginning and end of the string before sending it back. 

**Additional context**
@marcduiker could you please connect us with your team for any additional context/details I might have missed above? Thanks!

**Comment by marcduiker** [comment]
Hi @jozsefkovacs, could you add more info to this one? Perhaps an anonymized sample?

**Comment by MateusAmin** [comment]
> 23d10f65e24c49609a6bf9eddf7812w4: Function 'asd (Orchestrator)' failed with an error. Reason: Microsoft.Azure.WebJobs.FunctionFailedException: The activity function 'asd' failed: "Self referencing loop detected for property 'ManifestModule' with type 'System.Reflection.RuntimeModule'. Path 'TargetSite.Module.Assembly'.". See the function execution logs for additional details. ---> Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'ManifestModule' with type 'System.Reflection.RuntimeModule'. Path 'TargetSite.Module.Assembly'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at asd.asd(CloudEvent event, TelemetryClient telemetry) in :line 232
   at zxc.sdf(CloudEvent arg, IProcessor processor) in :line 63
   at zxc.xcv(CloudEvent event) in :line 34
   at Clqwe.qwe(String payload, ILogger log) in :line 54
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 584
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 531
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 467
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 277
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, String instanceId, RetryOptions retryOptions, Object input) in C:\projects\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\DurableOrchestrationContext.cs:line 456
   at asd.RunOrchestrator(DurableOrchestrationContext context) in:line 23
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in C:\projects\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 92. IsReplay: False. State: Failed. HubName: DurableFunctionsHub. AppName: fun-ace-prod-v2. SlotName: Production. ExtensionVersion: 1.7.1. SequenceNumber: 78.

@asavaritayal @marcduiker

Perhaps something like this? I am have the same codebase in two different tenants. This issue is only occurring in one of them.  It looks like it doesn't matter what it is serializing as long as it is outside the main function class.

**Comment by MateusAmin** [comment]
Let me know if there is some sort of formatting I can do to clean up the stacktrace.

**Comment by cgillum** [comment]
I formatted the stacktrace to make it more readable (using the triple-back ticks, ```).

From what I can tell, it looks like the app code is calling `JsonConvert.SerializeObject` and passing in an object with a circular reference. Newtonsoft.Json doesn't like this and will throw this exception. More information on this general problem can be found in [this StackOverflow post](https://stackoverflow.com/questions/7397207/json-net-error-self-referencing-loop-detected-for-type).

More specifically, it looks like you're passing in some type which is not designed to be serialized. The mention of  `System.Reflection.RuntimeModule` in the exception message is the hint for this. I don't know exactly what your application is doing, but I suggest changing  the type of data you are trying to serialize to instead use serialization-friendly types.

I don't think this is a Durable Functions issue, but rather a general .NET application code issue. Let me know if there's any other help I can provide.

**Comment by TsuyoshiUshio** [comment]
I agree with Chris. Remove the self-reference is the simplest solution.  However, if you really need self-reference, you can serialize by your self. Durable Functions uses DurableTask repo which is shared with other projects. That is why we can't change the serialize method easily, However, you can serialize by your self like this.  I also encounter the same problem and solve it by serialize by my self. 

```
        public static TraceContextStore Create(TraceContext context)
        {
            var store = new TraceContextStore();
            string json = JsonConvert.SerializeObject(context, new JsonSerializerSettings()
            {
                TypeNameHandling = TypeNameHandling.Objects,
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize
            });
            store.TraceContextJson = json;
            return store;
        }
```

**Comment by jozsefkovacs** [comment]
Hello @asavaritayal thanks for creating an issue for this.

I'm adding an antonym repository to provide you with exact details for future reference.
[Repo : recursive-issue-685](https://github.com/jozsefkovacs/recursive-issue-685)

In this solution there is 3 sets of Starter, Orchestration and activity Function.

Under the folder **Issue_1** it is shown how the Json de-serializer fails to do it's job with the default settings.

Under the folder **Bonus_Issue** is shown that even if we state that the return type of the Activity and the expected type of the Orchestration is **string**, it still fails to de-serialize. Throwing the same exception. This Bonus issue folder is there just to save people time not to try fix it like that.

Folder **Workaround_1** contains a possible way to implement @TsuyoshiUshio suggestion. Here it can be noted that when (de)serializing the SelfRefClass we use additional settings mainly we are setting the ReferenceLoopHandling parameter.

**Comment by jozsefkovacs** [comment]
@cgillum Could you please suggest a way to set these Settings globally in a function? I guess that would be a more elegant way to deal with this issue, rather than explicitly setting how we (de)serialize through the Durable Task framework. Perhaps using the `IWebJobsStartup` Interface somehow to configure this on startup?

**Comment by cgillum** [comment]
@jozsefkovacs there isn't a way to control the serialization for function inputs and outputs currently. Support for customizing the JSON serializer is tracked by https://github.com/Azure/azure-functions-durable-extension/issues/65. Injecting a service as part of `IWebJobsStartup` sounds like a nice idea though, so I'll make a note of that.

However, the callstack above seems to indicate that the serialization is done inside the function code and not by this extension. That means the user code can use any serialization settings that it wants.

**Comment by Tyler-V** [comment]
Was this ever actioned? Is there a "simple" way in Startup to override the Newtonsoft serialization settings of the Azure functions to ignore self-referencing loops? This is a pretty common scenario when working with objects from Entity Framework, not having the ability to override how the durable functions serialize these makes it difficult to work with

**Comment by davidmrdavid** [comment]
Hi @Tyler-V. This change predates me, but I believe this was addressed in https://github.com/Azure/azure-functions-durable-extension/pull/1101.

@amdeel, do we have any docs or samples on how to customize the serializer?

**Comment by cgillum** [comment]
@Tyler-V is this what you're looking for? https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp#customizing-serialization-and-deserialization

**Comment by Tyler-V** [comment]
Microsoft has the best documentation, if you can find it whoops I missed that one thank you @cgillum :)
