### ISSUE TITLE
activityTrigger and orchestrationTrigger are not registered on Azure

### ISSUE THREAD

**Issue by juchom** [Azure/azure-functions-durable-extension#692]
I have a project with durable functions that works fine locally but not on Azure.

The starter function (TimerTrigger) works fine locally and doesn't start on Azure.

The orchestrator and activities are working fine locally but clicking on them in the portal on Azure I have this error:

> The binding type(s) 'orchestrationTrigger' are not registered. Please ensure the type is correct and the binding extension is installed. 
> The binding type(s) 'activityTrigger' are not registered. Please ensure the type is correct and the binding extension is installed. 

I've tried with:
Microsoft.Azure.WebJobs.Extensions.DurableTask v1.8.0 & v1.7.1
Microsoft.NET.Sdk.Functions 1.0.26 & 1.0.24
FUNCTIONS_EXTENSION_VERSION ~2

Connecting to remote logging with VS2019:

```
2019-04-08T08:43:06  Welcome, you are now connected to log-streaming service.
Application:2019-04-08T08:44:06  No new trace in the past 1 min(s).
Application:2019-04-08T08:45:06  No new trace in the past 2 min(s).
Application:2019-04-08T08:46:06  No new trace in the past 3 min(s).
Application:2019-04-08T08:47:06  No new trace in the past 4 min(s).
Application:2019-04-08T08:47:08.921 [Information] Stopping JobHost
Application:2019-04-08T08:47:08.940 [Information] Job host stopped
Application:2019-04-08T08:47:24.766 [Information] Initializing Host.
Application:2019-04-08T08:47:24.874 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=1
Application:2019-04-08T08:47:24.926 [Information] ApplicationInsightsLoggerOptions
Application:{
Application:  "SamplingSettings": {
Application:    "EvaluationInterval": "00:00:15",
Application:    "InitialSamplingPercentage": 100.0,
Application:    "MaxSamplingPercentage": 100.0,
Application:    "MaxTelemetryItemsPerSecond": 20.0,
Application:    "MinSamplingPercentage": 0.1,
Application:    "MovingAverageRatio": 0.25,
Application:    "SamplingPercentageDecreaseTimeout": "00:02:00",
Application:    "SamplingPercentageIncreaseTimeout": "00:15:00"
Application:  },
Application:  "SnapshotConfiguration": null
Application:}
Application:2019-04-08T08:47:24.927 [Information] LoggerFilterOptions
Application:{
Application:  "MinLevel": "None",
Application:  "Rules": [
Application:    {
Application:      "ProviderName": null,
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "None",
Application:      "Filter": null
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "Trace",
Application:      "Filter": null
Application:    }
Application:  ]
Application:}
Application:2019-04-08T08:47:24.927 [Information] LoggerFilterOptions
Application:{
Application:  "MinLevel": "None",
Application:  "Rules": [
Application:    {
Application:      "ProviderName": null,
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "None",
Application:      "Filter": null
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "Trace",
Application:      "Filter": null
Application:    }
Application:  ]
Application:}
Application:2019-04-08T08:47:24.933 [Information] FunctionResultAggregatorOptions
Application:{
Application:  "BatchSize": 1000,
Application:  "FlushTimeout": "00:00:30",
Application:  "IsEnabled": true
Application:}
Application:2019-04-08T08:47:24.933 [Information] SingletonOptions
Application:{
Application:  "LockPeriod": "00:00:15",
Application:  "ListenerLockPeriod": "00:00:15",
Application:  "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
Application:  "LockAcquisitionPollingInterval": "00:00:05",
Application:  "ListenerLockRecoveryPollingInterval": "00:01:00"
Application:}
Application:2019-04-08T08:47:24.935 [Information] Starting JobHost
Application:2019-04-08T08:47:24.937 [Information] Starting Host (HostId=myhost, InstanceId=3246cf05-921a-4773-a4e8-7e76cfea9bcb, Version=2.0.12382.0, ProcessId=8592, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~2)
Application:2019-04-08T08:47:24.965 [Information] Loading functions metadata
Application:2019-04-08T08:47:24.993 [Information] 1 functions loaded
Application:2019-04-08T08:47:25.198 [Information] Generating 1 job function(s)
Application:2019-04-08T08:47:25.318 [Error] Error indexing method 'MyFunctionStarter'
Application:Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'MyFunctionStarter' ---> System.InvalidOperationException : Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 242
Application:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 137 
Application:   End of inner exception
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 145
Application:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 73
Application:2019-04-08T08:47:25.387 [Warning] Function 'MyFunctionStarter' failed indexing and will be disabled.
Application:2019-04-08T08:47:25.388 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Application:2019-04-08T08:47:25.388 [Information] Host initialized (444ms)
Application:2019-04-08T08:47:25.408 [Information] Host started (464ms)
Application:2019-04-08T08:47:25.408 [Information] Job host started
Application:2019-04-08T08:47:25.809 [Information] Host Status: {
Application:  "id": "myhost",
Application:  "state": "Running",
Application:  "version": "2.0.12382.0",
Application:  "versionDetails": "2.0.12382.0 Commit hash: 690321b72c45f61f9d665ff8c23f980bc31c1c85"
Application:}
Application:2019-04-08T08:47:30.452 [Information] Host lock lease acquired by instance ID 'b40e06de24c624615a56120895201375'.
Application:2019-04-08T08:47:47.202 [Information] Initializing Host.
Application:2019-04-08T08:47:47.304 [Information] Host initialization: ConsecutiveErrors=0, StartupCount=1
Application:2019-04-08T08:47:47.370 [Information] ApplicationInsightsLoggerOptions
Application:{
Application:  "SamplingSettings": {
Application:    "EvaluationInterval": "00:00:15",
Application:    "InitialSamplingPercentage": 100.0,
Application:    "MaxSamplingPercentage": 100.0,
Application:    "MaxTelemetryItemsPerSecond": 20.0,
Application:    "MinSamplingPercentage": 0.1,
Application:    "MovingAverageRatio": 0.25,
Application:    "SamplingPercentageDecreaseTimeout": "00:02:00",
Application:    "SamplingPercentageIncreaseTimeout": "00:15:00"
Application:  },
Application:  "SnapshotConfiguration": null
Application:}
Application:2019-04-08T08:47:47.370 [Information] LoggerFilterOptions
Application:{
Application:  "MinLevel": "None",
Application:  "Rules": [
Application:    {
Application:      "ProviderName": null,
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "None",
Application:      "Filter": null
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "Trace",
Application:      "Filter": null
Application:    }
Application:  ]
Application:}
Application:2019-04-08T08:47:47.371 [Information] LoggerFilterOptions
Application:{
Application:  "MinLevel": "None",
Application:  "Rules": [
Application:    {
Application:      "ProviderName": null,
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "None",
Application:      "Filter": null
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Script.WebHost.Diagnostics.SystemLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": null,
Application:      "Filter": "<AddFilter>b__0"
Application:    },
Application:    {
Application:      "ProviderName": "Microsoft.Azure.WebJobs.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider",
Application:      "CategoryName": null,
Application:      "LogLevel": "Trace",
Application:      "Filter": null
Application:    }
Application:  ]
Application:}
Application:2019-04-08T08:47:47.371 [Information] FunctionResultAggregatorOptions
Application:{
Application:  "BatchSize": 1000,
Application:  "FlushTimeout": "00:00:30",
Application:  "IsEnabled": true
Application:}
Application:2019-04-08T08:47:47.371 [Information] SingletonOptions
Application:{
Application:  "LockPeriod": "00:00:15",
Application:  "ListenerLockPeriod": "00:00:15",
Application:  "LockAcquisitionTimeout": "10675199.02:48:05.4775807",
Application:  "LockAcquisitionPollingInterval": "00:00:05",
Application:  "ListenerLockRecoveryPollingInterval": "00:01:00"
Application:}
Application:2019-04-08T08:47:47.373 [Information] Starting JobHost
Application:2019-04-08T08:47:47.380 [Information] Starting Host (HostId=myhost, InstanceId=f1c92879-9bc6-4107-a4ab-40038726a5c7, Version=2.0.12382.0, ProcessId=6076, AppDomainId=1, InDebugMode=True, InDiagnosticMode=False, FunctionsExtensionVersion=~2)
Application:2019-04-08T08:47:47.420 [Information] Loading functions metadata
Application:2019-04-08T08:47:47.441 [Information] 1 functions loaded
Application:2019-04-08T08:47:47.654 [Information] Generating 1 job function(s)
Application:2019-04-08T08:47:47.754 [Error] Error indexing method 'MyFunctionStarter'
Application:Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'MyFunctionStarter' ---> System.InvalidOperationException : Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 242
Application:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 137 
Application:   End of inner exception
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 145
Application:   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Application:   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector index,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 73
Application:2019-04-08T08:47:47.806 [Warning] Function 'MyFunctionStarter' failed indexing and will be disabled.
Application:2019-04-08T08:47:47.807 [Warning] No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
Application:2019-04-08T08:47:47.807 [Information] Host initialized (425ms)
Application:2019-04-08T08:47:47.815 [Information] Host started (433ms)
Application:2019-04-08T08:47:47.815 [Information] Job host started
Application:2019-04-08T08:47:52.961 [Information] Host lock lease acquired by instance ID 'b40e06de24c624615a56120895201375'.
```

Here is the actual code

```
public static class MyFunctionStarter
{
        [FunctionName("MyFunctionStarter")]
        public static async Task Run([TimerTrigger("0 30 5 * * *")]TimerInfo myTimer,
            [OrchestrationClient] DurableOrchestrationClient starter)
    {
    }
}
```

The function body is empty. Without [OrchestrationClient] DurableOrchestrationClient starter, the function works, as soon as I add it doesn't work anymore.

Here is the csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.8.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.26" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

***If deployed to Azure***

- Timeframe issue observed: Since April 5th, 15h00 UTC
- Region: France Central
- Orchestration instance ID(s):

**Comment by juchom** [comment]
I've tried a webdeploy of the same code to another function app and it works.

Double checking the files from my zip deploy (not working) and the web deploy, I'm missing this file:
extensions.json

My build server and my local machine are using "Microsoft (R) Build Engine version 16.0.450+ga8dc7f1d34 for .NET Core"

Doing the same steps my build server does on my local machines I have the extensions.json when I publish.
On my build server this file is not present.

**Comment by juchom** [comment]
I made some progress but I still can't explain the issue.
My function is build with Azure DevOps.
With the Hosted VS 2017 it works fine, the extensions.json file is generated.
With my self hosted machine, I have no error during build time, but extensions.json is not generated...

Any idea?

**Comment by cgillum** [comment]
This is indeed odd. @fabiocav do you know what the problem could be, or who can help?

**Comment by juchom** [comment]
Ok, I made more progress. It works on my new build machines without VS2017 installed.

I have an old build machine with VS2017 installed and this one is not producing the extensions.json file.

How dotnet build knows how to produce extensions.json?

**Comment by juchom** [comment]
A bit more information:

This task is missing on my old build server:
```
10:25:32.475   1:7>Target "_GenerateFunctionsExtensionsMetadataPostBuild: (TargetId:231)" in file "C:\Users\MyUser\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets" from project "C:\MyProject\MyFunctions\E1.Functions.csproj" (entry point):
                   Using "GenerateFunctionsExtensionsMetadata" task from assembly "C:\Users\MyUser\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.2\build\..\tools\netstandard2.0\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.dll".
                   Task "GenerateFunctionsExtensionsMetadata" (TaskId:137)
                     Task Parameter:SourcePath=C:\MyProject\MyFunctions\bin\Release\netcoreapp2.2\bin (TaskId:137)
                     Task Parameter:OutputPath=C:\MyProject\MyFunctions\bin\Release\netcoreapp2.2\bin (TaskId:137)
                   Done executing task "GenerateFunctionsExtensionsMetadata". (TaskId:137)
                   Task "Move" skipped, due to false condition; ($(_IsFunctionsSdkBuild) == 'true' AND Exists('$(TargetDir)extensions.json')) was evaluated as (true == 'true' AND Exists('C:\MyProject\MyFunctions\bin\Release\netcoreapp2.2\extensions.json')).
```

**Comment by juchom** [comment]
Doing a diff of the dotnet build logs in diagnostics, the first important diff happens very soon is:

This line exists on a working machine and does not on the old build server
```
Property reassignment: $(_FunctionsExtensionsDir)="C:\MyProject\MyFunctions\bin\Release\netcoreapp2.2\bin" (previous value: "C:\MyProject\MyFunctions\bin\Release\netcoreapp2.2\") at C:\Users\MyUser\.nuget\packages\microsoft.azure.webjobs.script.extensionsmetadatagenerator\1.0.2\build\Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets (11,5)
```

**Comment by juchom** [comment]
FYI, I've just tried Microsoft.NET.Sdk.Functions v1.0.27 and issue is still present.

Let me know how can I help troubleshoot this.

**Comment by ConnorMcMahon** [comment]
@juchom, I believe I have this same issue on my machine. I will hopefully have an answer soon about how to resolve this.

As a side note, have you been having issues on that machine with all functions extensions not generating an `extension.json` file, or just durable functions?

**Comment by juchom** [comment]
@ConnorMcMahon it's not working only for durable functions.

This one works
```
[FunctionName("Function1")]
public static void Run([TimerTrigger("0 */1 * * * *")]TimerInfo myTimer,
        //[OrchestrationClient] DurableOrchestrationClient starter,
        ILogger log)
{
        log.LogInformation($"C# Timer triggger function executed at: {DateTime.Now}");
}
```

This one doesn't
```
[FunctionName("Function1")]
public static void Run([TimerTrigger("0 */1 * * * *")]TimerInfo myTimer,
        [OrchestrationClient] DurableOrchestrationClient starter,
        ILogger log)
{
        log.LogInformation($"C# Timer triggger function executed at: {DateTime.Now}");
}
```
But in both case it's not generating an extensions.json file.

I would be interested in your solution and how you troubleshoot this issue.

**Comment by juchom** [comment]
Hi @ConnorMcMahon did you made some progress on this issue?

**Comment by ConnorMcMahon** [comment]
@juchom, sorry for the delay on this. It appears that upgrading Microsoft.NET.Sdk.Functions to 1.0.28 fixed the issues that were on my machine. Can you try this and see if that helps for you?

**Comment by juchom** [comment]
It works now, thanks!

**Comment by AAATechGuy** [comment]
Just FYI, if you debug/run from Visual Studio (F5), somehow, even with latest Microsoft.NET.Sdk.Functions (v1.0.28), its not able to detect AzureFunctions defined in the project. 

I root caused the issue to Project properties > Debug > Working Directory is not set somehow by default. Set it to the actual directory where binaries are found and your AzureFunctions becomes available for debug. 

PS, this would add launchSettings.json /profiles/{projectName}/workingDirectory=/objd/amd64/

![image](https://user-images.githubusercontent.com/3484074/59544356-f0226c00-8ec5-11e9-9fc3-eeeab5e9b5bf.png)

**Comment by ashinzekene** [comment]
Currently having this same issue with Microsoft.NET.Sdk.Functions v3.0.9
