### ISSUE TITLE
OrchestrationBinding: Type not supported in WebJobs

### ISSUE THREAD

**Issue by colindembovsky** [Azure/azure-functions-durable-extension#77]
According to the docs, Durable Functions is an extension of Azure Functions __and__ WebJobs. However, all the samples are for Functions. We're trying to use Durable extensions in a WebJobs project.

I have this code:
```csharp
public static async Task AccountTrigger(
	[QueueTrigger("account")]string account,
	[OrchestrationClient]DurableOrchestrationClient starter,
	TraceWriter log)
{
	var collectorProcessId = await starter.StartNewAsync("ProcessAccount", account);
	log.Info($"Started collection with processId {collectorProcessId}");

	// start the checker loop
	await starter.StartNewAsync("CheckStatus", collectorProcessId);
}
```

When I start the project, this line throws an exception:
```csharp
host.RunAndBlock();
```

The exception is:
```
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException occurred
  HResult=0x80131500
  Message=Error indexing method 'Functions.AccountTrigger'
  Source=Microsoft.Azure.WebJobs.Host
  StackTrace:
   at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(TraceWriter trace, ILogger logger)
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.<IndexTypeAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<CreateAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexProvider.<GetAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostConfigurationExtensions.<CreateJobHostContextAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.WebJobs.JobHost.<RuntimeInitAsync>d__44.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__25.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.WebJobs.JobHost.Start()
   at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
   at WebJob1.Program.Main() in D:\mdata\ws\nwc\VisualCadence\WebJob1\WebJob1\Program.cs:line 54

Inner Exception 1:
InvalidOperationException: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).
```

I see that there is a `UseDurableTask` extension method, but when I try to add that in I get this compile error:

```
The type 'JobHostConfiguration' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.WebJobs.Host, Version=2.1.0.0, ...
```

However, I have a reference to that assembly - but it's version 3.0.0.0.

The question is how to use Durable extensions (such as OrchestrationClient and OrchestrationContext) from a WebJob, not from a function?

**Comment by colindembovsky** [comment]
So I downgraded to the 2.1.0-beta4 of the Microsoft.Azure.WebJobs, Microsoft.Azure.WebJobs.Host and Microsoft.Azure.WebJobs.Extensions packages and this seems to work.
