### ISSUE TITLE
Exception thrown when passing large input to Orchestrator function

### ISSUE THREAD

**Issue by CastleArg** [Azure/azure-functions-durable-extension#814]
**Describe the bug**
A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

**Investigative information**

- Durable Functions extension version:
- Function App version (2.0):
- Programming language used:

***If JavaScript***

- durable-functions npm module version:
"^1.2.2"

**To Reproduce**

1. create large object (presumably >10485760bytes)
2. Pass it to an orchestrator function
await client.startNew(
    'MyOrchestratorFunction',,
    undefined,
    myLargeObject
  );

**Expected behavior**
Can hit breakpoint at start of Orchestrator function and see my input

**Actual behavior**
vague error message in terminal
Executed 'Functions.MyFunc' (Failed, Id=ea7ccb06-aad7-49ee-8d37-bb48ba6a771d)
[21/06/2019 8:32:43 AM] System.Private.CoreLib: Exception while executing function: Functions.MyFunc. System.Private.CoreLib: Result: Failure
Exception: Error
Stack: Error
    at DurableOrchestrationClient.<anonymous> (c:\dev\MyFunc\node_modules\durable-functions\lib\src\durableorchestrationclient.js:291:23)
    at Generator.throw (<anonymous>)
    at rejected (c:\dev\MyFunc\node_modules\durable-functions\lib\src\durableorchestrationclient.js:5:65).

Putting a breakpoint in catch block of durableorchestrationclient.js startnew() reveals the real error and why not logged:
message.error is null.  Inspecting message itself reveals:

"Request body larger than maxBodyLength limit"
This appears to be from axios default maxBodyLength limit when trying to post to durable task for status inspection.

**Comment by cgillum** [comment]
This issue looks to be specific to the durable-functions NPM package. Transfering this issue to the **azure-functions-durable-js** repo.
