### ISSUE TITLE
SignalEntityAsync proxy invocation errors

### ISSUE THREAD

**Issue by cecilphillip** [Azure/azure-functions-durable-extension#859]
### Description
Trying to call class based entity via a generated proxy through `SignalEntityAsync` throws an exception.

```csharp
public interface IUserEntity
{
    void AddBundle(LinkBundle bundle);
    IList<LinkBundle> Bundles { get; }
}

// This is throws (in my code)
await client.SignalEntityAsync<IUserEntity>(entityTarget, proxy => proxy.AddBundle(linkDocument))

// This code works fine
await client.SignalEntityAsync(entityTarget, "AddBundle", linkDocument)
```
Here are the packages I’m using:
```xml
<PackageReference Include="Microsoft.ApplicationInsights" Version="2.10.0" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.0.0-beta1" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
```

### Actual behavior
Throws an InvalidOperationException with the following message:
`”Only a return type is void / Task / Task<T>."`

### Stack trace
```
  at Microsoft.Azure.WebJobs.EntityProxyFactory.BuildMethods(TypeBuilder typeBuilder, Type interfaceType) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\EntityProxyFactory.cs:line 94
   at Microsoft.Azure.WebJobs.EntityProxyFactory.CreateProxyType(Type interfaceType) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\EntityProxyFactory.cs:line 45
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Azure.WebJobs.EntityProxyFactory.Create[TEntityInterface](IEntityProxyContext context, EntityId entityId) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\EntityProxyFactory.cs:line 28
   at Microsoft.Azure.WebJobs.DurableEntityProxyExtensions.SignalEntityAsync[TEntityInterface](IDurableOrchestrationClient client, EntityId entityId, Action`1 operation) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\Proxy\DurableEntityProxyExtensions.cs:line 42
   at LinkyLinkEntities.Endpoints.LinkOperations.<SaveLinks>d__11.MoveNext() in C:\Dev\theurlist\backend-csharp-durableentities\src\LinkyLinkEntities\Endpoints\SaveLinks.cs:line 71
```

**Comment by cgillum** [comment]
What does your `IUserEntity` interface look like?

**Comment by cecilphillip** [comment]
The interface is in the code snippet above

**Comment by cgillum** [comment]
Oh sorry. I got confused seeing C# statements and interface definitions in the same code block.

That does seem strange. We'll investigate.

**Comment by cgillum** [comment]
FYI @shibayan if you have any ideas about this.

**Comment by shibayan** [comment]
The reason is that the interface definition contains properties.
Since Proxy operates only on Entity Function (so-called method), it is not permitted to define anything other than methods in the interface.

**Comment by cecilphillip** [comment]
Confirmed that removing the properties from the interface fixed this issue. That behavior is a little nonintuitive IMO. 

It might also end up being problematic attempting to use interfaces from a 3rd party package i.e. the numerous implementations of `ILogger`

**Comment by sebastianburckhardt** [comment]
Perhaps we should indicate in the docs that the "entity interfaces" are limited versions of C# interfaces meant to be used for _remote_ communication with entities. Being a remote interface, it is quite unlikely that existing interfaces can or should be used as-is... for remote call interfaces one tends to make different design choices (because calls and responses have to be serialized, and communication takes a long time). Note that our entity interfaces have other restrictions already, e.g. one. cannot have more than one argument, and all types must be serializable.

**Comment by cecilphillip** [comment]
+1 for docs. Maybe also a roslyn analyzer to flag unsupported interface usage at dev time.

**Comment by cgillum** [comment]
FYI @amdeel, who is currently working on a Roslyn analyzer. Ensuring entity operations have either zero or one arguments would be a good thing for us to flag.

**Comment by cgillum** [comment]
The additional validation has gone out with the v2.0.0-beta2 release.
