### ISSUE TITLE
Cannot have a null property in durable actors .NET (v2)

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#863]
I’m trying to use the new .NET library for durable and have a class like this:

```charp
public class MyActor {
 public string foo;
 public Dictionary<string, string> bar;
 // …
}
```

If after the first execution `bar` is null and hasn’t been initialized, when I try to re-call the actor (using the REST API directly) I get an exception thrown in my code:

> Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll: 'Cannot convert null value to System.Collections.Generic.IDictionary`

Here’s the full exception that has my actual dictionary type and some line references:
<details>
<p>

> Exception has occurred: CLR/Newtonsoft.Json.JsonSerializationException
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll: 'Cannot convert null value to System.Collections.Generic.IDictionary`2[System.Guid,Hollan.Function.FailureRequest]. Path 'FailureWindow', line 1, position 31.'
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at DurableTask.Core.Serializing.DataConverter.Deserialize[T](String data) in C:\source\durabletask\src\DurableTask.Core\Serializing\DataConverter.cs:line 54
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableEntityContext.Microsoft.Azure.WebJobs.IDurableEntityContext.GetState[TState](Func`1 initializer) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableEntityContext.cs:line 108
   at Microsoft.Azure.WebJobs.TypedInvocationExtensions.<DispatchAsync>d__0`1.MoveNext() in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\EntityScheduler\TypedInvocationExtensions.cs:line 90
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.<InvokeAsync>d__2.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20

</p>
</details>

**Comment by cecilphillip** [comment]
I had a similar issued. I updated my entity to initialize the collection to an empty instance

```csharp
    public class UserEntity: IUserEntity
    {
        [JsonProperty("userId")]
        public string UserId { get; set; }

        [JsonProperty("bundles")]
        public IList<LinkBundle> Bundles { get; } = new List<LinkBundle>();
        
        . . .
    }
```

**Comment by cgillum** [comment]
@amdeel can you help look into this issue?

**Comment by amdeel** [comment]
@jeffhollan I tried to reproduce this issue but didn't get an exception thrown. Do you have any more details about this issue that I could use to reproduce it?
