### ISSUE TITLE
Await in async activity causes null reference exception

### ISSUE THREAD

**Issue by Tomatipasta** [Azure/azure-functions-durable-extension#870]
Hello

I am experiencing a weird null pointer in async activity with durable functions. Can somebody explain? Seems like await while reading from input stream causes a null pointer exception.

**Dotnet version**: 2.2.300
**Microsoft.NET.Sdk.Functions**: 1.0.27
**Microsoft.Azure.WebJobs.Extensions.DurableTask**: 1.8.3
**Microsoft.Azure.DocumentDB.Core**: 2.1.3
**Microsoft.Azure.WebJobs.Extensions.CosmosDB**: 3.0.2
**Microsoft.Azure.WebJobs.Extensions.Storage**: 3.0.4

The snippet that doesn't work.
```
        [FunctionName("processRoutingFileActivity")]
        public static async void storeRouterCVCRequireds(
            [ActivityTrigger] Newtonsoft.Json.Linq.JObject input,
            [Blob("router-upload/{data.blobName}", FileAccess.Read)] Stream blob,
            [CosmosDB(
                            databaseName: Router.ROUTER_DATABASE,
                            collectionName: "{data.collection}",
                            ConnectionStringSetting = Router.ROUTER_CONNECTION_CONFIG_STRING)] IAsyncCollector<RoutingElement> routingElementsOut,
            ILogger log
            )
        {
            StreamReader reader = new StreamReader(blob);

            while (!reader.EndOfStream)
            {
                string line = reader.ReadLine();

                log.LogInformation($"Line {line}");

                Disabled3D entry = new Disabled3D("1", line);
                await routingElementsOut.AddAsync(entry);
            }


        }
```

The snippet that works.
```
        [FunctionName("processRoutingFileActivity")]
        public static async void storeRouterCVCRequireds(
            [ActivityTrigger] Newtonsoft.Json.Linq.JObject input,
            [Blob("router-upload/{data.blobName}", FileAccess.Read)] Stream blob,
            [CosmosDB(
                            databaseName: Router.ROUTER_DATABASE,
                            collectionName: "{data.collection}",
                            ConnectionStringSetting = Router.ROUTER_CONNECTION_CONFIG_STRING)] IAsyncCollector<RoutingElement> routingElementsOut,
            ILogger log
            )
        {
            StreamReader reader = new StreamReader(blob);

            List<string> lines = new List<string>();
            while (!reader.EndOfStream)
            {
                string line = reader.ReadLine();

                log.LogInformation($"Line {line}");
                lines.Add(line);
            }

            foreach (string line in lines)
            {
                Disabled3D entry = new Disabled3D("1", line);
                await routingElementsOut.AddAsync(entry);
            }

            log.LogInformation($"Processing for {fileName} finished");
        }
```

The exception with broken await example.
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.WindowsAzure.Storage.Blob.BlobReadStreamBase.ConsumeBuffer(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.WindowsAzure.Storage.Blob.BlobReadStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Storage.Blob.BlobReadStream.<>c__DisplayClass4_0.<Read>b__0()
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun)
   at Microsoft.Azure.WebJobs.Host.Blobs.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\DelegatingStream.cs:line 107
   at Microsoft.Azure.WebJobs.Host.Blobs.WatchableReadStream.Read(Byte[] buffer, Int32 offset, Int32 count) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Blobs\WatchableReadStream.cs:line 66
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at Company.Function.ParseFiles.storeRouterCVCRequireds(JObject input, Stream blob, IAsyncCollector`1 routingElementsOut, ILogger log) in /Users/artur.luik/Desktop/azure_dev/src/Functions/ProcessRoutingFiles.cs:line 175
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by cgillum** [comment]
Are you confident that this is an issue with Durable Functions?

One thing that might be worth trying - can you reproduce this problem if instead of using the `[Blob]` input binding, you use the Azure Storage SDK directly to read the blob? If that works but the `[Blob]` input binding doesn't, then it could be an issue related to Azure Storage SDK mismatches between Azure Functions and your code. It could also be something specific to the WebJobs `WatchableReadStream` that I see in your callstack, which I'm not particularly familiar with.
