### ISSUE TITLE
Token PropertyName in state ArrayStart would result in an invalid JSON object. Path ''.

### ISSUE THREAD

**Issue by ElanHasson** [Azure/azure-functions-durable-extension#922]
### Description
> Getting a serialization error when calling IDurableOrchestrationContext.CallActivityWithRetryAsync

```
Token PropertyName in state ArrayStart would result in an invalid JSON object. Path ''

   at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
   at Newtonsoft.Json.JsonTextWriter.WritePropertyName(String name)
   at Newtonsoft.Json.Linq.JProperty.WriteTo(JsonWriter writer, JsonConverter[] converters)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at DurableTask.Core.Serializing.JsonDataConverter.Serialize(Object value, Boolean formatted) in C:\source\durabletask\src\DurableTask.Core\Serializing\JsonDataConverter.cs:line 76
   at DurableTask.Core.Serializing.JsonDataConverter.Serialize(Object value) in C:\source\durabletask\src\DurableTask.Core\Serializing\JsonDataConverter.cs:line 60
   at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskInternal>d__17.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 87
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskToWorker>d__16`1.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 81
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DurableTask.Core.TaskOrchestrationContext.<ScheduleTask>d__15`1.MoveNext() in C:\source\durabletask\src\DurableTask.Core\TaskOrchestrationContext.cs:line 73
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at DurableTask.Core.RetryInterceptor`1.<Invoke>d__4.MoveNext() in C:\source\durabletask\src\DurableTask.Core\RetryInterceptor.cs:line 79
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at DurableTask.Core.RetryInterceptor`1.<Invoke>d__4.MoveNext() in C:\source\durabletask\src\DurableTask.Core\RetryInterceptor.cs:line 79
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableOrchestrationContext.<CallDurableTaskFunctionAsync>d__85`1.MoveNext() in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableOrchestrationContext.cs:line 648
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at BestDeal.Services.MarketPlace.AzureFunctions.Domain.DomainEventBroker.<DomainPublishEvents>d__5.MoveNext() in C:\Users\elan\Source\Repos\The Best Deal\src\Services\MarketPlace\BestDeal.Services.MarketPlace.AzureFunctions\Domain\DomainEventBroker.cs:line 56
```
### Expected behavior
The activities should be fanned out without a serialization issue.

### Actual behavior
An exception is thrown.

### Relevant source code snippets
```csharp

        [FunctionName(nameof(DomainPublishEvents))]
        public async Task DomainPublishEvents(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var events = context.GetInput<dynamic>();
            var eventList = new List<Task>();
            foreach (var @event in events)
            {
                eventList.Add(context.CallActivityWithRetryAsync<bool>(nameof(this.DomainPublishEvent),
                     new RetryOptions(TimeSpan.FromSeconds(5), 20) { BackoffCoefficient = 0.8 }, @event));
            }

            await Task.WhenAll(eventList);
        }

        [FunctionName(nameof(DomainPublishEvent))]
        public async Task<bool> DomainPublishEvent([ActivityTrigger] IDurableActivityContext context)
        {
            var @event = context.GetInput<dynamic>();

            await PublishDomainEvents(@event); // not included as it just publishes events to Azure Storage Queue
            return true;
        }

```

### Known workarounds
None.

### App Details
Local Run.
- **Durable Functions extension version (e.g. v1.8.3)**: 2.0 beta 2
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

Will try in Azure and update with more info.

**Comment by ElanHasson** [comment]
The problem was I was passing a single `dynamic` object and using `context.GetInput<dynamic>()`, and then using a `foreach` over the single `dynamic` object.

I think it is something to do with Json.Net's flexibility :)

The error messages could be friendlier, and this could be easier to debug.

**Comment by cgillum** [comment]
That's a very odd serialization error. Indeed, it seems like there is something about that dynamic `@event` object that Json.NET doesn't like. What kind of object is it? I'm wondering if it would be possible for us to reproduce locally.

I don't expect there's much we can do to fix the serialization error, but would it be sufficient for us to perhaps catch serialization errors like this and rethrow a friendlier exception?

**Comment by ElanHasson** [comment]
Hi Chris,

It's basically a POCO. I can try to isolate and repro.

I think this could be something for the Analyzer to handle perhaps. 

I also think giving more info about *what* is being serialized. Something like enhancing the exception data with an instance of the object being serialize/string of the serialized data depending on context.
