### ISSUE TITLE
FunctionFailedException contains no information about the error

### ISSUE THREAD

**Issue by worldspawn** [Azure/azure-functions-durable-extension#929]
### Description
I have an orchestration calling a sub-orchestration. Actually its more like a sub-sub-sub orchestration. This orchestration is failing with the error:

```
Microsoft.Azure.WebJobs.FunctionFailedException: The orchestrator function 'RunRemoteOrchestration' failed: "". See the function execution logs for additional details.
   at Microsoft.Azure.WebJobs.DurableOrchestrationContext.CallDurableTaskFunctionAsync[TResult](String functionName, FunctionType functionType, String instanceId, RetryOptions retryOptions, Object input) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\DurableOrchestrationContext.cs:line 508
   at Drawboard.SourceFileProcessing.PdfTextOrchestration.Run(DurableOrchestrationContext context) in /src/dotnet-function-app/Pdf/TextExtraction/PdfTextOrchestration.cs:line 40
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\Listener\TaskOrchestrationShim.cs:line 91
```
The exceptions' inner exception is null. The text `See the function execution logs for additional details.` is baffling because I am already looking at my log output.

I added a complete try catch block in the orchestration that it is calling and receive no errors in my log. I also receive no error messages from the functions runtime informing me that the function "RunRemoteOrchestration" execution failed (just that it failed in the context of the caller).

This function is running in a container, based off the azure functions container image hosted in AKS.

I would like to know how I can determine what the cause of the exception is.

**Comment by worldspawn** [comment]
Some code for context. This is the orchestration that fails (which is ran as a sub-orchestration). I do get the log entry output from the catch block.

``` csharp
[FunctionName(Constants.FunctionNames.PdfTextOrchestration)]
        public async Task<IEnumerable<(string, string)>> Run([OrchestrationTrigger] DurableOrchestrationContext context) {
            string jobId = null;
            string fileId = null;
            try {
                var message = context.GetInput<JObject>();
                var fileUri = message.SelectToken("fileUri").Value<string>();
                jobId = message.SelectToken("jobId").Value<string>();
                fileId = message.SelectToken("fileId").Value<string>();
                var pageNo = message.SelectToken("pageNo").Value<int>();
                var runTextExtraction = message.SelectToken("runTextExtraction")?.Value<bool>() ?? false;

                var instanceId = context.NewGuid().ToString("N");
                await context.CallActivityWithRetryAsync(Constants.FunctionNames.EventNotify, new RetryOptions(TimeSpan.FromSeconds(10), 2), new {
                        jobId,
                        fileUri,
                        fileId,
                        instanceId,
                        @event = "InstanceIdCreated"
                    });

                var pdfTextArtifacts = await context.CallSubOrchestratorAsync<(string imageUri, string imageDataUri, string textUri)>("RunRemoteOrchestration", instanceId, new {
                        orchestratorName = Constants.FunctionNames.GetPdfTextArtifacts,
                        payload = message});
                
                var imageUri = pdfTextArtifacts.imageUri;
                var imageDataUri = pdfTextArtifacts.imageDataUri;

                var azureResult = await context.CallActivityWithRetryAsync<(string type, string uri)>(Constants.FunctionNames.AzureTextExtraction, 
                    new RetryOptions(TimeSpan.FromSeconds(30), 5), new {
                        jobId,
                        fileUri,
                        pageNo,
                        imageUri,
                        imageDataUri
                    });

                var finalOcrResult =  await context.CallActivityWithRetryAsync<(string type, string uri)>(Constants.FunctionNames.CreateOcrArtifact, 
                    new RetryOptions(TimeSpan.FromSeconds(30), 5), new {
                        jobId,
                        fileUri,
                        pageNo,
                        pdfTextUri = pdfTextArtifacts.textUri,
                        azureDataUri = azureResult.uri
                    });

                _logger.LogTrace("PdfTextOrchestration Succeeded. {jobId}/{fileId}", jobId, fileId);

                return new [] {
                    azureResult,
                    finalOcrResult
                };
            }
            catch (Exception ex) {
                _logger.LogError(ex, "PdfTextOrchestration Failed. {jobId}/{fileId}", jobId, fileId);
                throw;
            }
        }
```

Its calling the below code. I never get the explicit log messages from the catch blocks.

``` csharp
[FunctionName("RunRemoteOrchestration")]
        public async Task<JToken> RunRemoteOrchestration([OrchestrationTrigger] DurableOrchestrationContext context)
        {
            try {
                var input = context.GetInput<JObject>();
                string statusQueryGetUri = null;
                _logger.LogTrace("Executing RunRemoteOrchestration");

                if (input.SelectToken("statusQueryGetUri") == null) {
                    _logger.LogTrace("Executing RunRemoteOrchestration - calling Start {input}", input.ToString());
                    statusQueryGetUri = await context.CallActivityAsync<string>("StartRemoteOrchestration", input);
                    input.Add("statusQueryGetUri", new JValue(statusQueryGetUri));
                }
                else {
                    _logger.LogTrace("Executing RunRemoteOrchestration - statusUriExists {input}", input.ToString());
                    statusQueryGetUri = input.SelectToken("statusQueryGetUri").Value<string>();
                }

                _logger.LogTrace("Executing RunRemoteOrchestration - Calling CheckIsComplete {input}", input.ToString());
                var result = await  context.CallActivityAsync<(bool success, string output)>("CheckIsComplete", statusQueryGetUri);
                if (result.success) {
                    _logger.LogTrace("Executing RunRemoteOrchestration - CheckIsComplete true {input}", input.ToString());

                    return JToken.Parse(result.output);                
                }

                _logger.LogTrace("Executing RunRemoteOrchestration - CheckIsComplete false {input}", input.ToString());

                context.ContinueAsNew(input);
                return null;
            }
            catch (Exception ex) {
                _logger.LogError(ex, "RunRemoteOrchestration Failed. Inner Exception: {ex}", ex.InnerException);
                throw;
            }
        }

        [FunctionName("StartRemoteOrchestration")]
        public async Task<string> StartRemoteOrchestration([ActivityTrigger] JObject message)
        {
            try {
                var orchestratorName = message.SelectToken("orchestratorName").Value<string>();
                var url = $"http://{RemoteHost}/api/orchestrators/{orchestratorName}/wait";
                var payload = message.SelectToken("payload").Value<JObject>();
                _logger.LogDebug("Starting Remote Orchestration to {url} with payload {payload}", url, payload);
                
                using (var response = await Client.PostAsync(
                    url,
                    new StringContent(payload.ToString())))
                {
                    if (response.IsSuccessStatusCode) {
                        var reply = await response.Content.ReadAsStringAsync();

                        _logger.LogDebug("Reply from Remote Orchestration to {url} with payload {payload} was {status} {reply}", url, payload.ToString(), response.StatusCode, reply);

                        return JObject.Parse(reply).SelectToken("statusQueryGetUri").Value<string>();
                    }
                    else {
                        var reply = await response.Content.ReadAsStringAsync();
                        _logger.LogError("Failure reply from Remote Orchestration to {url} with payload {payload} was {status} {reply}", url, payload.ToString(), response.StatusCode, reply);
                        throw new Exception("StartRemoteOrchestration failed.");
                    }
                }
            }
            catch (Exception ex){                
                _logger.LogError(ex, "StartRemoteOrchestration Failed {message}", message);
                throw;
            }
        }

        [FunctionName("CheckIsComplete")]
        public async Task<(bool success, string output)> CheckIsComplete([ActivityTrigger] string statusUrl)
        {            
            try {
                _logger.LogTrace("Check Status Url {statusUrl}", statusUrl);
                using (var response = await Client.GetAsync(statusUrl))
                {
                    if (response.StatusCode == HttpStatusCode.OK)
                    {
                        var reply = await response.Content.ReadAsStringAsync();
                        _logger.LogDebug("Check Status Url {statusUrl}", statusUrl);
                        _logger.LogTrace("Status Url {statusUrl} returned OK with reply {reply}", statusUrl, reply);
                        var output = JObject.Parse(reply).SelectToken("output");
                        return (true, output.ToString());
                    }
                    else {
                        if (response.StatusCode == HttpStatusCode.Accepted) {
                            await Task.Delay(TimeSpan.FromSeconds(2));
                            return (false, null);
                        }
                        else {
                            //ToDo: extract error from response?
                            throw new Exception("Remote execution has failed.");
                        }
                    }
                }
            }
            catch (Exception ex) {
                _logger.LogError(ex, "CheckIsComplete Failed {statusUrl}", statusUrl);
                throw;
            }
        }
```

**Comment by cgillum** [comment]
That's very odd. You mentioned that you are running in AKS...how are you capturing logs?

Unfortunately, we don't have access to any telemetry when you run outside of Azure Functions or Azure App Service, so I'm not sure how to best investigate this. By chance would you be able to provide a minimal repro that we could use to try and reproduce the issue on our side?

**Comment by worldspawn** [comment]
I have this defined:

`ENV AzureFunctionsJobHost__Logging__Console__IsEnabled=true`

So I get entries like 

```
09 Sep 2019 17:04:49.502
 Executing 'CheckIsComplete' (Reason='', Id=41b3de17-01f4-4cda-a81b-9f85119a64f0)
09 Sep 2019 17:04:49.501
 f16cdc6295155507b17f890b3f90df79: Function 'CheckIsComplete (Activity)' started. IsReplay: false. Input: (780 bytes). State: Started. HubName: SourceFileHub. AppName: . SlotName: . ExtensionVersion: 1.8.3. SequenceNumber: 257.
09 Sep 2019 17:04:49.486
 f16cdc6295155507b17f890b3f90df79: Function 'RunRemoteOrchestration (Orchestrator)' awaited. IsReplay: false. State: Awaited. HubName: SourceFileHub. AppName: . SlotName: . ExtensionVersion: 1.8.3. SequenceNumber: 256.
```

Any other logging I get is manual. We're outputting logs to seq.

Just got to work and I've been getting this error all night which tells that the durable functions runtime has probably gone a bit off the rails (no one has been submitting the same workload all night long over and over).. I noticed its the same instance id.

![image](https://user-images.githubusercontent.com/819581/64574499-15ceec80-d3b3-11e9-8827-35896a7dcb95.png)

Digging in this further I queries the instances table for the matching instance id and its RuntimeStatus is still "Running". The created and last updated time are `2019-09-05T00:04:47.967Z`

Looking for history entries with the same instance id I have a single entry

![image](https://user-images.githubusercontent.com/819581/64574482-ffc12c00-d3b2-11e9-9ebf-d6403c2b395e.png)

So I dont think I can produce a repro.

**Comment by worldspawn** [comment]
Is there a tool that visualises the data in the durable tables/queues?

**Comment by ElanHasson** [comment]
Hi @worldspawn,

Check out https://github.com/yuka1984/DurableFunctionsHistoryViewer. A great idea, however I'm finding that it chokes hard when you have more than a few hundred instances in the history.

I'm guessing @cgillum has some great Kusto queries that would prove extremely useful. Perhaps he can share them here or in a repo somewhere.

I do think it would be cool to have a timeline view like Application Insights provides. Perhaps some of the queries can be used to produce them.

**Comment by worldspawn** [comment]
Cheers for that @ElanHasson.

**Comment by worldspawn** [comment]
I've resolved this myself just by stopping the functions and deleting the storage tables for them. After that I havent had further issues. Feel free to close, if you would like any further info just ask.
